### ISSUE TITLE
How to connect to the MySQL server

### ISSUE THREAD

**Issue by samholmes** [Chassis/Chassis#100]
I'm new to using Vagrant in general. How do I connect to the MySQL server that Chassis sets up for me in the VM?

**Comment by noplanman** [comment]
I've run into this not working with PhpStorm.
SequelPro works perfectly, but PhpStorm tells me that the SSH authorisation failed, even though I'm using the exact same settings.

Is there a setting that needs adjusting somewhere?

![phpstorm-chassis-mysql](https://cloud.githubusercontent.com/assets/9423417/21965335/2a773ce6-db5e-11e6-8db8-2b14120d8e96.png)

**Comment by BronsonQuick** [comment]
@noplanman Digging into this for you now!

**Comment by BronsonQuick** [comment]
@noplanman So change this section to Auth type: Password then use `vagrant`as the password.

You should be able to connect and see this:

![phpstorm](https://cloud.githubusercontent.com/assets/1377956/21970966/d45c39ac-dbf7-11e6-82a6-748b04dbc099.png)

**Comment by noplanman** [comment]
@BronsonQuick Spot on!
Should have thought of that myself :grin:
