### ISSUE TITLE
vagrant fails after fresh chassis clone, on "include?" method in Vagrantfile

### ISSUE THREAD

**Issue by dirad** [Chassis/Chassis#1017]
Windows 10 
Vagrant 2.3.4

It started with an existing install that i tried to `git pull` to update in order to recover from [# ](https://github.com/Chassis/Chassis/issues/992#)
but now any `vagrant up` on fresh chassis clones follows with this error :

```
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /lem2/Vagrantfile
Line number: 0
Message: undefined method `include?'
```

Other existing vagrant boxes that are also provisioned with Chassis work fine!

**Comment by BronsonQuick** [comment]
Hey @dirad,

For now can you please comment out this section:
https://github.com/Chassis/Chassis/blob/main/Vagrantfile#L239-L244

Can you please let me know if you have any custom configs setup? That'll help me to see if I can replicate this.

Can you also let me know the exact version of Vagrant and VirtualBox that you have installed and also which operating system you are using?

Thanks!

**Comment by dirad** [comment]
Holy mackerel that did it.  🙏

As i mentioned, I made sure this wasn't about my specific site config. 
It also happened on a new folder without anything relating to vagrant or other git repos in it.

Could it have been the terminal or the shell i was using?
Nothing fancy.  I'm using bash from the  git/bin package for windows.
I tried on two terminals.    Cmder and Tabby.   
I now also verified that it fails [on a fresh git clone, without any config changes] on CMD and Powershell own terminals & shells.


Vagrant 2.3.4
Virtualbox 7.0.4 r154605
Windows 10

**Comment by dirad** [comment]
> 

I do realize some strangeness though.
WP ins't installed.. I have to run the installer.

**Comment by BronsonQuick** [comment]
Sorry I missed the version of Vagrant and Windows 10 that you mentioned earlier. I had only just woken up when I saw your issue 😅

The first issue was that I forgot to think about Windows shells so I definitely need to revisit that whole block that I link you too. For now you'll need to keep that whole section commented out or checkout Chassis at this sha: https://github.com/Chassis/Chassis/commit/796ededf63314070a54d1cdac1266dc20d9f4230

Everything else should work fine for you when you check that out and run `vagrant up` or `vagrant provision`. I'll do a PR tomorrow morning to revert a few things in regards to the shell detection and make sure I do a smart fallback for Windows as well. Sorry for the inconvenience!

**Comment by BronsonQuick** [comment]
@dirad This should be fixed for you now. I just tested it on Windows 10 and it does what it was supposed to do on all operating systems now. Turns out Windows didn't like the `()` around my `includes?` for checking the shell!
