### ISSUE TITLE
Automate updates to WordPress.

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/Chassis#1054]
The updates to WordPress could be automated via a GitHub action running on a schedule.

The process could be something along the following lines:

* Query `http://api.wordpress.org/core/version-check/1.7/` (using HTTP ensures only the latest release is shown)
* Regex to figure out the latest tag
* If the tag does not match the current version of WP in Chassis, create a PR to run an update

As new releases are tagged prior to the official release, we're unable to use the GitHub API to query tags on https://github.com/wordpress/wordpress as it's theoretically possible a release gets abandoned post tagging if a serious issue arises.

**Comment by BronsonQuick** [comment]
Apparently I forgot to close this issue.
