### ISSUE TITLE
Multisite Performance Issue after migrating databases from production

### ISSUE THREAD

**Issue by tgelles** [Chassis/Chassis#119]
I set up multisite subdirectories without any issues, but when I used Migrate DB Pro to pull down my production site's content/db, there are serious performance issues and many 504 timeout errors.

I see Vagrant's docs have information http://docs.vagrantup.com/v2/synced-folders/nfs.html about using NFS, but editing the VagrantFile to allow NFS threw up this error:

`The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o 'vers=3,udp' 172.28.128.1:'/Users/cpecken1/Documents/websites/myproject' /vagrant
Stdout from the command:
Stderr from the command:
stdin: is not a tty
mount.nfs: requested NFS version or transport protocol is not supported`

Has anyone experienced this problem or something similar when a) pulling from their production db before or b) attempting to set up an NFS server to boost performance?

**Comment by tgelles** [comment]
Essentially, adding:

`config.vm.synced_folder ".", "/vagrant", :nfs => true, :mount_options => ['dmode=777','fmode=777']`

to line 107 in the VagrantFile does not work.

Where are we supposed to add the code to allow NFS Mount?

**Comment by BronsonQuick** [comment]
I'm going to close this one as it's an old issue. We did add a fix for this in https://github.com/Chassis/Chassis/pull/371 but had to revert it and it will eventually be tackled again in https://github.com/Chassis/Chassis/issues/377
