### ISSUE TITLE
No PHP errors

### ISSUE THREAD

**Issue by samholmes** [Chassis/Chassis#121]
If I forget a semi-colon, I don't get an error message displayed on the page. Instead, I just get a blank page. Why?

Maybe Chassis has a PHP configured to puke out errors to a log file? Where is this log file if so?

**Comment by tareiking** [comment]
Yo @samholmes - WP / PHP Error display is turned off by default. You can adjust your WP Debug settings as mentioned here : http://codex.wordpress.org/Debugging_in_WordPress.

In your case, you probably want to add the following to either wp-config.php or local-config.php depending on your setup:

```
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);
```
