### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by zanematthew** [Chassis/Chassis#122]
I'm sure this isn't the place to post edits for the "docs", but I couldn't find anywhere else, and I feel that the install process can be slightly improved.

It should be noted that Puppet is included with "[Whats in the box](http://docs.chassis.io/en/latest/quickstart/#what-s-in-the-box)"

In the "[Installation](http://docs.chassis.io/en/latest/quickstart/#installing)", step 4 can be removed :)

>Make a copy of local-config-sample.php and rename to local-config.php

1. There is no need for the `local-config.php`
1. The file `local-config-db.php` was already there

http://docs.chassis.io/en/latest/quickstart/#installing

**Comment by BronsonQuick** [comment]
Hey @zanematthew, thanks for opening this issue. `local-config.php` and `local-config-db.php` are slightly different files. Maybe we should update the docs to say that:
> Make a copy of local-config-sample.php and rename to local-config.php
is optional instead.

Thanks again for bringing this to our attention :+1:

**Comment by zanematthew** [comment]
No problem, it was even easier to install than the steps listed. Glad I could help.
