### ISSUE TITLE
WordPress Networking not fully supported

### ISSUE THREAD

**Issue by zanematthew** [Chassis/Chassis#125]
After following the docs for [Multisite](http://docs.chassis.io/en/latest/config/#multisite) (which should actually be labeled WordPress Networking), I receive a message saying my blogs table is empty.

It appears that during the provision that entries are not entered into the *_blogs table.

Here's what I did:

1. Installed Chassis following configuration
1. Set `multisite: subdomains` via the config.yaml, note there's some confusion here as the config says "[only subdirectories](https://github.com/Chassis/Chassis/blob/master/config.yaml#L41)" are available, yet the site raves about using sub-domains

> Subdirectory mode is great, but subdomain mode is even better.

I then:

1. Changed my hosts in yaml as well, and added the correct IP to my `/etc/hosts` file
1. Finally ran; `vagrant provision`
1. Visited my site foo.local, only to see the "Error establishing a database connection"
1. I then took it upon myself to visit foo.local/wp, and to see a message saying I'm missing tables
1. Visited foo.local/phpmyadmin to see that the sz_blogs table is empty

**Comment by zanematthew** [comment]
I've dug deeper into this, and it appears that when doing the set-up Chassis writes to the URL http://vagrant.local/ to various locations in the db for WordPress networking, even though the `hosts:` is set to site.local via the config.yaml

**Comment by zanematthew** [comment]
Seems there's other open issues relating to WordPress Networking #79, and #42.

Also the docs found [here](https://github.com/Chassis/chassis.github.io/blob/c455dabcf4c7cf9ae2310487744d1ca71f0b9738/index.md#multisite) my need to be removed/update to reflect the issues with networking/multisite.

When time permits I'll entertain this more, possibly contribute code (vs. issues)...until we meet again Chassis.

Its been nice, but back to my current work flow; `rm -rf chassis.local`

**Comment by rmccue** [comment]
Hi @zanematthew!

> After following the docs for Multisite (which should actually be labeled WordPress Networking)

WP networks are a specific piece of data in WP, but "multisite" is the overarching terminology for the functionality. "Networking" isn't a term used to describe either.

We need to get #79 merged in ASAP, I'd thought it had been already, so apologies for the error in the docs.

> I've dug deeper into this, and it appears that when doing the set-up Chassis writes to the URL http://vagrant.local/ to various locations in the db for WordPress networking, even though the hosts: is set to site.local via the config.yaml

Do you have specific examples here? We test with other URLs regularly, and the only place `vagrant.local` appears in the codebase is in `config.yaml`, so it's possible that your instance may have been misconfigured?

Thanks for trying Chassis, and sorry it didn't work for you. We'd be happy to run though things with you and get it sorted when you have time :)
