### ISSUE TITLE
Running multiple Chassis boxes simultaneously 

### ISSUE THREAD

**Issue by greaveselliott** [Chassis/Chassis#126]
Hi all,
I have been attempting to run two Chassis boxes, but I get the following port error:

--- 
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 2222 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 22, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine is in a state which doesn't allow modifying port forwarding.

---
Not that I understand these config files at all, I decided to take a breath and brave the journey into reading the config.yaml and .vagrantFile looking for some kind of port configuration setting - but found nothing obvious. 

Does anyone know what settings I need to change so the ports of my boxes no longer conflict with each other?

 Thanks in advanced,

- Elliott

**Comment by BronsonQuick** [comment]
Hey @greaveselliott,

I've actually been doing this all day today actually to write and test a plugin for [RAMP](https://crowdfavorite.com/ramp/). All you need to do is copy `config.yaml` and paste it in the root as `config.local.yaml` and change:
```
hosts:
    - vagrant.local
```
to something like:
```
hosts:
    - elliott.local
```
then run `vagrant provision` and you should be able to get to [elliott.local](http://elliott.local)

Then do the same with the second Chassis install and give the host a different name. e.g. `greaves.local`.

I hope that helps :smile:

**Comment by greaveselliott** [comment]
Awesome! worked perfectly.

I forgot to run “vagrant provision” after making changes to the config XD.

I was changing the config and hoping for the best! :P

Thanks again,

- Elliott

**Comment by BronsonQuick** [comment]
No problem :smile: I'm glad it worked! I should probably add that to our docs :+1:
