### ISSUE TITLE
Update to Wordpress 4.2

### ISSUE THREAD

**Issue by tidalvirus** [Chassis/Chassis#128]
Can you please update WordPress to 4.2? Also, as I'm unclear how you are doing it, it would be awesome if you could write a few notes on how you update wp in Chassis, so in future I might be able to submit a pull request in stead.

It doesn't appear to be a submodule, so I'm a little unclear on how you do it.

I realise you might already be doing this, considering it's been out a few hours now. Thought it might be helpful to get some info on how you update though.

Thanks!

Sid

**Comment by Japh** [comment]
:+1:

I saw @BronsonQuick say he was going to be doing this today, so hopefully he can provide a few notes as well  :)

**Comment by BronsonQuick** [comment]
Hey @tidalvirus, sorry for the delay. I've updated that now via: https://github.com/Chassis/Chassis/commit/618646808e51dbf2e7e543e79a243a67ba9c0d56

The command is `git subtree pull --prefix=wp --squash git@github.com:WordPress/WordPress 4.2`

**Comment by tidalvirus** [comment]
No need to apologise for any delay, it was hardly a long wait!

Thanks for providing the note - guess I need to install the subtree script in my git setup on a couple of my Debian/stable machines. :)

**Comment by BronsonQuick** [comment]
@tidalvirus You can just run `git pull` on your Debian machines and it'll pull down the latest version of WP for you :smile: The above command is the one to use if you ever beat us to updating and want to do a Pull Request back to the repo :+1:

**Comment by tidalvirus** [comment]
It was in fact in case I ever wanted to make a pull request. :)
