### ISSUE TITLE
Worth Noting: Windows CMD must be run in administrator mode

### ISSUE THREAD

**Issue by danieliser** [Chassis/Chassis#135]
Spent over 4 hours trying to figure out why it wouldn't work, kept failing dependancies etc. May be worth adding a note to the directions that mentions windows users need to run cmd as an administrator.

**Comment by BronsonQuick** [comment]
:disappointed: Sorry man. You probably should've dropped an issue here earlier on so we could help you debug it so you didn't lose 4 hours of your life :cry: 

I'm happy to update the docs so no one else hits that same issue. Which version of the following are you running:
- Windows
- Vagrant
- VirtualBox

Can you please copy and paste all the commands you ran over the last 4 hours so we can work out what you tried to run and what failed? Link us to any custom `.yaml` files you've made and any Chassis `extensions` you might've installed as well. Ultimately Chassis is supposed to make WP devs life easier so the fact that Chassis just wasted 4 hours of your life when it normally takes 4 mins to go from zero to a Chassis install pains me!

**Comment by danieliser** [comment]
@BronsonQuick - No big deal, it was 4am when I gave up, then tried this morning with a clear head and figured it may be a permissions issue.

WIndows - 7
Vagrant - Latest
VirtualBox - Latest

Also I basically ran nothing but your own tutorial commands and the ones listed on http://wp-api.org/#rest-api_installation.

Beyond that I spent time researching vagrant and wordpress setups in general to see if I was missing anything key. This is my first go with Vagrant in general so I expected a bit of learning, though I am a Full stack dev capable of building my own stacks in that period of time haha.

Now that I know though it was a stupid mistake on my part not trying that sooner, but a note in the setup guide would make that clear for anybody else that may come along.

No hard feelings. Likely had something to do with it being late :)

**Comment by danieliser** [comment]
What eventually gave it away was that many of the Senza installs were failing due to missing dependancies and the hosts never worked. IE vagrant.local never worked in browser which lead me to realize that when I edit my hosts file I have to open notepad as an admin, so I likely needed to open cmd as one as well.

**Comment by danieliser** [comment]
Also vagrant SSH did work, but trying to call the wp command line resulted in wp command not found.

**Comment by BronsonQuick** [comment]
@danieliser Ahh okay then. It's 4am now in Australia :) I should be asleep I guess haha :smile: So Chassis and the WP-API project are kinda separate from each other even though there is a crossover in these projects due to the devs.

If you were to pretend you'd not encountered the WP-API docs first and followed the docs at: http://docs.chassis.io/en/latest/ do you reckon you would've got up and running with Vagrant and Chassis? For your first run of Vagrant in general I'm disappointed Chassis wasn't fast and easy :cry:

You should go from "nothing" (provided the base Vagrant box is already cached on your machine) to a Chassis WP stack in under 4 minutes. The other "famous" WordPress + Vagrant stack is [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) and it takes a super long time to provision as it's not very lean, hence Chassis existing.

Did you have Bonjour installed as per the docs? http://docs.chassis.io/en/latest/quickstart/#prerequisites If you didn't then `.local` wouldn't have automagically resolved on Windows.

Once you got it up and running after those four hours :sob: and tried to run a wp command, which directory were you in after you ran `vagrant ssh`? Were you in `/vagrant/wp`?

If not then does it work in that directory? Hopefully it does and if that the case we need to update our docs! Because a few of us use Chassis everyday we tend to forget steps in the docs so it's issues like this that help us realise things we're missing so we can add in those missing steps!

**Comment by danieliser** [comment]
Actually I started reading on their site but followed your guide first since it was more in depth than just a few commands to run like theirs. I only tried their commands and setup instructions after multiple failed attempts with your docs.

I tried various things to fix it such as adding ssh to my $paths, digging to the vagrant configs and trying to tweak settings etc. had I simply run cmd as admin all would have likely worked as expected.

Also my wp command seems to run globally now that the box is running properly. Before so many depend an ies failed to install that the box was essentially just linux with mysql. Php-fpm and such wernt working which meant wp cli couldn't install either.

Either way great tool and I'm sure that a simple note for windows vista,7 & 8 users mentioning cmd as admin would make it as simple as you hope.

PS after all the failings I tried VVV as well which also failed and helped lead me to solution. Which I then switched back to chassis so I now have both haha. And yea VVV took substantially longer to run it's setup with the manual copying of each file in wp it seemed.

**Comment by danieliser** [comment]
Ok I lied. Its still not working. Thought it was but left just after the install and never got to test. Upon testing found that host still doesnt resolve and vagrant provision resulted in the following.

C:\Users\Daniel\Documents\Chassis\salonapp>vagrant provision
==> default: Running provisioner: shell...
    default: Running: C:/Users/Daniel/AppData/Local/Temp/vagrant-shell20150508-4
548-x3uwd8.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for vagrant.local in environment productio
n in 8.31 seconds
==> default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DP
kg::Options::=--force-confold --force-yes install php5-fpm' returned 100: Readin
g package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: php5-fpm is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.
==> default: 1 not fully installed or removed.
==> default: After this operation, 0 B of additional disk space will be used.
==> default: Setting up php5-fpm (5.4.40+real-1+deb.sury.org~precise+4) ...
==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5
-fpm: not found
==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.
==> default: dpkg: error processing php5-fpm (--configure):
==> default:  subprocess installed post-installation script returned error exit
status 127
==> default: Errors were encountered while processing:
==> default:  php5-fpm
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: Error: /Stage[main]/Sennza::Php/Package[php5-fpm]/ensure: change fr
om absent to latest failed: Could not update: Execution of '/usr/bin/apt-get -q
-y -o DPkg::Options::=--force-confold --force-yes install php5-fpm' returned 100
: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: php5-fpm is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.
==> default: 1 not fully installed or removed.
==> default: After this operation, 0 B of additional disk space will be used.
==> default: Setting up php5-fpm (5.4.40+real-1+deb.sury.org~precise+4) ...
==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5
-fpm: not found
==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.
==> default: dpkg: error processing php5-fpm (--configure):
==> default:  subprocess installed post-installation script returned error exit
status 127
==> default: Errors were encountered while processing:
==> default:  php5-fpm
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: Notice: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/php.ini]: Depen
dency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/php.ini]: Skip
ping because of failed dependencies
==> default: Notice: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/pool.d/www.conf
]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/pool.d/www.con
f]: Skipping because of failed dependencies
==> default: Notice: /Package[php5-mysql]: Dependency Package[php5-fpm] has fail
ures: true
==> default: Warning: /Package[php5-mysql]: Skipping because of failed dependenc
ies
==> default: Notice: /Package[php5-gd]: Dependency Package[php5-fpm] has failure
s: true
==> default: Warning: /Package[php5-gd]: Skipping because of failed dependencies

==> default: Notice: /Package[php5-curl]: Dependency Package[php5-fpm] has failu
res: true
==> default: Warning: /Package[php5-curl]: Skipping because of failed dependenci
es
==> default: Notice: /Stage[main]/Sennza::Php/Service[php5-fpm]: Dependency Pack
age[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Sennza::Php/Service[php5-fpm]: Skipping becau
se of failed dependencies
==> default: Notice: /Package[nginx]: Dependency Package[php5-fpm] has failures:
 true
==> default: Warning: /Package[nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Sennza/File[/etc/nginx/nginx.conf]: Dependency
 Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Sennza/File[/etc/nginx/nginx.conf]: Skipping
because of failed dependencies
==> default: Notice: /Package[sendmail]: Dependency Package[php5-fpm] has failur
es: true
==> default: Warning: /Package[sendmail]: Skipping because of failed dependencie
s
==> default: Notice: /Package[curl]: Dependency Package[php5-fpm] has failures:
true
==> default: Warning: /Package[curl]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Dependency Pack
age[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Skipping becau
se of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: De
pendency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: S
kipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Dependency Package[
php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Skipping because o
f failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/File[/vagrant]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/File[/vagrant]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/l
ocal-config-db.php]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/
local-config-db.php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/File[/etc/nginx/sites-available/vagrant.local]: Dependency Package[
php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Skipping because o
f failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Dependency Package[ph
p5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Skipping because of
failed dependencies
==> default: Notice: /Stage[main]/Sennza/Service[nginx]: Dependency Package[php5
-fpm] has failures: true
==> default: Warning: /Stage[main]/Sennza/Service[nginx]: Skipping because of fa
iled dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/Mysql::Db[wordpress]/Database[wordpress]: Dependency Package[php5-f
pm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/Mysql::Db[wordpress]/Database[wordpress]: Skipping because of fail
ed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Dependency
 Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Skipping
because of failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]:
 Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]
: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[va
grant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Dependency Pack
age[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[v
agrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Skipping becau
se of failed dependencies
==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/l
ocal-config-extensions.php]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/
local-config-extensions.php]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 14.17 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

C:\Users\Daniel\Documents\Chassis\salonapp>

**Comment by tikot** [comment]
@danieliser try setting box to `ubuntu/trusty64`. I think the issue is with [php.pp](https://github.com/Chassis/Chassis/blob/master/puppet/modules/sennza/manifests/php.pp#L71) when php5-5.6 is added.

**Comment by danieliser** [comment]
@tikot - Can you tell me where I should be looking to change this?

**Comment by tikot** [comment]
@danieliser change the box [Vagrantfile L69](https://github.com/Chassis/Chassis/blob/master/Vagrantfile#L69)

**Comment by danieliser** [comment]
@tikot - That did the trick. After destroying and rebuilding the box now loads and wp command works. I did have to add `172.28.128.3	vagrant.local` to my hosts file which I didn't see mentioned in docs so not sure if thats typical or just another issue I'm seeing.

Is there any possible or particular reasons I'm seeing issues nobody else is experiencing? Other software or installations on the pc that could conflict in such a way?
