### ISSUE TITLE
Vagrant up fails (failed dependencies)

### ISSUE THREAD

**Issue by unfulvio** [Chassis/Chassis#136]
At the first vagrant up or subsequent provisioning something goes wrong - see full error list in the otuput below (failed dependencies):

    $ vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...                                                                                                                                    
    ==> default: Checking if box 'hashicorp/precise64' is up to date...                                                                                                                            
    ==> default: Clearing any previously set forwarded ports...                                                                                                                                    
    ==> default: Clearing any previously set network interfaces...                                                                                                                                 
    ==> default: Preparing network interfaces based on configuration...                                                                                                                            
        default: Adapter 1: nat                                                                                                                                                                    
        default: Adapter 2: hostonly                                                                                                                                                               
    ==> default: Forwarding ports...                                                                                                                                                               
        default: 22 => 2222 (adapter 1)                                                                                                                                                            
    ==> default: Booting VM...                                                                                                                                                                     
    ==> default: Waiting for machine to boot. This may take a few minutes...                                                                                                                       
        default: SSH address: 127.0.0.1:2222                                                                                                                                                       
        default: SSH username: vagrant                                                                                                                                                             
        default: SSH auth method: private key                                                                                                                                                      
        default: Warning: Connection timeout. Retrying...                                                                                                                                          
    ==> default: Machine booted and ready!                                                                                                                                                         
    ==> default: Checking for guest additions in VM...                                                                                                                                             
        default: The guest additions on this VM do not match the installed version of                                                                                                              
        default: VirtualBox! In most cases this is fine, but in rare cases it can                                                                                                                  
        default: prevent things such as shared folders from working properly. If you see                                                                                                           
        default: shared folder errors, please make sure the guest additions within the                                                                                                             
        default: virtual machine match the version of VirtualBox you have installed on                                                                                                             
        default: your host and reload your VM.                                                                                                                                                     
        default:                                                                                                                                                                                   
        default: Guest Additions Version: 4.2.0                                                                                                                                                    
        default: VirtualBox Version: 4.3                                                                                                                                                           
    ==> default: Checking for host entries                                                                                                                                                         
    ==> default: Setting hostname...                                                                                                                                                               
    ==> default: Configuring and enabling network interfaces...                                                                                                                                    
    ==> default: Mounting shared folders...                                                                                                                                                        
        default: /vagrant => C:/Dropbox/Projects/geobench                                                                                                                                          
        default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => C:/Dropbox/Projects/geobench/puppet/manifests                                                                   
    ==> default: Running provisioner: shell...                                                                                                                                                     
        default: Running: C:/Users/Fulvio/AppData/Local/Temp/vagrant-shell20150512-11272-a45994.sh                                                                                                 
    ==> default: stdin: is not a tty                                                                                                                                                               
    ==> default: Running provisioner: puppet...                                                                                                                                                    
    ==> default: Running Puppet with development.pp...                                                                                                                                             
    ==> default: stdin: is not a tty                                                                                                                                                               
    ==> default: Notice: Compiled catalog for vagrant.local in environment production in 22.38 seconds                                                                                             
    ==> default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install php5-fpm' returned 100: Reading package lists...             
    ==> default: Building dependency tree...                                                                                                                                                       
    ==> default: Reading state information...                                                                                                                                                      
    ==> default: php5-fpm is already the newest version.                                                                                                                                           
    ==> default: 0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.                                                                                                                  
    ==> default: 1 not fully installed or removed.                                                                                                                                                 
    ==> default: After this operation, 0 B of additional disk space will be used.                                                                                                                  
    ==> default: Setting up php5-fpm (5.4.40+real-1+deb.sury.org~precise+4) ...                                                                                                                    
    ==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5-fpm: not found                                                                                                
    ==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.                                                                                                                          
    ==> default: dpkg: error processing php5-fpm (--configure):                                                                                                                                    
    ==> default:  subprocess installed post-installation script returned error exit status 127                                                                                                     
    ==> default: Errors were encountered while processing:                                                                                                                                         
    ==> default:  php5-fpm                                                                                                                                                                         
    ==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)                                                                                                                           
    ==> default: Error: /Stage[main]/Sennza::Php/Package[php5-fpm]/ensure: change from absent to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-c
    onfold --force-yes install php5-fpm' returned 100: Reading package lists...                                                                                                                    
    ==> default: Building dependency tree...                                                                                                                                                       
    ==> default: Reading state information...                                                                                                                                                      
    ==> default: php5-fpm is already the newest version.                                                                                                                                           
    ==> default: 0 upgraded, 0 newly installed, 0 to remove and 181 not upgraded.                                                                                                                  
    ==> default: 1 not fully installed or removed.                                                                                                                                                 
    ==> default: After this operation, 0 B of additional disk space will be used.                                                                                                                  
    ==> default: Setting up php5-fpm (5.4.40+real-1+deb.sury.org~precise+4) ...                                                                                                                    
    ==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5-fpm: not found                                                                                                
    ==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.                                                                                                                          
    ==> default: dpkg: error processing php5-fpm (--configure):                                                                                                                                    
    ==> default:  subprocess installed post-installation script returned error exit status 127                                                                                                     
    ==> default: Errors were encountered while processing:                                                                                                                                         
    ==> default:  php5-fpm                                                                                                                                                                         
    ==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)                                                                                                                           
    ==> default: Notice: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/php.ini]: Dependency Package[php5-fpm] has failures: true                                                                     
    ==> default: Warning: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/php.ini]: Skipping because of failed dependencies                                                                            
    ==> default: Notice: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/pool.d/www.conf]: Dependency Package[php5-fpm] has failures: true                                                             
    ==> default: Warning: /Stage[main]/Sennza::Php/File[/etc/php5/fpm/pool.d/www.conf]: Skipping because of failed dependencies                                                                    
    ==> default: Notice: /Package[php5-mysql]: Dependency Package[php5-fpm] has failures: true                                                                                                     
    ==> default: Warning: /Package[php5-mysql]: Skipping because of failed dependencies                                                                                                            
    ==> default: Notice: /Package[php5-gd]: Dependency Package[php5-fpm] has failures: true                                                                                                        
    ==> default: Warning: /Package[php5-gd]: Skipping because of failed dependencies                                                                                                               
    ==> default: Notice: /Package[php5-curl]: Dependency Package[php5-fpm] has failures: true                                                                                                      
    ==> default: Warning: /Package[php5-curl]: Skipping because of failed dependencies                                                                                                             
    ==> default: Notice: /Stage[main]/Sennza::Php/Service[php5-fpm]: Dependency Package[php5-fpm] has failures: true                                                                               
    ==> default: Warning: /Stage[main]/Sennza::Php/Service[php5-fpm]: Skipping because of failed dependencies                                                                                      
    ==> default: Notice: /Package[nginx]: Dependency Package[php5-fpm] has failures: true                                                                                                          
    ==> default: Warning: /Package[nginx]: Skipping because of failed dependencies                                                                                                                 
    ==> default: Notice: /Stage[main]/Sennza/File[/etc/nginx/nginx.conf]: Dependency Package[php5-fpm] has failures: true                                                                          
    ==> default: Warning: /Stage[main]/Sennza/File[/etc/nginx/nginx.conf]: Skipping because of failed dependencies                                                                                 
    ==> default: Notice: /Package[sendmail]: Dependency Package[php5-fpm] has failures: true                                                                                                       
    ==> default: Warning: /Package[sendmail]: Skipping because of failed dependencies                                                                                                              
    ==> default: Notice: /Package[curl]: Dependency Package[php5-fpm] has failures: true                                                                                                           
    ==> default: Warning: /Package[curl]: Skipping because of failed dependencies                                                                                                                  
    ==> default: Notice: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Dependency Package[php5-fpm] has failures: true                                                                               
    ==> default: Warning: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Skipping because of failed dependencies                                                                                      
    ==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Dependency Package[php5-fpm] has failures: true                                                                  
    ==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Skipping because of failed dependencies                                                                         
    ==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Dependency Package[php5-fpm] has failures: true                                                                                   
    ==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Skipping because of failed dependencies                                                                                          
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/vagrant]: Dependency Package[php5-fpm] has failures: true                                   
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/vagrant]: Skipping because of failed dependencies                                          
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Dependency Package[php5-fpm] has failures: true                                           
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Skipping because of failed dependencies                                                  
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Dependency Package[php5-fpm] has failures: true   
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Skipping because of failed dependencies          
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Dependency Package[php5-fpm] has failures: true     
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Skipping because of failed dependencies            
    ==> default: Notice: /Stage[main]/Sennza/Service[nginx]: Dependency Package[php5-fpm] has failures: true                                                                                       
    ==> default: Warning: /Stage[main]/Sennza/Service[nginx]: Skipping because of failed dependencies                                                                                              
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database[wordpress]: Dependency Package[php5-fpm] has failures: true         
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Dependency Package[php5-fpm] has failures
    : true                                                                                                                                                                                         
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database[wordpress]: Skipping because of failed dependencies                
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Skipping because of failed dependencies 
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]: Dependency Package[php5-fpm] h
    as failures: true                                                                                                                                                                              
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]: Skipping because of failed de
    pendencies                                                                                                                                                                                     
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Dependency Package[php5-fpm] has failures: tru
    e                                                                                                                                                                                              
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/Sennza::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Skipping because of failed dependencies      
    ==> default: Notice: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Dependency Package[php5-fpm] has failures: true                                   
    ==> default: Warning: /Stage[main]/Main/Sennza::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Skipping because of failed dependencies                                          
    ==> default: Notice: Finished catalog run in 13.49 seconds                                                                                                                                     
    The SSH command responded with a non-zero exit status. Vagrant                                                                                                                                 
    assumes that this means the command failed. The output for this command                                                                                                                        
    should be in the log above. Please read the output to determine what                                                                                                                           
    went wrong.                                                                                                                                                                                   

The first error shows:
`Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install php5-fpm' returned 100: Reading package lists...`                                                                                                                                                                   `
subsequent errors mention a failed dependencies, in particular with php5-fpm

**Comment by lionel-bijaoui** [comment]
I have the same problem. Is there a solution ?

**Comment by mgratch** [comment]
I have the same error happening when trying to use chassis for the first time, I brought this to @rmccue attention via [Post Status](https://poststatus.com) slack the other day. 

Also I am not sure if this is helpful, but I am also having trouble with provisioning VVV with errors related to getting npm dependencies. https://github.com/Varying-Vagrant-Vagrants/VVV/issues/670 -- perhaps the 2 problems are related?  Perhaps I am just bad with computer... :disappointed:

**Comment by BronsonQuick** [comment]
@mgratch Hrm. I haven't tested with my Windows machine in a while so I'll try and test this on the weekend and see if I can a) replicate it and b) fix it for you.

**Comment by sethrubenstein** [comment]
Yea I'm having a similair problem. 
`==> default: Failed to fetch http://apt.puppetlabs.com/pool/precise/main/f/facter/facter_2.4.4-1puppetlabs1_all.deb  Temporary failure resolving 'apt.puppetlabs.com'
==> default: Failed to fetch http://apt.puppetlabs.com/pool/precise/main/h/hiera/hiera_1.3.4-1puppetlabs1_all.deb  Temporary failure resolving 'apt.puppetlabs.com'
==> default: Failed to fetch http://apt.puppetlabs.com/pool/precise/main/p/puppet/puppet-common_3.8.3-1puppetlabs1_all.deb  Temporary failure resolving 'apt.puppetlabs.com'
==> default: Failed to fetch http://apt.puppetlabs.com/pool/precise/main/p/puppet/puppet_3.8.3-1puppetlabs1_all.deb  Temporary failure resolving 'apt.puppetlabs.com'
==> default: Fetched 2,483 kB in 1min 25s (29.2 kB/s)
==> default: E
==> default: :
==> default: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: stdin: is not a tty
==> default: Could not parse options: invalid option: --hiera_config
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by GuerrillaCoder** [comment]
I am also having this problem

```
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Running provisioner: shell...
    default: Running: C:/Users/mikey/AppData/Local/Temp/vagrant-shell20160423-13124-89oz3m.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for vagrant.local in environment production in 5.42 seconds
==> default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install php5-fpm' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: php5-fpm is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.
==> default: 1 not fully installed or removed.
==> default: After this operation, 0 B of additional disk space will be used.
==> default: Setting up php5-fpm (5.4.45-3+deb.sury.org~precise+1) ...
==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5-fpm: not found
==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.
==> default: dpkg: error processing php5-fpm (--configure):
==> default:  subprocess installed post-installation script returned error exit status 127
==> default: Errors were encountered while processing:
==> default:  php5-fpm
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: Error: /Stage[main]/Chassis::Php/Package[php5-fpm]/ensure: change from absent to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install php5-fpm' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: php5-fpm is already the newest version.
==> default: 0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.
==> default: 1 not fully installed or removed.
==> default: After this operation, 0 B of additional disk space will be used.
==> default: Setting up php5-fpm (5.4.45-3+deb.sury.org~precise+1) ...
==> default: /usr/sbin/invoke-rc.d: 438: /usr/sbin/invoke-rc.d: /etc/init.d/php5-fpm: not found
==> default: invoke-rc.d: initscript php5-fpm, action "start" failed.
==> default: dpkg: error processing php5-fpm (--configure):
==> default:  subprocess installed post-installation script returned error exit status 127
==> default: Errors were encountered while processing:
==> default:  php5-fpm
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: Notice: /Stage[main]/Chassis::Php/File[/etc/php5/fpm/php.ini]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/File[/etc/php5/fpm/php.ini]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis::Php/File[/etc/php5/fpm/pool.d/www.conf]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Chassis::Php/File[/etc/php5/fpm/pool.d/www.conf]: Skipping because of failed dependencies
==> default: Notice: /Package[php5-mysql]: Dependency Package[php5-fpm] has failures: true
==> default: Notice: /Package[php5-gd]: Dependency Package[php5-fpm] has failures: true
==> default: Notice: /Package[php5-curl]: Dependency Package[php5-fpm] has failures: true
==> default: Notice: /Stage[main]/Chassis::Php/Service[php5-fpm]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Package[php5-mysql]: Skipping because of failed dependencies
==> default: Warning: /Package[php5-gd]: Skipping because of failed dependencies
==> default: Warning: /Package[php5-curl]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Chassis::Php/Service[php5-fpm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-db.php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/index.php]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/index.php]: Skipping because of failed dependencies
==> default: Notice: /Package[nginx]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Package[nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/File[/etc/nginx/nginx.conf]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Chassis/File[/etc/nginx/nginx.conf]: Skipping because of failed dependencies
==> default: Notice: /Package[sendmail]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Package[sendmail]: Skipping because of failed dependencies
==> default: Notice: /Package[curl]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Package[curl]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/Exec[wp-cli download]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/local/src/wp-cli/bin/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Wp::Cli/File[/usr/bin/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/vagrant/wp]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/vagrant/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-available/vagrant.local]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/File[/etc/nginx/sites-enabled/vagrant.local]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Chassis/Service[nginx]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Chassis/Service[nginx]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database[wordpress]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database[wordpress]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database_user[wordpress@localhost]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Mysql::Db[wordpress]/Database_grant[wordpress@localhost/wordpress]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Chassis::Site[vagrant.local]/Wp::Site[/vagrant/wp]/Exec[wp install /vagrant/wp]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Dependency Package[php5-fpm] has failures: true
==> default: Warning: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 5.31 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

This issue was reported a year ago, anyone managed to fix it?

**Comment by valerios** [comment]
Tried setting this up on Windows after seeing your talk at WordCamp and I get the same issue.

**Comment by BronsonQuick** [comment]
I'll make sure I give this a whirl on my Windows machine over the weekend and see if I can fix it!

**Comment by valerios** [comment]
I changed PHP version to 5.6 and tried it again. This time it has come up with no problem.

**Comment by BronsonQuick** [comment]
@valerios Ahh interesting. Good to know that works. Thanks for updating the issue! I'll still have a look into 5.4 on Windows!

**Comment by torsybil** [comment]
@valerios answer is the only workaround so far. It is only fair for the [Chassis team ](https://github.com/Chassis): @BronsonQuick to include this in [quickstart instructions](http://docs.chassis.io/en/latest/quickstart/). I am using windows 10. Thanks

**Comment by BronsonQuick** [comment]
@valerios @torsybil. Can you folks try it on 5.5 too and let me know how it goes. If it works on 5.5 I'll change the default value to 5.5 or if that doesn't work then I'll change the default to 5.6 and update the docs accordingly. Thanks!

**Comment by cameronjonesweb** [comment]
I'll just add that WordPress recommends hosts be running 5.6: https://wordpress.org/about/requirements/
I believe it would be best to just change the default to 5.6 both to bring it in line with the recommendation from .org and to get around this bug

**Comment by BronsonQuick** [comment]
@cameronjonesweb I like your thinking regarding that. I'll get a PR up in a tick! ✨
