### ISSUE TITLE
Duplicate module declaration if extension includes a module used by Chassis

### ISSUE THREAD

**Issue by nickperkins** [Chassis/Chassis#137]
Chassis extensions are imported at the beginning of the Chassis deployment.pp. If an extension uses a module which is declared later within deployment.pp, this will cause a Duplicate module declaration error. 

Example: I'm writing an extension to install foundation command line tools. This requires nodejs which includes the apt module, as does Chassis. The following error is observed when trying to provision:

`Error: Duplicate declaration: Class[Apt] is already declared; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:21 on node vagrant.local`

An extension could check to see if a module has been defined before including it, however as the extensions are imported before the module declarations I believe this would not work.

_sidenode: I'm pretty fresh with puppet, so if my understanding is incorrect I apologise._

**Comment by BronsonQuick** [comment]
Hey @nickperkins,

Any chance you could give me access to the extension you're creating so I can replicate your issue and offer a fix? I *think* it'll just be a simple change in your extension to fix this.

**Comment by nickperkins** [comment]
Hey @BronsonQuick 

nickperkins/chassis-foundation@ff5a6325dd77221abfce72291b3e805cc5d63c4e

Hopefully it makes sense and isn't totally wrong :)

**Comment by BronsonQuick** [comment]
Hey @nickperkins, I didn't hear back from you about https://github.com/nickperkins/chassis-foundation/commit/ff5a6325dd77221abfce72291b3e805cc5d63c4e#commitcomment-11555666 so I'm closing this now as I'm cleaning the issues 👍
