### ISSUE TITLE
XDebug installation via apt-get fails

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Chassis#138]
`sudo apt-get install php5-xdebug` does not appear to work currently. 

![screen shot 2015-06-08 at 12 32 52 pm](https://cloud.githubusercontent.com/assets/676582/8028850/3449d4ec-0df4-11e5-9ddb-b6677e86d604.png)

I gather that the issue is that the php5-xdebug package requires PHP 5.6 (http://packages.ubuntu.com/vivid/phpapi-20131226). Is there a known workaround for this?

**Comment by BronsonQuick** [comment]
Hey @ericnicolaas, sorry for the delay in getting back to you. You're spot on about `php5-xdebug` needing 5.6 :smiley:  You can bump alter the php version to 5.6 (even though the docs don't mention that yet #mybad) http://docs.chassis.io/en/latest/config/#php-version then run `vagrant provision` to switch to 5.6 then you can run `sudo apt-get install php5-xdebug` inside vagrant.

![screen shot 2015-06-09 at 8 26 39 pm](https://cloud.githubusercontent.com/assets/1377956/8055869/34c1016e-0ee6-11e5-9495-9201e8e54aa9.png)

![screen shot 2015-06-09 at 8 26 50 pm](https://cloud.githubusercontent.com/assets/1377956/8055870/45653814-0ee6-11e5-8901-24ae34403f09.png)

Writing an actual XDebug extension (https://github.com/Chassis/Chassis/issues/53) for Chassis got tricky when we added php version switching.

Hopefully the php version upgrade helps and you get Xdebug working. If so, feel free to close this issue :+1:

**Comment by ericnicolaas** [comment]
Yep, looks like that does the trick. Thanks @BronsonQuick!
