### ISSUE TITLE
Manage memory allocation in YAML config

### ISSUE THREAD

**Issue by cconover** [Chassis/Chassis#141]
It would be great if the amount of memory used by the Vagrant could be managed in the YAML configuration file.

**Comment by michaelbeil** [comment]
I would submit a PR if you have some custom code for this, otherwise resorting to the WordPress memory allocation constant in the `local-config.php` file works fine: https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP.
