### ISSUE TITLE
`vagrant up` fails when setting hostname

### ISSUE THREAD

**Issue by lachenmayer** [Chassis/Chassis#142]
From a fresh recursive git clone, I get the following output when I run `vagrant up`.

```
...snip...

==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostnamectl set-hostname 'vagrant'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 2: hostnamectl: command not found
```

Full output: https://gist.github.com/615ae8726c3f7c663545

Vagrant 1.7.3
VirtualBox 4.3.30
OS X 10.9.5

Cheers!

**Comment by BronsonQuick** [comment]
Hey @lachenmayer,

I've just looked into this and I can replicate it with Vagrant 1.7.3. This a known issue in Vagrant and will be fixed in `1.7.4` so the fix for now is to downgrade to `1.7.2` and upgrade when `1.7.4` comes out.

**Comment by BronsonQuick** [comment]
@lachenmayer Vagrant `1.7.4` is out now and I can confirm that Chassis is working as expected :+1:

**Comment by lachenmayer** [comment]
Awesome, cheers! :+1:
