### ISSUE TITLE
How to install PHP packages? 

### ISSUE THREAD

**Issue by dominicwhittle** [Chassis/Chassis#144]
I'm working on client site that uses an algorithm dependant on function `stats_cdf_normal()`, which is part of [PEAR PECL](https://pecl.php.net/package/stats) `stats` and not part of the included PHP. 

Do you have instructions for including php packages in vagrant/puppet? Should this be added using the chassis extensions?

**Comment by BronsonQuick** [comment]
Hey @dominicwhittle! I have no idea why I didn't respond when you posted this but yeah this would be added by creating a Chassis extension that uses puppet to provision it. Have a look at some of the extensions we've created for Chassis so you can get an idea of the folder structure and file naming patterns: https://github.com/Chassis
