### ISSUE TITLE
Where is the directory?

### ISSUE THREAD

**Issue by fbm-static** [Chassis/Chassis#147]
When I `vagrant ssh` into the directory, where do I `cd` to make use of wp-cli? I can't find it in the documentation.

**Comment by Japh** [comment]
Check in `/vagrant/`

**Comment by Japh** [comment]
For future reference, you can check mapped directories in `Vagrantfile` to determine this kind of thing :smile:

**Comment by fbm-static** [comment]
thanks mate!
