### ISSUE TITLE
Weird shell behaviour when provisioning

### ISSUE THREAD

**Issue by derwentx** [Chassis/Chassis#151]
Hey all,
Thanks so much for creating this great bit of software! I'm loving it.
So I'm new to vagrant and my problem may just be because I'm doing something weird here but I'm using chassis and extending it with a line in the vagrant file to provision my test site with a bunch of `wp-cli`  calls from a shell script called `provisioner.sh` using this bit of code just before the # success? line in the Vagrantfile

``` bash
    config.vm.provision "shell", path: "provisioner.sh"
```

Then the provisioner has a bunch of calls to `sudo -u vagrant wp ...`

I thought i would make things a bit more readable and use `alias wpv="sudo -u vagrant wp"` however I noticed that the shell seems to ignore these aliases, even though if i run the exact same shell script directly on the server it works fine. 

Any ideas?

**Comment by BronsonQuick** [comment]
Hey @derwentx,

Any chance you could push your code to a Github repo so we can clone it to try and debug it for you? Thanks!

**Comment by derwentx** [comment]
Hi Bronson,
I'm working on my code as a fork of chassis here: https://github.com/derwentx/Chassis-TechnoTan
I'm provisioning it with provisioner.sh and I've commented out the line that does the aliasing on line 48
optimally I would like to call `wpv` instead of `sudo -u vagrant wp` in this script.
Thanks!

**Comment by BronsonQuick** [comment]
Hey @derwentx I'm doing some issue triage/gardening at the moment. I'd suggest making a [Chassis extension](http://docs.chassis.io/en/latest/extend/#creating-your-own) that installs https://github.com/danielbachhuber/dictator and then you can set some of those settings with that instead.

**Comment by derwentx** [comment]
Hey @BronsonQuick , thanks for following up. I ended up abandoning my attempt to get this working and it's been a year since I worked on it so I wouldn't remember what to do to reproduce the problem. If I recall correctly it ended up being a problem with my configuration or the way that I was using Bash, so feel free to close this issue.
Thanks!
