### ISSUE TITLE
Connecting to Sequel Pro with multiple Chassis instances

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Chassis#152]
I am running a few different Chassis instances on my computer. Mostly things are fine except for the fact that I am not able to connect to Sequel Pro. I have tried the variations at https://cloud.githubusercontent.com/assets/21655/4692717/f3d93fe6-5774-11e4-85aa-797b443d431c.png and https://github.com/Chassis/Chassis/wiki/Connecting-to-MySQL. No luck. 

This is the error I am getting: 

<img width="590" alt="screen shot 2015-10-12 at 2 57 04 pm" src="https://cloud.githubusercontent.com/assets/676582/10421926/8ee3e752-70f1-11e5-8f9a-5fd03f168304.png">

I got the impression from a previous issue here that this may be a specific issue with running multiple Chassis sites on the same machine. Is that correct? Any way around this, other than using PHPMyAdmin?

Cheers, 
Eric

**Comment by BronsonQuick** [comment]
Hey @ericnicolaas, sorry for the delay in getting back to you. I hadn't actually thought about this as I hadn't hit this issue before!

If you're running multiple Chassis instances at once then you should see a port collision that gets fixed.

<img width="754" alt="screen shot 2015-10-12 at 9 25 39 pm" src="https://cloud.githubusercontent.com/assets/1377956/10426937/54dbead2-7128-11e5-995d-ac7a5aa4ee6e.png">

You should be able to just change the SSH Port from `2222` to the new port in my screenshot it's `2201` and you'll connect to the correct database in Sequel Pro. All Chassis instances will have a different port number.

I'll try and remember to update the docs for this tomorrow for everyone :smile:

**Comment by ericnicolaas** [comment]
Awesome, thanks @BronsonQuick. Helpful as always :)
