### ISSUE TITLE
VIP-Quickstart

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#183]
The Challenge if you choose to accept it Mr. @BronsonQuick is to get a VIP-Quickstart extension for Chassis.

**Comment by rmccue** [comment]
@stuartshields Were you thinking VIP Classic or VIP Go here? :)

**Comment by stuartshields** [comment]
@rmccue I was thinking VIP Classic for the time being, but it wouldn't hurt to have VIP GO support either.

**Comment by johnbillion** [comment]
Note to readers: Stuart is working on this here: https://github.com/stuartshields/chassis-vip

**Comment by rmccue** [comment]
Quickstart is being deprecated: https://lobby.vip.wordpress.com/2017/03/13/goodnight-sweet-quickstart/

(For anyone looking for the above link, it has been moved to https://github.com/stuartshields/chassis-vip-classic)

I'd like to add some docs to the official site about using VIP here, both Classic and Go variants.

**Comment by stuartshields** [comment]
So I've depreciated the old one - https://github.com/stuartshields/chassis-vip-depreciated

Currently working on - https://github.com/stuartshields/chassis-vip-classic

**Comment by rmccue** [comment]
@stuartshields Do you want to move these repos to the Chassis org? (Up to you.)

In any case, we should add them to the documentation as our officially-recommended solution for VIP.

**Comment by stuartshields** [comment]
@rmccue Yeah I do, I just haven't gotten around to it. Let me know the best approach.

**Comment by BronsonQuick** [comment]
I'm closing this as we now have https://github.com/Chassis/vip-classic Props @stuartshields
