### ISSUE TITLE
Unable to install plugins from admin

### ISSUE THREAD

**Issue by cameronjonesweb** [Chassis/Chassis#187]
From [WP Australia Slack](https://wpaustralia.slack.com/archives/chassis/p1465024263000002)

After setting up a new Chassis instance I attempted to install some plugins from the WordPress admin interface. After a significant delay (most likely due to the wild weather affecting internet connection) the plugin installation fails.

![image](https://cloud.githubusercontent.com/assets/12673074/15798904/83960d0c-2a8d-11e6-82dc-9d16f0604dd1.png)

If I create a `plugins` directory in `content` then installation has no problems.

Language files don't seem to have this issue.

I believe this is a Windows file permissions issue rather than a Chassis issue. Perhaps an adequate solution would be to just provide the `plugins` directory inside of the content directory when provisioning.

Running on a Windows 10 machine, PHP 5.6. Only host and admin details changed from defaults.

**Comment by cameronjonesweb** [comment]
I just noticed the docs say to create said plugins directory...

**Comment by BronsonQuick** [comment]
@cameronjonesweb Yeah that's correct! You have to create it yourself. We could automatically create it with Puppet however we've designed Chassis so that people can use their own folder structure if they like so we've left it up to them to set it up to their liking so it's intended behaviour.
