### ISSUE TITLE
HTTPS support in Chassis core

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#198]
There's an [OpenSSL extension for Chassis](https://github.com/javorszky/chassis-openssl) which enables support for HTTPS. This should be merged into Chassis core and become a configuration flag.

By default Chassis should provide support HTTPS, and using the `https` scheme by default for its hosts should become a flag.

The extension does the following:
- Installs OpenSSL
- Generates a security certificate for the site's domain
- Adds relevant lines for certs to the Nginx config file

The extension does not:
- Set the site's scheme to `https` (in wp-config.php)
- Install the cert as a trusted cert in the host OS
- Generate a cert with wildcard subdomain support
- Generate a cert for all available hosts in the `hosts` config.

/cc @javorszky

**Comment by BronsonQuick** [comment]
There's a PR in progress for this over here: https://github.com/Chassis/Chassis/pull/207

**Comment by rmccue** [comment]
So, why should this be in Chassis core rather than in an extension? :)

**Comment by BronsonQuick** [comment]
To encourage people to always use https. I'm with @johnbillion on this one being in core.

**Comment by rmccue** [comment]
I'm concerned that this is a fair bit of extra processing for what is essentially an edge case. We're not realistically improving security by offering HTTPS on a localhost machine, and without some of the more automated things (adding to the host's cert store, etc), I don't think it provides a great user experience.

Unless core is uniquely positioned to offer the functionality better than an extension could, I'm 👎 on including this.

**Comment by rmccue** [comment]
I'd like to also see benchmarks on how this affects installation time. If it turns out it has a minimal impact on boot time, then I'd probably be OK with adding it.

**Comment by BronsonQuick** [comment]
>We're not realistically improving security by offering HTTPS on a localhost machine

I'm thinking more about the longer goal of Chassis provisioning production servers as well where https is important.

I'll do try and do some benchmarks in my holidays for you. I am yet to test the progress Johnny B has made with this yet.

**Comment by rmccue** [comment]
> I'm thinking more about the longer goal of Chassis provisioning production servers as well where https is important.

Provisioning a self-signed certificate is pretty useless for production, so we would need further support for passing in configuration for the certificate and key file anyway.

**Comment by johnbillion** [comment]
The reason this should be in Chassis core is that, as a trend, more and more sites are being built on HTTPS, so the likelihood that developers need an HTTPS _development environment_ is increasing. Chassis should make it easy to provision an HTTPS environment for development.

It's not about increasing security locally or procuring valid certs for live environments (although the latter could be something to look at at a later date).

**Comment by javorszky** [comment]
An example of that is to make the local development site work with certain payment gateways, if it's an ecommerce site in dev. Some payment gateways will just flat out refuse to talk to the site if it's on http, even on sandbox.

**Comment by BronsonQuick** [comment]
I should've closed this issue as we have [docs](http://docs.chassis.io/en/latest/guides/#setting-up-ssl) and the [OpenSSL extension](https://github.com/Chassis/chassis_openssl) that we maintain.
