### ISSUE TITLE
Add and configure OpenSSL

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#20]
Looks like https://github.com/camptocamp/puppet-openssl might do the trick although you might know a better way @rmccue

**Comment by javorszky** [comment]
Hey, so I created this: https://github.com/javorszky/chassis-openssl

It works, but is brittle. If you have some time, can you look at that / help me what I can improve and how? :)

**Comment by javorszky** [comment]
So I was thinking about this and have been trying to get it working. Findings: 

* simply overwriting the nginx file in `sites-available` is not an option, as puppet will complain that the same file is declared someplace else
* having a nearly identical nginx file in the same folder for what is effectively 3 lines of change for the entire functionality seems a bit of an overkill, plus the extension would need to closely monitor chassis core and adjust its own template files as core's change
* instead, it might be an option to add this into core, and put this behind a `yaml` flag: `-ssl: on`, and much like the PHP versions, register it, but don't pull it down, unless the user has specified it
* that way there could be an alternate template, and provisioning could choose which one to use whether the flag is set in the yaml file

Thoughts? :)

**Comment by rmccue** [comment]
@javorszky I'd like to keep it out of Chassis by default, since it doesn't fit the 80/20 rule, plus I think we're better off making a more generic system instead.

What if instead we added `include /etc/nginx/sites-enabled/{$fqdn}.d/*` into there? The SSL extension could then just have `{$fqdn}.d/ssl` with:
```nginx
listen 443 ssl;

ssl_certificate    /etc/ssl/certs/<%= @fqdn %>.crt;
ssl_certificate_key    /etc/ssl/certs/<%= @fqdn %>.key;
```

I'm investigating if this would work at the moment. :)

**Comment by rmccue** [comment]
I just tried this locally, and it seems like you can do this:

```nginx
listen 80;
listen 8080;
listen 443 ssl;

ssl_certificate    test.crt;
ssl_certificate_key    test.key;
```

...all in the same server block, and it works fine. The SSL configuration only applies to the listening ports where `ssl` is specified.

@javorszky Would this work for you?

**Comment by javorszky** [comment]
Hey @rmccue!

Awesome, thank you! TIL about nginx's include.

The above description didn't work for me though. It gets stuck while trying to include `/etc/nginx/sites-enabled/*`, and sadly `{$fqdn}.d/` is also being picked up, but is a directory, and nginx doesn't seem to like that.

Working on it though...

**Comment by BronsonQuick** [comment]
Props to you @javorszky: https://github.com/javorszky/chassis-openssl to fix this :+1:

**Comment by javorszky** [comment]
My pleasure :)
