### ISSUE TITLE
Chassis/Vagrant & PhpStorm Remote interperters

### ISSUE THREAD

**Issue by orionrush** [Chassis/Chassis#201]
I seem to be having a series of issues with PhpStorm and setting up Chassis as a vagrant box. 
([relivant ticket here on intellij support](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207713925-Error-can-t-run-Vagrant-executable-?page=1)).

The Chassis box itself is fine, and I have all the typical functionality via terminal. Fundamentally I'd like to use Chassis' php as a remote interpreter for PhpStorm, so if configuring PhpStorm with vagrant the documented way way fails, I might be able to simply point the [interpreter](https://www.jetbrains.com/help/phpstorm/2016.1/configuring-remote-php-interpreters.html) to the remote box via  an ssh connection. 

So two questions:

1. Has anyone had experience working with any of the intillij products that have Vagrant integration using Chassis? 
2. SSH: Are there any specifics I should know, or ssh settings I should use? Or should I, for example set them manually by adding the likes of `config.ssh.password = "password"` to the `Vagrentfile`?

**Some relevant docs:**
- [Vagrant: ssh-config name|id] (https://www.vagrantup.com/docs/cli/ssh_config.html)
- [Vagrant: ssh_settings](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html)
- [PhpStorm 10.0 Vagrant ](https://www.jetbrains.com/help/phpstorm/10.0/vagrant.html)
- [PhpStorm: Working with reproducible development environments using Vagrant ](https://www.jetbrains.com/help/phpstorm/2016.1/working-with-reproducible-development-environments-using-vagrant.html#d385367e186)
- [ PhpStorm: Debugging vvv vagrant setup with phpstorm](https://blog.jetbrains.com/phpstorm/2016/06/debugging-vvv-vagrant-setup-with-phpstorm/)
- [PhpStorm: Configuring remote php interpreters](https://www.jetbrains.com/help/phpstorm/2016.1/configuring-remote-php-interpreters.html)

**Comment by BronsonQuick** [comment]
Hey @orionrush!

I've got PHPStorm and Vagrant working fine at the moment: 
![chassis-vagrant-phpstorm](https://cloud.githubusercontent.com/assets/1377956/16904531/94f2c124-4cdb-11e6-83a0-7dcb66a7d373.png)
Is that what you're trying to achieve or are you after something else instead?

In terms of debugging with Chassis. I have written a Chassis Extension for XDebug + PHPStorm: https://github.com/Chassis/Xdebug I can add some more docs on setting the PHPStorm Xdebug configs correctly if that helps?

If I've misunderstood what you're after then feel free to let me know a bit more detail and I'll do my best to help you! Thanks 😄

**Comment by BronsonQuick** [comment]
Also, I'll try and find some time to look over https://www.jetbrains.com/help/phpstorm/2016.1/configuring-remote-php-interpreters.html and how it can work with Chassis as well towards the end of the week!

**Comment by orionrush** [comment]
@BronsonQuick 
Thanks for confirming that PhpStorm can use Chassis as a Vagrant Box. This also confirms that the issue I'm seeing have to do with my setup. The fact I'm on osx 10.8.5, is probably a big part of it. 

So rather than try to debug PhpStorm and an old OS, I'll work the problem by using ssh. To do this I need I need to access the machine *not* through `vagrant ssh` but by modifying Chassis' ssh settings to allow a password connection. I'll open a separate ticket related to the ssh issues that I've encountered.

**Comment by orionrush** [comment]
To complete this, I'm posting how I ultimately got things going.

To recap, in my case as PhpStorm's Vagrant integration is broken due to issues related ( I believe ) to my older OS. So I'm not able to use any of the Vagrant options as expected. However, as the box itself works just fine I can still it as a 'Remote PHP interpreter' using the SSH option. 

Setting up Vagrant/Chassis to use a password for SSH proved to be quite a bit more complicated than I was expecting. It was far simpler to use the `private_key` provided.

First, after making sure the box is running, run `vagrant ssh-config` and you should get results similar to these:

     Host default
       HostName 127.0.0.1
       User vagrant
       Port 2222
       UserKnownHostsFile /dev/null
       StrictHostKeyChecking no
       PasswordAuthentication no
       IdentityFile /Users/anachronistic/Documents/Web/Vagrent/orionrush.com/.vagrant/machines/default/virtualbox/private_key
       IdentitiesOnly yes
       LogLevel FATAL
       ForwardAgent yes

Back in PhpStorm's 'Remote PHP interpreter' settings,  use values for user, host, and port. For Auth Type, choose the 'Key pair', using the path found under IdentityFile as the value. 

![screen shot 2016-07-18 at 11 42 47](https://cloud.githubusercontent.com/assets/788150/16912571/ce42236a-4cdc-11e6-85c7-c7f018b8b925.png)
