### ISSUE TITLE
Change config.yaml to chassis.yaml

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#202]
Since some devs might use Chassis for local environments, and some not, while they both share the same content repo, same goes for deployment, wouldn't it make sense if the config file is named after chassis rather than it holding a generic `config` name ?

**Comment by BronsonQuick** [comment]
@shadyvb I guess that's a possibility but my only concern is making this backwards compatible for people with existing setups. I can handle that inside the Ruby files we have. I'll wait to see what @rmccue thinks before I tackle that though.

**Comment by BronsonQuick** [comment]
I think I'm going to close this one for now as I think you might've been thinking about this with the `wp-cli` stuff. I'm happy to open it again later if we definitely hit is as a problem.

**Comment by shadyvb** [comment]
@BronsonQuick Not really a problem, it is just that having `content.yml` file within `wp-content` folder ( without prior knowledge of Chassis ) wouldn't be so helpful.

Was thinking of cases where we'd make a site repo chassis-compatible, a more descriptive file name would've worked best in that case. So not a problem per-se, just an enhancement.
