### ISSUE TITLE
Allow setting default theme/plugins list from config file

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#203]
It'd be nice if we can setup the default theme, and the active/installed plugin list through the config.yaml file, would make it easier for people to have a consistent environment across teams.

**Comment by BronsonQuick** [comment]
I'm thinking a few extra parameters for `themes:` and `plugins:` would be great for this then we'll use `puppet-wp` to install and activate them.

**Comment by cameronjonesweb** [comment]
Would love to see this

**Comment by tareiking** [comment]
:+1: from me.
