### ISSUE TITLE
Link wp-cli.yml to home folder

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#204]
This will allow direct usage of wp-cli using `vagrant ssh -c 'wp foo bar'` commands, without the need to SSH then issue a single command.

**Comment by shadyvb** [comment]
FTR, `vagrant ssh -c 'wp --path=/vagrant/wp foo bar` works, would just be easier if we can omit the path thing, this is a WordPress-only box after all.

**Comment by BronsonQuick** [comment]
@shadyvb Good thinking on this! I just read about some other upstream updates that look great too: http://wp-cli.org/blog/restful-wp-cli-update-4.html
