### ISSUE TITLE
Changing URL needs couple of provisions + restarts to work

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#206]
Steps:
1. Provision using Domain A
2. Change Domain to B
3. Provision

Expected result: New config is picked up, and domain is changed and accessible locally

Actual result: First provision doesn't pick up the changes, so I needed to do the following to get Domain B to work:
1. Restart
2. Provision
3. Restart ( might not really be needed, not quite sure )

**Comment by johnbillion** [comment]
This also occurs the first time you provision a brand new box using a project that uses a non-standard URL.

**Comment by johnbillion** [comment]
FYI, the error I got during provisioning was:

```
==> default: Error: Could not set 'file' on ensure: No such file or directory - /etc/nginx/sites-available/wunderman.local20160718-2353-1hf0ak8.lock at 22:/vagrant/puppet/modules/chassis/manifests/site.pp
==> default: Error: Could not set 'file' on ensure: No such file or directory - /etc/nginx/sites-available/wunderman.local20160718-2353-1hf0ak8.lock at 22:/vagrant/puppet/modules/chassis/manifests/site.pp
==> default: Wrapped exception:
==> default: No such file or directory - /etc/nginx/sites-available/wunderman.local20160718-2353-1hf0ak8.lock
==> default: Error: /Stage[main]/Main/Chassis::Wp[wunderman.local]/Chassis::Site[wunderman.local]/File[/etc/nginx/sites-available/wunderman.local]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /etc/nginx/sites-available/wunderman.local20160718-2353-1hf0ak8.lock at 22:/vagrant/puppet/modules/chassis/manifests/site.pp
```

**Comment by shadyvb** [comment]
I've seen that as well. Thought it was a result of trying to provision a second box with the same domain, but the error might actually not be related to that :/

**Comment by orionrush** [comment]
- I've seen this as well

**Comment by paulgibbs** [comment]
I can confirm that:

> This also occurs the first time you provision a brand new box using a project that uses a non-standard domain.

happens. If I set hosts to vagrant.local and custom.local, the aliasing works.

**Comment by BronsonQuick** [comment]
I had trouble reproducing this error yesterday and I've provisioned 100's on Chassis boxes and never seen this. Could I please get a copy of your yaml files as well as version numbers of Vagrant and Virtual Box. Thanks!

**Comment by shadyvb** [comment]
VirtualBox 5.0.2
Vagrant 1.8.1

And the yaml only contained the custom domain.

**Comment by BronsonQuick** [comment]
@shadyvb Which yaml file Sir? You can have 4 of them! https://github.com/Chassis/Chassis/blob/master/config.yaml#L6

**Comment by shadyvb** [comment]
@BronsonQuick I edited the `config.yaml` within Chassis folder itself to test,  and `content/config.yaml`, and later `../content/config.yaml` with custom content dir.

**Comment by BronsonQuick** [comment]
@shadyvb Awesome thanks. That'll help me debug it further. One more question before I get to testing and hopefully replicating this and fixing it, with those yamls, did you delete anything out of the main existing config? Ideally if you could shoot through gists of all your yaml configs that would help even further! Thanks!

**Comment by BronsonQuick** [comment]
Alrighty. I've just received another report of this. It sounds like I should be able to replicate it with the following steps:

1. Do a fresh clone of Chassis.
2. `vagrant up`
3. Copy `config.yaml` to `content/config.local.yaml` and change the hostname.
4. `vagrant provision`

The new url shouldn't be resolved but the previous `http://vagrant.local`will still exist and resolve.

**Comment by BronsonQuick** [comment]
I was just debugging a different issue with a colleague and he had issues with Chassis because he had the `vagrant-vbguest` plugin installed. When we removed that plugin Chassis initial provisions and subsequent provisions worked fine. Can you all have a look and see if you have that plugin or other vagrant plugins installed that might be modifying things? Taa muchly!

**Comment by shadyvb** [comment]
Hint: the plugin functionality can probably be disabled by adding `config.vbguest.auto_update = true`, will test and let you know.

**Comment by shadyvb** [comment]
For me, I had a few mirrors fail some required dependencies, with 404s on `precise-backport` and `precise-security` URLs. And that prevented the final step of WordPress actual installation, which only happened if I provisioned again, not sure why it failed the first time but not the second though.

Changing `apt_mirror` to `No` fixed this for me. So this explains that some has it working and some don't, because we get different mirrors. Some might even have had it intermittently because you can get different mirrors depending on -probably- ping status.

This fixes the issue for me, whether I have the `vbguest` plugin installed or not.

**Comment by BronsonQuick** [comment]
@shadyvb Thanks for the tip about `config.vbguest.auto_update = false`! I'll give that a whirl tomorrow and update the docs.

Ahh right. Good work hunting down the mirror issue! I've had that happen once before when a mirror went stale but it was a one off. I'll update the docs for that too. Thanks a bunch! 😍

**Comment by paulgibbs** [comment]
Can't we just update the defaults so stuff is sane and actually works, rather than take the "document all the sort-of bugs in a FAQ" solution?

**Comment by BronsonQuick** [comment]
@paulgibbs If the mirror fix fixes your issue too then I'm happy to update the mirrors to No. It will mean that provisioning will be slower for everyone though. I'll see what @rmccue things about this change as well.

**Comment by shadyvb** [comment]
@BronsonQuick I don't think `vbguest` affects the process, at least not in my trials.

And yes the mirror update will make it slower, but slower is better than broken, I guess.

**Comment by BronsonQuick** [comment]
I've just tried digging into this a little more. There's a chance that http://unix.stackexchange.com/a/304541 might fix this issue.

**Comment by indietravel** [comment]
Maybe related:

1. Start new project with default settings: provisions fine.
2. `cp config.yaml content/config.local.yaml` - provisions fine.
3. `nano content/config.local.yaml` and update `hosts` to 
```
hosts:
    - podcast.local
    - vagrant.local
```
4. `$ vagrant provision` has some big red scary warnings...
```
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> default: Running provisioner: shell...
    default: Running: /var/folders/jd/d448dcd560l4rwy9b_b4p7yr0000gp/T/vagrant-shell20170711-4036-1o35b15.sh
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Notice: Compiled catalog for vagrant.local in environment production in 4.81 seconds
==> default: Notice: /Stage[main]/Main/Chassis::Wp[podcast.local]/Chassis::Site[podcast.local]/File[/etc/nginx/sites-available/podcast.local]/ensure: defined content as '{md5}12abeda6543df157ae80dfd598d81d71'
==> default: Notice: /Stage[main]/Main/Chassis::Wp[podcast.local]/Chassis::Site[podcast.local]/File[/etc/nginx/sites-enabled/podcast.local]/ensure: created
==> default: Error: /Stage[main]/Chassis/Service[nginx]: Failed to call refresh: Could not restart Service[nginx]: Execution of '/etc/init.d/nginx reload' returned 1: Reloading nginx configuration (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
==> default:  failed!
==> default: Error: /Stage[main]/Chassis/Service[nginx]: Could not restart Service[nginx]: Execution of '/etc/init.d/nginx reload' returned 1: Reloading nginx configuration (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
==> default:  failed!
==> default: Notice: Finished catalog run in 1.86 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
5. `vagrant reload` pops up some errors:
```
...
==> default: Mounting shared folders...
    default: /vagrant => /Users/xxxx/s/podcast
    default: /var/log/php => /Users/xxxx/s/podcast/logs/php
==> default: Detected mount owner ID within mount options. (uid: 1000 guestpath: /var/log/php)
==> default: Detected mount group ID within mount options. (gid: 1000 guestpath: /var/log/php)
    default: /var/log/nginx => /Users/xxxx/s/podcast/logs/nginx
==> default: Detected mount owner ID within mount options. (uid: 1000 guestpath: /var/log/nginx)
==> default: Detected mount group ID within mount options. (gid: 1000 guestpath: /var/log/nginx)
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => /Users/xxxx/s/podcast/puppet/manifests
```
6. `vagrant provision` returns:
```
$ vagrant provision
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> default: Running provisioner: shell...
    default: Running: /var/folders/jd/d448dcd560l4rwy9b_b4p7yr0000gp/T/vagrant-shell20170711-4239-19eaibf.sh
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Notice: Compiled catalog for podcast.local in environment production in 8.87 seconds
==> default: Notice: /Stage[main]/Main/Chassis::Wp[podcast.local]/Chassis::Site[podcast.local]/File[/etc/nginx/sites-available/podcast.local]/content: content changed '{md5}12abeda6543df157ae80dfd598d81d71' to '{md5}bde042b6c606611ec604edb16326a92a'
==> default: Notice: /Stage[main]/Chassis/Service[nginx]: Triggered 'refresh' from 1 events
==> default: Notice: Finished catalog run in 4.30 seconds
==> default: Running provisioner: shell...
    default: Running: /var/folders/jd/d448dcd560l4rwy9b_b4p7yr0000gp/T/vagrant-shell20170711-4239-1nk7vb7.sh
```
Looks like podcast.local should be working...
7. `curl` shows it's not, although vagrant.local is:
```
$ curl -IkL http://podcast.local
curl: (6) Could not resolve host: podcast.local
$ curl -IkL http://vagrant.local
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Tue, 11 Jul 2017 15:53:35 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/7.0.21-1~ubuntu16.04.1+deb.sury.org+1
Link: <http://vagrant.local/?rest_route=/>; rel="https://api.w.org/"
```

**Comment by indietravel** [comment]
Had some more time to play with this config this weekend. With the above settings, I could get things running properly using the 'reload / provision / reload' workflow recommended by OP. Seems a bit torturous though. This is out of my wheelhouse to patch, but happy to test patches.

**Comment by indietravel** [comment]
Touch more feedback here: with the 'reload / provision / reload' workflow; working perfectly in Chrome; Safari "can't connect to server "foo.local"."
