### ISSUE TITLE
wp-cli warnings on provision

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#212]
> ==> default: Error: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/home/vagrant/.wp-cli/config.yml]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /home/vagrant/.wp-cli/config.yml20160725-2372-10j5dhn.lock at 64:/vagrant/puppet/modules/chassis/manifests/wp.pp

Doesn't actually seem to affect wp-cli or provisioning but this does cause the script to return with a non-zero status, causing the fail text. When I ssh in after this, ~/.wp-cli/ doesn't exist.

**Comment by BronsonQuick** [comment]
@paulgibbs Thanks for the bug report. Fixed 👍
