### ISSUE TITLE
VM using 127.0.0.1 on provision

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#213]
When I provision a new Chassis, it assigns itself to 127.0.0.1... not ideal because :80 on that could be used for some other web server (in my case, the default Httpd that came with Mac OS).

**Comment by BronsonQuick** [comment]
I was thinking about this over lunch. Are you sure isn't not just the ssh address for the VM that is `127.0.0.1` can you please ping `vagrant.local` and let me know what IP address that returns? Thanks!

**Comment by rmccue** [comment]
I don't think this is actually possible. The subnet for assignments is 192.168.0.1/16 (mask is 255.255.0.0), and 127.0.0.1 isn't a private IP. Either something is seriously wrong with the DHCP client, or potentially you're checking the wrong IP?

**Comment by miklb** [comment]
I'm not sure if this is related or not. I had been using Chassis without problem, but today trying to spin up a new instance (from a git checkout) I'm experiencing nothing being written to the hosts file.

When I ping my new instance after `vagrant up` I'm getting `127.0.53.53` 

but nothing loads in the browser. On  OS 10.11.6 fwiw. Would be glad to provide more details if this is related, or point me where to better ask.

**Comment by BronsonQuick** [comment]
@miklb We don't use the hosts file for Chassis so that's not a problem.

The `127.0.53.53` is another strange IP address. Are you using any kinds of proxy, firewall or antivirus software by any chance?

**Comment by miklb** [comment]
@BronsonQuick no proxy/firewall/antivirus.

Strangely, if I remove my custom `client.dev` from the `config.yaml` file and use `vagrant.local` when I tried to ping I got `Unknown host`

**Comment by BronsonQuick** [comment]
@miklb Ahh okay then. So Chassis is designed to only work with `.local` domains. You can use `whatever.local` and it'll be fine. `.dev` will never work with Chassis. There's a note about that in the docs: http://docs.chassis.io/en/latest/config/#custom-host-names

**Comment by BronsonQuick** [comment]
@miklb Also, after you altered the domain name back to `vagrant.local` did you run `vagrant provision` again as you'll need to do that.

**Comment by BronsonQuick** [comment]
@miklb Also please let me know if I should update the docs to make that a little clearer. Because I know all the ins and outs of Chassis I'm often unsure if our wording in the docs is clear enough for some features. Thanks! 😄

**Comment by miklb** [comment]
OK, weird re-provisioning the box worked this time. I did notice some issues previously in provisioning with mirrors and `apt`, so maybe something didn't get purged properly when spinning vagrant back up. I'll keep an eye out.

> Also please let me know if I should update the docs to make that a little clearer.

I didn't catch it in the docs, but this was the 1st time I tried customizing. Previously I was just using out of the box. 

Thanks for this, I had looked at a lot of options for a lightweight dev environment, and this has by far been the best solution.

**Comment by BronsonQuick** [comment]
@miklb Awesome. Glad that reprovision sorted it out! Basically anytime you change an option in the yaml file you need to run `vagrant provision` for the puppet to look at the changes and change the state of your dev environment.

> Thanks for this, I had looked at a lot of options for a lightweight dev environment, and this has by far been the best solution.

Awesome! Glad to hear that Chassis is suiting your dev needs! 👍
