### ISSUE TITLE
Run custom commands before package installations ?

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#221]
If I need to add an apt proxy for example, what would be the best way to execute arbitrary commands before the package installation process ?

**Comment by rmccue** [comment]
Puppet includes a [concept called "stages"](https://docs.puppet.com/puppet/latest/reference/lang_run_stages.html). Everything in Chassis runs in the main stage, so you can do this to run things before or after:

```puppet
stage { 'first':
    before => Stage['main'],
}
stage { 'last':
    after => Stage['main'],
}
exec { '/vagrant/before.sh':
    stage => first
}
exec { '/vagrant/after.sh':
    stage => last
}
```
