### ISSUE TITLE
Vagrant 1.8.5's bug prevent chassis from running on Windows - 'change_host_name' not supported

### ISSUE THREAD

**Issue by JonathanScher** [Chassis/Chassis#233]
Should we document that for Windows users?

Cloning the repository and running vagrant up on Windows will give you an error:
```
Vagrant attempted to execute the capability 'change_host_name'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```
To go around this bug, the user must go through a manual patching:
Replace "C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.5\plugins\guests\ubuntu\guest.rb" with the file found there: https://raw.githubusercontent.com/carlosefr/vagrant/1c631c18d1a654405f6954459a42ac19a1a2f096/plugins/guests/ubuntu/guest.rb

http://stackoverflow.com/questions/38636023/vagrant-not-supported-the-capability-change-host-name

**Comment by BronsonQuick** [comment]
@JonathanScher Thanks for the bug report. I hadn't upgraded to `1.8.5` yet so I hadn't seen this. I'll update the docs now! Thanks again!

**Comment by BronsonQuick** [comment]
Alrighty. Just dropping a note here as Vagrant 1.8.6 is out now so you should be able to upgrade and not have this issue anymore 😄
