### ISSUE TITLE
Investigate pre-compilation of Puppet catalog

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#247]
When provisioning, we get a `Notice: Compiled catalog for vagrant.local in environment production in 14.80 seconds`; if we can optimise this out, we could potentially save ~15s. However, I suspect this wouldn't work with our configuration handling.

**Comment by BronsonQuick** [comment]
I've been `vagrant up`ing a lot lately and the max I've ever seen is around 4 seconds. How often have you seen a large time like that?

**Comment by rmccue** [comment]
This has mostly been much lower for me lately (4s), and the catalog changes based on config, so we can't really optimise this much further.
