### ISSUE TITLE
Add better error reporting when yaml files have an error or incorrect syntax

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#287]
Turns out I had a bit of a PEBCAK moment and I had a yaml file that didn't have a comment commented out correctly. This resulted in this error:
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Volumes/Sites/chassis/Vagrantfile
Line number: 28
Message: NameError: uninitialized constant Psych::Error
```

By changing the Psych::Error to Psych::SyntaxError we get a more readable error:
```
ERROR: Could not load config:
    (/Volumes/Sites/chassis/config.local.yaml): mapping values are not allowed in this context at line 6 column 11
```

**Comment by rmccue** [comment]
Looks like this may have been an update in Psych.

**Comment by rmccue** [comment]
Aha, it's actually the reverse. Ruby 2.0 has [Psych::SyntaxError](https://ruby-doc.org/stdlib-2.0.0/libdoc/psych/rdoc/Psych/SyntaxError.html) < Psych::Error < RuntimeError, while 1.9 has [Psych::SyntaxError](http://ruby-doc.org/stdlib-1.9.3/libdoc/psych/rdoc/Psych/SyntaxError.html) < SyntaxError.
