### ISSUE TITLE
Box 'hashicorp/precise64' could not be found.

### ISSUE THREAD

**Issue by Japh** [Chassis/Chassis#290]
I'm running into a strange error firing up my first Chassis install on a brand new MacBook Pro running macOS 10.12.1.

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error:
```

Searching around a bit for this reveals an older issue with conflicting cURL versions between the ones shipped with Vagrant and Windows 10. So I guess it's possible this is also a cURL conflict but with macOS? Although the errors others posted seemed to not be quite the same.

It might just be something simple, but I figured worth opening the issue anyway so then someone else can find the fix in future if it occurs.

Any ideas?

**Comment by rmccue** [comment]
Could this have been a temporary network issue?

**Comment by Japh** [comment]
No, I don't think so. It's persisted every time I've tried over a couple of hours, and everything else is working fine.

**Comment by BronsonQuick** [comment]
This seems like an odd one! Does it work if you do `vagrant login`?

Could I get a few more details off you please:

1. Which version of Vagrant are you using?
2. Which version of VirtualBox are you using?
3. Do you have any Vagrant plugins installed?

Another option I'm thinking might be to try manually adding the box from another source.
e.g.
`vagrant box add precise64 http://files.vagrantup.com/precise64.box`

Ideally Chassis should 'just work' so I definitely want to get to the bottom of this as I won't want folks with new Mac's hitting this issue. Thanks for reporting it!

**Comment by Japh** [comment]
Tried `vagrant login` and still no dice.

1. Vagrant 1.8.7
2. VirtualBox 5.1.10
3. `vagrant-share` (installed by default I think) and `vagrant-hostsupdater`

I'm guessing I could _maybe_ manually add the box...

**Comment by Japh** [comment]
Running that manual add command gets me a different error:

```
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'precise64' (v0) for provider:
    box: Downloading: http://files.vagrantup.com/precise64.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

**Comment by Japh** [comment]
And yet I can `wget` the URL and it downloads fine.

**Comment by Japh** [comment]
Fixed! Deleting the embedded version of curl from Vagrant did the trick, as suggested here: https://github.com/mitchellh/vagrant/issues/5016#issuecomment-260220289
