### ISSUE TITLE
apt-get update on every provision

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#292]
Right now, the provisioning is not quite truthful when it specifies "latest", as the underlying apt cache is not being updated.

This is particularly problematic when moving from an older copy of Chassis to a newer one with the new default PHP version (#279), as the cached packages don't contain this.

It would be great if we could _also_ make apt-get update faster. I partially investigated this in #262, but we can revisit that.

**Comment by BronsonQuick** [comment]
I'm closing this out in favour of https://github.com/Chassis/Chassis/issues/582
