### ISSUE TITLE
Remove XML extension

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#296]
We've introduced Php's XML package back into core so we can delete the XML extension that I created. It hasn't been around long and only @mattheu have used it as far as I'm aware so we can delete it.

Deleting the folder that the extension was cloned into then running a `git pull` and `vagrant provision` in Chassis's root directory will install xml.

**Comment by mattheu** [comment]
👍 Updated my box today. All good.

Is it typical that users just clone the extension or would they usually add the extension to the `config.local.yaml`. It would be nice if the extension was not defined in the config file to not load it, even if the extension files were present - however it would probably cause issues for existing users.

**Comment by BronsonQuick** [comment]
I usually clone an extension if It's an extension I want to use but I other might not want to use. e.g. Fish or Xdebug. Originally we didn't have support for automatically cloning and extensions from the yaml files so we used to manually clone them.
