### ISSUE TITLE
Extensions provision fails on VMWare

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#300]
With VMWare, Chassis installs and works out of the box fine. I can switch between PHP versions, and it all works.

When I try to add any extension, however, it fails with the following output: 

> $ vagrant provision
==> default: Running provisioner: shell...
    default: Running: /var/folders/tr/1zvk31cs3_bds22b4gbwfdc40000gn/T/vagrant-shell20161213-3154-ad7yjt.sh
==> default: stdin: is not a tty
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for vagrant.local in environment production in 1.33 seconds
==> default: Notice: /Stage[main]/Tester::Config/File[/vagrant/extensions/tester/wpdevel/wp-tests-config.php]/ensure: defined content as '{md5}8f838da9b4524f8eba2cdbc50c0ea819'
==> default: Error: Operation not permitted - /vagrant/local-config-extensions.php20161213-28338-ret4ba
==> default: Error: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]/content: change from {md5}d28bac1939d50ee28f050d9ce5a20713 to {md5}d2811a6204141c81798734aca9fe234d failed: Operation not permitted - /vagrant/local-config-extensions.php20161213-28338-ret4ba
==> default: Notice: Finished catalog run in 1.24 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

After much trial and error on Slack, Ryan, Bronson, and I, discovered that if I deleted `local-config-extensions.php`  before running provision, the provision works fine and it rebuilds the deleted file.

**Comment by BronsonQuick** [comment]
Thanks for the solid bug report @paulgibbs! I'll be buying VMware either this week or next week so I can get to the bottom of this and make sure we support both!= VirtualBox and VMware!

**Comment by BronsonQuick** [comment]
@paulgibbs I'm going to close this one for now as I know this issue is fixed in https://github.com/Chassis/Chassis/pull/408 using VWWare and `vagrant plugin install vagrant-bindfs`

**Comment by BronsonQuick** [comment]
Cancel that. I didn't test that correctly!

**Comment by BronsonQuick** [comment]
Closing in favour of https://github.com/Chassis/Chassis/issues/728
