### ISSUE TITLE
error_log in PHP CLI

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#302]
In the PHP CLI .ini (on PHP 7.0), please can `error_log` be set ideally as `error_log = /var/log/php/php_errors.log` by default? Infuriating to not realise the FPM and CLI PHP configurations are not identical when you can't figure out why something isn't logged.

**Comment by paulgibbs** [comment]
Actually I can't see any PHP logs anywhere for anything. Can you verify and test that it's working?

**Comment by BronsonQuick** [comment]
@paulgibbs Ahh right. I didn't know cli and fpm had different logging as well! That's nuts. I'll resolve that.

Re the other logs I did fix those for peeps in https://github.com/Chassis/Chassis/pull/246 so you should see logs in: https://github.com/Chassis/Chassis/blob/master/config.yaml#L77 if they aren't working then I'm guessing this might be another VMWare synced folder issue which I'll get to the bottom of during my holidays for you and everyone else using VMWare!

**Comment by BronsonQuick** [comment]
@paulgibbs I just tried to replicate this issue and I couldn't. I did a fresh Chassis install with VMWare and went to http://vagrant.local/phpinfo.php and this is what I see:

![error_log](https://cloud.githubusercontent.com/assets/1377956/21582732/2060915e-d0b8-11e6-8474-18189cf97980.png)

Can you please have another check of your install and let me know if you're still having this issue so I can try and work out how to replicate it? Thanks!

**Comment by rmccue** [comment]
Can confirm that the PHP log value doesn't match in CLI and FPM:
```
vagrant@vagrant:~$ php -i | grep error_log
error_log => no value => no value
opcache.error_log => no value => no value
```

We're only provisioning `"/etc/${php_dir}/fpm/php.ini"` right now, we should provision the CLI file as well.
