### ISSUE TITLE
zip extensions missing

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#303]
Trying to install wp-cli from Composer, from dev:

` Failed to download mustache/mustache from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /etc/php/7.0/cli/php.ini`

Please please can zip and unzip extensions be enabled by default for PHP?

**Comment by BronsonQuick** [comment]
@paulgibbs Thanks for the bug report. I didn't realise that was another extension that was removed in 5.6+. I've done a PR for this so you can use that branch until my PR is reviewed and merged.

Sorry about that and thanks for reporting it! 💖
