### ISSUE TITLE
Move to Ubuntu 16.04

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#311]
We're currently on 12.04 (precise) LTS which is only supported through April. We can move either to 14.04 (trusty) which is supported through April 2019, or 16.04 (xenial) which is supported through April 2021. We may as well move to the latest LTS (16.04).

Looking into what will be required here. In particular, this drops Upstart in favour of systemd, which means we may be able to run inside a Docker container (#272). I suspect a bunch of things will break here.

**Comment by BronsonQuick** [comment]
We've shipped Xenial now so we can close this issue. 💃🏻
