### ISSUE TITLE
Default hosts don't get added to /etc/chassis-hosts/conf.d/subdomains on provision

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#320]
So when using `multisite: subdomains`, the `hosts` from `config.yaml` don't get added to `Multisite subdomains don't get added to /etc/chassis-hosts/conf.d/subdomains`. 

Only when you go Network Admin > Sites and create a subdomain will it get added. While this might be the preferred way, when using the following code:

```
	wp::plugin { $plugins:
		location => '/vagrant/wp',
                networkwide => true,
		require  => Class['wp'],
	}
```

Will error out the following code on provision:

```
==> default: Notice: /Stage[main]/Main/Chassis::Wp[vagrant.local]/File[/vagrant/local-config-extensions.php]/content: content changed '{md5}b24989b3ec57d8f506c316d6d84f3e84' to '{md5}fcbdc6ed7f257edae64dedcbeeb82ae5'
==> default: Notice: /Stage[main]/Vip::Plugins/Wp::Plugin[keyring]/Exec[wp install plugin keyring]/returns: Error: Site vagrant.local/ not found.
==> default: Error: /usr/bin/wp plugin install keyring returned 1 instead of one of [0]
```

Take note on: Error: **Site vagrant.local/ not found.**

**Comment by BronsonQuick** [comment]
Fixed. Props @stuartshields
