### ISSUE TITLE
Extension request: WordCamp meta environment

### ISSUE THREAD

**Issue by tareiking** [Chassis/Chassis#325]
When developing a local WordCamp theme, the recommendation is to use VVV + the [WordPress.org meta environment repo](https://github.com/WordPress/meta-environment) - however, that's a pain-filled process (try it, I dare you.. but don't because - sanity).

What would be perfect is an extension that loaded the provisioning databases, host entries and sub-sites required to quickstart a WordCamp theme environment built-on chassis.

The current WordCamp provisioning scripts are here: https://github.com/WordPress/meta-environment/tree/master/wordcamp.dev/provision and could help with the extension.

I have a huge feeling that all WordCamp theme developers would be so dang grateful for such an extension.

**Comment by stuartshields** [comment]
@tareiking I might have a look into this once I've finished the VIP extension. I know Bronson has a bit of work cut out for him with the multisite bug I found the other day.

**Comment by cameronjonesweb** [comment]
I've been using VVV for building the Brisbane theme, it took 3-4 hours to provision and getting it working was so painful I even wrote a guide. A Chassis extension would be amazing

**Comment by tareiking** [comment]
This has largely been resolved using @stuartshields https://github.com/stuartshields/chassis-wordcamp/.

Closing issue.
