### ISSUE TITLE
Correct our check for $_SERVER['HTTP_HOST']

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#328]
As it turns out [this](https://github.com/Chassis/Chassis/blob/master/wp-config.php#L53) check is incorrect and it should be `! isset` rather than `empty` more details on this are over here: https://github.com/Chassis/Chassis/issues/324#issuecomment-277432764

**Comment by kasparsd** [comment]
@BronsonQuick What is the value of `$_SERVER['HTTP_HOST']` which fails the `empty()` check?

**Comment by stuartshields** [comment]
@kasparsd Have a look at the ticket referenced. However:

`==> default: Error: /usr/bin/wp core install --url='http://vagrant.local/' --title='WordPress Site' --admin_email='admin@example.com' --admin_name='admin' --admin_password='password' returned 255 instead of one of [0]
`
