### ISSUE TITLE
Add phpMyAdmin

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#33]
We should add phpMyAdmin to the build.

**Comment by greaveselliott** [comment]
Alternatively you could ditch phpMyAdmin for a native software package like Sequal Pro

**Comment by BronsonQuick** [comment]
@greaveselliott Yeah good call! I have a doc on that if you need it too: https://github.com/Chassis/Chassis/wiki/Connecting-to-MySQL :+1: 

Seeing you'll be running two Chassis boxes at once Sequel Pro probably won't suit in that case so you'll want to add the phpMyAdmin Chassis extension for both installs: https://github.com/Chassis/phpMyAdmin
