### ISSUE TITLE
Allow setting language in config.yaml

### ISSUE THREAD

**Issue by cameronjonesweb** [Chassis/Chassis#335]
Would be good to have for anyone not using US English, save us having to update settings once it's been provisioned.

**Comment by BronsonQuick** [comment]
Good idea! I might be able to whip something up for that this arvo!

**Comment by BronsonQuick** [comment]
@cameronjonesweb I just had a chat to McCue. He's keen for me make a Dictactor extension instead. https://github.com/Chassis/Chassis/issues/59

I'll close this for now but keep your eye on that other ticket and I'll see how I go.
