### ISSUE TITLE
Adding custom nginx

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#344]
@BronsonQuick and @rmccue we need to add custom settings to the nginx file for VIP Extension. See here: https://github.com/automattic/vip-wpcom-mu-plugins#concatenation

**Comment by rmccue** [comment]
Additional config files can be placed into `/etc/nginx/sites-available/{fqdn}.d/` and then get loaded; this was just fixed in the multisite config to match single sites: #341
