### ISSUE TITLE
Unable to use PHP version 7.0.16

### ISSUE THREAD

**Issue by katmoody** [Chassis/Chassis#346]
I'm just starting to get started with Chassis, but ran into this small issue when I tried to change my configuration to match a user's reported issue with the BWP plugin. This specific version 7.0.16 was the one supposedly having issues, but when I tried to update my local config file it fails to find the correct file (I think?): 

```Error: /Stage[main]/Chassis::Php/Package[php7.0.16-common]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install php7.0.16-common' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package php7.0.16-common
==> default: E: Couldn't find any package by regex 'php7.0.16-common'
==> default: Warning: /Package[php7.0.16-cli]: Skipping because of failed dependencies```

Do you need any other information? I switched back to PHP version 7.0

**Comment by rmccue** [comment]
This seems like a bug. Internally, Chassis should be transforming `7.0.16` to `package => php7.0, version => 7.0.16`, but we may be using the wrong variable.

**Comment by BronsonQuick** [comment]
@katmoody Ryan's fixed this and I've merged it so you can do `git pull` in the root directory of Chassis and you should be right now. Thanks for reporting this!

**Comment by katmoody** [comment]
Happy to help. My youngest somehow messed up my system yesterday morning so I'm in the middle of doing some reinstalling here anyway so I'm resetting a couple of my developer apps ;-)
