### ISSUE TITLE
Add option to increase memory

### ISSUE THREAD

**Issue by fklein-lu** [Chassis/Chassis#352]
I want to increase the memory allocated to Chassis, so I used a `Customfile` with the following contents (using Virtualbox):
```
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
end
```

I'm not sure that this actually works. The reason I want to do this is that I want to run WP unit tests faster, and I'm not sure whether there are not other settings limiting Chassis' performance.

**Comment by fklein-lu** [comment]
A weird thing that manifested itself today was that the unit tests run really fast for a while, and then super slow again, and then back to fast, without any changes to Chassis (not even rebooting).

**Comment by rmccue** [comment]
Per above edit, closing out. #283 will fix this in a more general sense.
