### ISSUE TITLE
Install mcrypt for everything before 7.1

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#359]
mcrypt will need to be installed for everything up to 7.0.

mcrypt in 7.1 is deprecated - http://php.net/manual/en/migration71.deprecated.php

**Comment by stuartshields** [comment]
FYI, I'll do the PR for this tomorrow.

**Comment by rmccue** [comment]
Is this required for WP to run? If not, should be in an extension, not in Chassis core.

**Comment by rmccue** [comment]
This is extension-land, not Chassis-land, as mcrypt isn't required by core. (It's optionally used inside the random_compat library.) Additionally, mcrypt was deprecated because it's very out-of-date with no maintainers, and is potentially unsafe for usage.

**Comment by BronsonQuick** [comment]
FYI: I made this extension the other day: https://github.com/Chassis/mcrypt #yourewelcome
