### ISSUE TITLE
Themes/plugins are skipped from content/config.yaml

### ISSUE THREAD

**Issue by LewisCraik** [Chassis/Chassis#362]
I have created my own config.yaml within my content directory (see attached minus .txt extension).

Of the plug ins I have included wordpress-importer is installed, but jetpack is not. I have also tried including themes, currently total, they are completely skipped.

I am not sure if this is a bug or user error on my part.
[config.yaml.txt](https://github.com/Chassis/Chassis/files/880499/config.yaml.txt)

**Comment by harleyoliver** [comment]
Just tried it and it worked fine for me, what's your error log saying?

**Comment by LewisCraik** [comment]
Where can I find my error log? I have debug.log in my contents folder, but that doesn't seem related to my last vagrant up, which did not include the themes/plugins.

**Comment by BronsonQuick** [comment]
@LewisCraik You can uncomment [this line](https://github.com/Chassis/Chassis/blob/master/Vagrantfile#L94) to see more information form vagrant.

Did you create a new content directory as per [the instructions](http://docs.chassis.io/en/latest/quickstart/#installing)? I think if those directories aren't created it'll probably fail. I haven't tested that though it's just a guess!

**Comment by LewisCraik** [comment]
I have created the content/theme and content/plugins folders. One of the plugins (wordpress-importer seems to work). The other, jetpack does not.

Thanks for the tip about extended logging, I see this error for the plugin:
```
==> default: Debug: Exec[wp install plugin jetpack --activate](provider=posix): Executing check '/usr/bin/wp plugin is-installed jetpack'
==> default: Debug: Executing '/usr/bin/wp plugin is-installed jetpack'
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Plugin[jetpack]/Exec[wp install plugin jetpack --activate]/unless: Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'wordpress'@'localhost' (using password: YES) in /vagrant/wp/wp-includes/wp-db.php on line 1538
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Plugin[jetpack]/Exec[wp install plugin jetpack --activate]/unless: Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
==> default: Debug: Exec[wp install plugin jetpack --activate](provider=posix): Executing check '/usr/bin/wp core is-installed'
==> default: Debug: Executing '/usr/bin/wp core is-installed'
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Plugin[jetpack]/Exec[wp install plugin jetpack --activate]/onlyif: Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'wordpress'@'localhost' (using password: YES) in /vagrant/wp/wp-includes/wp-db.php on line 1538
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Plugin[jetpack]/Exec[wp install plugin jetpack --activate]/onlyif: Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```
And this for the theme:
```
==> default: Debug: Exec[/vagrant wp theme activate total](provider=posix): Executing check '/usr/bin/wp core is-installed'
==> default: Debug: Executing '/usr/bin/wp core is-installed'
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Theme[total]/Wp::Command[/vagrant theme activate total]/Exec[/vagrant wp theme activate total]/onlyif: Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'wordpress'@'localhost' (using password: YES) in /vagrant/wp/wp-includes/wp-db.php on line 1538
==> default: Debug: /Stage[main]/Main/Chassis::Wp[vagrant.local]/Wp::Theme[total]/Wp::Command[/vagrant theme activate total]/Exec[/vagrant wp theme activate total]/onlyif: Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```

**Comment by BronsonQuick** [comment]
@LewisCraik Thanks for the logs. Looking at that my guess is that the database hasn't been installed and setup by Chassis at that stage. I haven't fully tested installing themes and plugins from scratch. I'll look into this next week for you.

I think for now if you comment out the themes and plugins section then do a `vagrant up` you should get a proper install. After that you can add back the plugins and themes sections and run `vagrant provision` and that should finish off the installation

**Comment by LewisCraik** [comment]
Thanks, I'll try that. 

Is it worth me uploading the full log?

**Comment by BronsonQuick** [comment]
Yeah a full log would be fabulous. Thanks!

**Comment by LewisCraik** [comment]
Full log attached.
[log.txt](https://github.com/Chassis/Chassis/files/888627/log.txt)

Your suggested workaround did not work either - I have attached logs for that two, both the up and provision stages.
[log2.txt](https://github.com/Chassis/Chassis/files/888678/log2.txt)

**Comment by BronsonQuick** [comment]
@LewisCraik Thanks for the logs. I didn't realise that themes weren't being installed correctly as I'd never tested that before! 😱

I've filed a PR upstream to the `puppet-wp` submodule we use which makes sure the theme installs correctly. I'll have to update the reference to that submodule if that gets merged in.

**Comment by BronsonQuick** [comment]
I think we fixed this at some point!
