### ISSUE TITLE
Branch a 2.0 for development

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#364]
Let's start a 2.0 development branch (`two-dot-oh`). Things to merge essentially straight away:

* [x] Extensions v2: #293 
* [x] Xenial: #312

**Comment by rmccue** [comment]
Branched, ready for merging.

**Comment by BronsonQuick** [comment]
@rmccue Looks like it needs a PR and a push? https://github.com/Chassis/Chassis/tree/two-dot-oh
