### ISSUE TITLE
Warn user if submodules are out-of-date (and offer to update for them)

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#368]
With 2.0, there's major changes to submodules required to provision. When we're provisioning, we should check that submodules are up to date, and offer to run the update for the users, similar to how we initialise them automatically for them.

```
WARNING: Your Chassis submodules appear to be out-of-date, and provisioning may
         fail. Would you like to update them now? [Y/n]
```

**Comment by BronsonQuick** [comment]
I'm gonna close this out seeing I have thing covered in $504.
