### ISSUE TITLE
Change PHP 5.6 to 7.0 in documentation

### ISSUE THREAD

**Issue by zela** [Chassis/Chassis#372]
Didn't find repository for docs.chassis.io, so writing here, sorry.

Just want to point out that here (http://docs.chassis.io/en/latest/quickstart/#what-s-in-the-box) is mentioned PHP 5.6, but Chassis contain version 7.0 for quite a while by default.

Thanks!

**Comment by rmccue** [comment]
Thanks @zela! For reference, docs are in the `docs/` directory in this repo :)
