### ISSUE TITLE
NFS fails on vagrant up

### ISSUE THREAD

**Issue by morganestes** [Chassis/Chassis#375]
## Expected
Provisioning a new VM should map my local Chassis directory to `/vagrant` on the VM.

## Actual
Provisioning succeeds with errors; NFS fails to map Chassis to `/vagrant` and logs to `/var/log`.

## Summary
On a new install of Chassis, vagrant throws an error and fails to fully map to `/vagrant`, so I'm left with a running VM with an empty `/vagrant` directory and no WordPress install.

Here's the error messages:

```sh
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.28.128.1:/Users/mestes/Sites/obyp-chassis/Chassis /vagrant
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

I've verified that `/etc/exports` on my host machine has the expected entries, the `/vagrant` directory exists on the VM (empty), and `nfsd` is running on host (macOS Sierra 10.12.4).

Reverting changes made in #371 allows me to provision the VM and get a working dev environment.

**Comment by BronsonQuick** [comment]
@morganestes Thanks for the bug report! I think I'll roll back NFS for now then. Ryan did raise a concern after I merged it: https://github.com/Chassis/Chassis/pull/371#issuecomment-299752228 as usual he's always on the ball!

For my own reference could you please let me know what operating system you're using and the version and also the versions of Virtual Box and Vagrant you're using please? That will help my debug this when I'm having a crack at adding NFS behind a config flag. Thanks!

**Comment by morganestes** [comment]
@BronsonQuick Thanks for the update.

I'm running VirtualBox 5.1.18 r114002, Vagrant 1.9.2. macOS Sierra 10.12.4.
