### ISSUE TITLE
Chassis doesn't recoginize installed virtualbox

### ISSUE THREAD

**Issue by zu** [Chassis/Chassis#382]
![chassis](https://cloud.githubusercontent.com/assets/147629/26447575/65d3ca10-4149-11e7-8aca-f8b40e3bc1dd.png)

Obviously I'm in the "everyone group" that is not at home at the command line but is supposed to be able to handle chassis nevertheless.

Didn't get into the documentation yet, but just starting the tool made me insecure, because as you can see in the screen shot VirtualBox is installed here.

**Comment by ntwb** [comment]
Thanks for creating this issue @zu, we're already tracking this issue in https://github.com/Chassis/Desktop/issues/2 so I'll close this in favour of that issue 😄

**Comment by zu** [comment]
Thanks!


(hopefully this doesn’t reopen the issue)




--\|/--------------------------------
  Christian Zumbrunnen
  Holzmatt 7, 5200 Brugg
  Mobile: 079 784 52 37
  Twitter: @chzumbrunnen
