### ISSUE TITLE
Chassies hangs on provisioning

### ISSUE THREAD

**Issue by taija** [Chassis/Chassis#388]
I am attempting to set up a Chassis development environment for the first time; a good bit of previous experience with Vagrant, but just found out about this project. 

After running `vagrant up` for the first time, Vagrant is hanging at 
```
==> default: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}44e7aa974ab98260d7d013a2087f1c77'
```
By `CTRL+C` ing twice I can exit, restart, and re-provision, which will get me past this hang around half the time. 

I am running up-to-date VirtualBox and Vagrant, on up-to-date macOS Sierra.

**Comment by BronsonQuick** [comment]
Hey @taija, just wondering if you're still having this issue?

Could you try setting this [line](https://github.com/Chassis/Chassis/blob/master/config.yaml#L38) to `Yes` to see if using a mirror helps speed this up.

Out of curious how long did Chassis stay on that line for?

Another option to see what's happening in more detail is to uncomment [this line](https://github.com/Chassis/Chassis/blob/master/Vagrantfile#L94) to see some more verbose output.

Sorry for the delay in getting back to you. I've been travelling!

**Comment by BronsonQuick** [comment]
I'm going to close this for now as I can't replicate it. If you're still having issues please feel free to open it for me and add more details and I'll get back to you!
