### ISSUE TITLE
Make it easier to work with WP-CLI packages

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#389]
In order to install a WP-CLI package you need to run `sudo wp package install ... --allow-root` because the vagrant user doesn't have write permission to the `/home/vagrant/.wp-cli` directory.

Can this be changed to avoid the need to use sudo and the allow-root flag?

**Comment by rmccue** [comment]
This sounds like a bug with the way we're provisioning; I bet we have a `file {}` with the wrong owner.
