### ISSUE TITLE
Custom pre and post provision scripts

### ISSUE THREAD

**Issue by noplanman** [Chassis/Chassis#399]
I see in the `puppet` folder that there are a `preprovision.sh` and `postprovision.sh` file.

It would be really great if the user could also define own scripts like this, to allow for any special configurations to be set before provisioning starts and after it ends.

Simply loading any existing `preprovision.sh` and `postprovision.sh` file from the root folder could do the trick.

My use case: APT caching
Thanks to our snaily internet at home, provisioning a new box takes forever, as it needs to download *everything* each time. For this reason, I have an instance of [apt-cacher-ng](https://www.unix-ag.uni-kl.de/~bloch/acng/) running on a server at home. This way, all other servers get their packages cached, meaning that they only need to be downloaded from the interwebz once.
This speeds up updating a LOT, for very obvious reasons.

To be able to use this, I need to add an apt config to the box before any apt commands get called, to make sure they all get proxied to the caching server.
Having a `preprovision.sh` loaded would allow exactly this, in a very simple way!

I'm also hinting towards #390 with this one. At least for some cases, like mine :wink:

**Comment by rmccue** [comment]
The best way to add custom scripts is to add extensions currently. Generally speaking, we want people to use Puppet, since it makes the setup much more repeatable. More complex extensions can add their own provisioning if they need to (this should already be possible). There aren't many cases where you need to run things before `preprovision.sh`.

However for this specific case, we have the `apt_mirror` configuration, which writes to `/etc/apt/sources.list` so you can likely set this instead (Apt-Cacher NG notes this as an option). Does that solve your problem?

**Comment by noplanman** [comment]
@rmccue You're totally right, it did work with `apt_mirror` :tada:

I tried it yesterday and it didn't work, must have had some silly typo or something, cause it wasn't finding the sources. :grin:

Say I do want to go the way of setting the proxy in the apt configs, what would be the best way?
Should I just fork the project and ignore the `puppet/{pre,post}provision.sh` files, and update them each time I pull from upstream?

@BronsonQuick

**Comment by rmccue** [comment]
You can [write an extension for Chassis](http://docs.chassis.io/en/latest/extend/); a `.vagrantplugins` file inside your extension will be loaded as part of Vagrant's plugin loader. I believe you should be able to register another provision script as part of that.

**Comment by noplanman** [comment]
Thanks @rmccue 

I've managed to make a tiny extension that allows any custom proxy to be added (via `config.local.yaml`), which is great!
But, it only gets called after the initial `puppet/preprovision.sh` file, which installs puppet and starts the whole provisioning.

Any way to get it executed before that?

For now I'll just use this in `Vagrantfile` before the puppet preprovision:
```
if File.exist?(File.join(File.dirname(__FILE__), "preprovision.sh"))
	config.vm.provision :shell, :path => "preprovision.sh"
end
```
