### ISSUE TITLE
Respect extension loading order

### ISSUE THREAD

**Issue by noplanman** [Chassis/Chassis#401]
The way chassis imports the extensions configurations now is by using file globbing:
```
# Load extensions
import "/vagrant/extensions/*/chassis.pp"
```
(https://github.com/Chassis/Chassis/blob/2.0/puppet/manifests/development.pp#L2)

I'm not sure how the internals work exactly, but it seems the order of the files loaded is random.

Is it possible to make it load extensions in the order that they are listed in the config?

My use case is to make sure that my little [APT proxy extension](https://github.com/noplanman/chassis-apt-proxy) is loaded first, before any others, to make the most of the caching.

**Comment by rmccue** [comment]
Extensions are not guaranteed to load in any particular order, and we likely won't change this.

Instead, you can use Puppet's dependency chaining:

```puppet
class {"apt-proxy":
    # ...
    before => Class['apt'],
}
``

If you absolutely have to be first (which makes sense for apt caching, but not for most extensions), you can also use [Puppet's stages](https://docs.puppet.com/puppet/latest/lang_run_stages.html). All Chassis extensions run in the `main` stage usually, so you could do this:

```puppet
stage { 'preinstall':
    before => Stage['main'],
}
class {"apt-proxy":
    # ...
    stage => preinstall,
}
```

**Comment by noplanman** [comment]
Perfect @rmccue, thanks so much!

Since the initial installation of puppet comes before the playbook anyway and there is no way to hook into the provision earlier, these both seem to have the same effect, but I'll go for the second solution, just in case other extensions also need packages installed. Not sure if this makes sense though, as apt seems to be called first in `development.pp` 🤔 

Is there any danger in another extension also defining a `preinstall` stage?
Should I maybe set it to a random string to make sure it doesn't clash with any other extension?

**Comment by rmccue** [comment]
You can definitely call the stage whatever you want, but stages are basically never used anyway, so the likelihood of a clash is minimal. This is the first time I've ever recommended anyone use them. :)

**Comment by noplanman** [comment]
> This is the first time I've ever recommended anyone use them. :)

😊 
Opted for `preinstall_apt_proxy`. It's working beautifully now!

*over & out*

**Comment by noplanman** [comment]
@rmccue @BronsonQuick 
I've seen the latest v2 for the extensions and would like to upgrade my apt-proxy extension.
How do I get it to load first like before? Seems like the class is generated in the chassis code, so there's no way to override the loading order with the `stage` parameter.

Is there some other way I can manipulate the loading order?

**Comment by rmccue** [comment]
@noplanman Best way is to split the class: have your init class (`apt-proxy`) specify a separate class (`apt-proxy::config`) and set the class on that. Basically, move your `chassis.pp` content inside the init class.

```puppet
class apt-proxy (
    $config
) {
	if ( $config[apt_proxy] ) {
		stage {"preinstall_apt_proxy":
			before => Stage['main'],
		}
		class {"apt-proxy::config":
			file  => $config[apt_proxy][file],
			http  => $config[apt_proxy][http],
			https => $config[apt_proxy][https],
			stage => preinstall_apt_proxy,
		}
	}
}
```

**Comment by noplanman** [comment]
Perfect! This Puppet thing is pretty sweet and flexible, me likes it :smiley:

Hopefully the last question:
I see that the extensions folder name must be the same as the class. The repository name on GitHub is different though, so it gives me a `Could not find declared class chassis-apt-proxy` error, because the module and class are simply `apt-proxy`.
Is there a way of saying that the extension is at `noplanman/chassis-apt-proxy` but that the folder it clones to should then be called `apt-proxy`?
Or must I either rename the repo or class?
