### ISSUE TITLE
Custom rewrite rules

### ISSUE THREAD

**Issue by grappler** [Chassis/Chassis#403]
I would like to hide `/wp/` in admin URL. How to do this is explained in https://github.com/wecodemore/wpstarter/issues/15 but I could not see a way in the config to do this without making a change to `puppet/modules/chassis/templates/site.nginx.conf.erb`

That is why I also created a PR to remove the useless `.htaccess` #402

**Comment by rmccue** [comment]
This should be possible already by adding an additional conf file with [the right name](https://github.com/Chassis/Chassis/blob/2cde06fac4bf18a65fdd646ec2db54614c9b61d4/puppet/modules/chassis/templates/site.nginx.conf.erb#L11). (You can build that into an extension pretty easily too.) Does that approach work for you?

**Comment by grappler** [comment]
That should work. I tried to do this but I am getting an error `Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class grappler at /vagrant/extensions/grappler/chassis.pp:3 on node vagrant.local`

I am not sure what I am doing wrong. It is my first time working with Puppet.

https://github.com/grappler/chassis-grappler

**Comment by rmccue** [comment]
You need to declare [your class](https://github.com/grappler/chassis-grappler/blob/master/modules/grappler/manifests/init.pp) as a class, rather than a define.

The [memcache extension](https://github.com/Chassis/memcache/blob/master/modules/memcache/manifests/init.pp) has a good example of this.

**Comment by grappler** [comment]
Thanks. I got that part work. How do I get my extension to run after [puppet/modules/chassis/manifests/site.pp](https://github.com/Chassis/Chassis/blob/master/puppet/modules/chassis/manifests/site.pp)?

It is failing at the moment with `Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir`. I think it is due to `/etc/nginx/sites-available` not being created before.

```
file { '/etc/nginx/sites-available/$name.d':
	ensure => directory
}
```

**Comment by rmccue** [comment]
You can add `require => File[ '/etc/nginx/sites-available/$name' ]` to your resources, which should set up the dependency chain for you.

However, you'll need to use the right variable; `$name` is set automatically set to `$config['hosts'][0]` somewhere up the chain, so you'll want to use that instead.

**Comment by grappler** [comment]
Thank you very much for your help and patience. I got it to work!!!!

Feel free to tell me everything that I have done wrong. https://github.com/grappler/chassis-grappler

Do you have a suggestion for a better name?

**Comment by BronsonQuick** [comment]
@grappler Thanks so much for creating the extension! For a name maybe `chassis-custom-rewrites` perhaps?

**Comment by grappler** [comment]
Thanks! I have updated the git repo https://github.com/grappler/chassis-custom-rewrites
