### ISSUE TITLE
Define machine name

### ISSUE THREAD

**Issue by grappler** [Chassis/Chassis#404]
I would be cool if there was a way to define the machine name. It makes it easier to manipulate the multiple instances. The change would need to be made to `Vagrantfile`. Run `vagrant global-status` to see if it is working.

https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name

**Comment by rmccue** [comment]
Is this just for `vagrant global-status`? The directory is already listed there, so I'm not sure how useful setting the name would be.

The VirtualBox machine names should already be set to the name of the directory (per both the above link, and also confirmed that locally).

**Comment by grappler** [comment]
> Is this just for `vagrant global-status`? 

No, you could also run `vagrant up maschine-name` or `vagrant provision maschine-name` making it easier to target specific machines without needing to be in the correct directory.

> The VirtualBox machine names should already be set to the name of the directory (per both the above link, and also confirmed that locally).

Strange I don't have this. I also don't have this for VVV so it could be a local issue.

This is my output for `vagrant global-status`

```
508a174  default       virtualbox running webdev/vagrant-local [VVV]
caa5d85  wearerequired virtualbox running  /webdev/wearerequired.local/_vagrant [puphpet]
ebc9792  atlantis      virtualbox poweroff /webdev/appflow [*Appflow]
8d3e149  default       virtualbox poweroff webdev/chassis [chassis]
8d94ba2  default       virtualbox poweroff webdev/php52 [chassis]
```

*[Appflow](https://github.com/ttssdev/appflow)

**Comment by BronsonQuick** [comment]
We've finally added support for this: https://github.com/Chassis/Chassis/pull/633
