### ISSUE TITLE
PHP 5.2 support

### ISSUE THREAD

**Issue by grappler** [Chassis/Chassis#405]
I just wanted to check some code in PHP 5.2 but I could not set it up because of the following errors.

```
Error: Duplicate declaration: Package[php5-fpm] is already declared in file /vagrant/puppet/modules/chassis/manifests/php.pp:98; cannot redeclare at /vagrant/puppet/modules/chassis/manifests/php.pp:129 on node php52.local
Error: Duplicate declaration: Package[php5-fpm] is already declared in file /vagrant/puppet/modules/chassis/manifests/php.pp:98; cannot redeclare at /vagrant/puppet/modules/chassis/manifests/php.pp:129 on node php52.local
```

I have seen the previous PRs and Issues: #109 #10

**Comment by rmccue** [comment]
Unfortunately, PHP 5.2 isn't supported by the underlying packages; that is, we have no viable way to install it.

We could potentially use [phpenv](https://github.com/phpenv/phpenv), but I don't think that supports 5.2 any more, and it may also be a bit brittle.
