### ISSUE TITLE
Unable to adjust PHP variables within php.ini.erb for server adjustments

### ISSUE THREAD

**Issue by katmoody** [Chassis/Chassis#411]
MacOS Sierra, version 10.12.5
Vagrant 1.9.5
Oracle VM VirtualBox Manager 5.1.22

The only change added to the config.yaml was for the domain name: buwp.local and to add the BackUpWordPress plugin

No Chassis extensions installed in this one

---

I attempted to change 4 options within the php.ini.erb file: 

- `max_execution_time` - change to 30
- `max_input_time` - change to 60
- `memory_limit` - change to 128M
- `proc_open` - add to disabled functions

I re-provisioned after making the changes and saving the file. The changes for `proc_open` and `max_input_time` were applied but the changes for `max_execution_time` and `memory_limit` didn't. 

See image regarding the default for `max_execution_time`:

<img width="467" alt="screen shot 2017-07-10 at 11 18 45 am" src="https://user-images.githubusercontent.com/5481211/28146913-27db19fc-674b-11e7-9f03-444f04639df6.png">

A LOT of searching online found that others are having this issue with setting a `max_execution_time` because of the `CLI SAPI`but I didn't find anything about a fix or that would point to a specific thing related to Chassis itself? I tried changing the `memory_limit` a number of different ways with no success so something is pre-empting that value from being changed? 

Tell me whatever else I can give you or tell you to help with troubleshooting.

**Comment by BronsonQuick** [comment]
I've shipped version 1 of a new extension to handle this customisations: https://github.com/Chassis/phpini I'll close this for now. Feel free to open it back up if you have any issues.
