### ISSUE TITLE
[Nginx] Conflicting server name "vagrant.local" on 0.0.0.0:80

### ISSUE THREAD

**Issue by andreilupu** [Chassis/Chassis#412]
1. What operating system do you use?
macOS Sierra 10.12.5
2. What version of Vagrant are you running?
vagrant 1.9.7
3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox

Hi, and congrats for starting this awesome project, I'm eager to give it a proper try and maybe contribute.
I've been trying to use Chassis on my machine but whenever I press Launch there is just in infinite loading and nothing happens.  Do you have any suggestions on how to debug that?

Anyway, I've opened the terminal, hit `vagrant up`, and now my machine has the green icon(but the status is still "Launching").

Now the problem is that the website is accessible at http://vagrant.local but I cannot access anything else like /wp-admin.
This is how my nginx log looks like:
```
2017/07/11 05:54:37 [warn] 29254#29254: duplicate MIME type "text/html" in /etc/nginx/nginx.conf:45
2017/07/11 05:54:37 [warn] 29254#29254: conflicting server name "vagrant.local" on 0.0.0.0:80, ignored
```

I'm not familiar with VVV, and I don't know yet how to find the Nginx config, but maybe the `nginx.conf.erb` template file has a `~` slipped as in https://stackoverflow.com/questions/11426087/nginx-error-conflicting-server-name-ignored ?

**Comment by rmccue** [comment]
This is just a warning, shouldn't actually affect anything otherwise.

The admin should be at http://vagrant.local/wp/wp-admin/ (since WordPress is in a subdirectory). Does that work for you?

> I've been trying to use Chassis on my machine but whenever I press Launch there is just in infinite loading and nothing happens. Do you have any suggestions on how to debug that?

Tracking that over at https://github.com/Chassis/Desktop/issues/17

**Comment by andreilupu** [comment]
Oh, that was so obvious, thank you! It works if I access the subdirectory.

For the second issue, I'll post in #17
