### ISSUE TITLE
Nginx 404 Error

### ISSUE THREAD

**Issue by KawaiiHannah** [Chassis/Chassis#417]
Hello! I've run into this issue for the past couple of weeks, but finally tested it on a base Chassis install with NO special configurations etc after a fresh restart, so there's no other boxes running at the same time. 

Once the box is provisioned, I can view the website, but after a few page loads, I get an Nginx 404 error that persists even after reloading or provisioning. I've attached the access logs and error log for Nginx

## The home page also then displays the following notice:

----

Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

----

## Other notes
1. What operating system do you use?
Windows 10 Pro

2. What version of Vagrant are you running?
1.8.5

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 5.1.22 r115126 (Qt5.6.2)

4. Do you have a custom YAML file? If so, what does it contain?
Not in this case

5. Do you have any Chassis extensions installed? If so, what are they?
Not in this case.

[access.txt](https://github.com/Chassis/Chassis/files/1154266/access.txt)
[error.txt](https://github.com/Chassis/Chassis/files/1154267/error.txt)

**Comment by cameronjonesweb** [comment]
I've noticed this too, for me Chrome is fine but all other browsers get the 'Welcome to nginx' page

**Comment by rmccue** [comment]
This can happen if you hit nginx's default site configuration, which can happen if you load the wrong domain. Are you accessing `http://vagrant.local/` here?

**Comment by KawaiiHannah** [comment]
So sorry for the late response - definitely accessing http://vagrant.local/ and getting that error.

**Comment by BronsonQuick** [comment]
I'll set a reminder to fire up my Windows laptop when I get back to Brisbane so I can see if I can hunt down why this is happening.

**Comment by KawaiiHannah** [comment]
Awesome, thank you! I'm happy to test as well - I've got a few boxes, both those with custom yaml files and a few test ones without.

**Comment by KawaiiHannah** [comment]
So I'm still experiencing this issue, but I did some more testing today and while I honestly feel like I have no idea what I'm doing, this seems to work at least temporarily so I can export stuff:

SSH in and run 'sudo nginx -t && sudo service nginx reload'

Then exit and vagrant reload the box. The box starts working again as it should, but only for a short time before I start experiencing the issue again. If I try reloading without SSHing in and reloading nginx, it doesn't work.

**Comment by BronsonQuick** [comment]
Hey @KawaiiHannah, sorry for the delay on me getting around to test this! I only just fired up my old Windows laptop this afternoon and found out something had broken upstream so I had to hunt down and patch https://github.com/Chassis/Chassis/pull/432 first as well as download all the Windows updates!

So far I haven't been able to replicate this issue. 😢 I'm on Windows 8.1 on this old laptop though so I'm wondering if perhaps it's isolated to Windows 10 so I might need to buy that and upgrade to replicate this perhaps?

I've been able to browse to http://vagrant.local/ in both Firefox and Chrome and I've been able to hit various URLs and they'll still resolve for me without any Nginx 404s.

I'm racking my brain trying to think what might be different for me apart from me being on Windows 8.1!

Apart from that, here are some ideas that spring to mind:
- Try updating Vagrant as I'm on `1.9.1`
- Try updating VirtualBox as I'm on `5.1.26`
- When this has happened is there any chance that you've changed Wifi or LAN networks or changed proxies? Vagrant and VirtualBox can be funny about that.

Sorry this is an issue for you and @cameronjonesweb. I think I'll see if I can upgrade to Windows 10 and hopefully replicate it

**Comment by BronsonQuick** [comment]
Ooh ooh, one more idea @KawaiiHannah. Any chance you could try this as a potential fix too? https://github.com/Chassis/Chassis/issues/424 Thanks!

**Comment by KawaiiHannah** [comment]
No worries @BronsonQuick :) I've updated Vagrant and VirtualBox and tried that potential fix as well, but sadly I'm still getting that error. After a fresh restart, the box worked again for a while in Chrome, but didn't work at all in Firefox and IE. I don't think I've got any old PCs running Windows 8.1, but I'll see if I can find one.

I do move between work and home, so I would be changing Wifi, but I generally halt the machine once I've stopped work at work and then vagrant up it again when I get home if I need to do anything further.

**Comment by BronsonQuick** [comment]
@KawaiiHannah Thanks for testing those potential fixes for me. I'll download a 90 trial of Windows 10 Pro now to see if I can replicate it.

Thanks for clarifying about the wifi as well so that's eliminated that too at least!

**Comment by BronsonQuick** [comment]
@KawaiiHannah So "good news", I can replicate this on Windows 10 in Firefox. Sorry for the delay! It took me ages getting setup on Windows 10 yesterday and finding the minimal amount of drivers I needed to get setup on my old computer to test this. Let's see if I can get to the bottom of this now.

**Comment by BronsonQuick** [comment]
I've still not been able to work out a fix for this unfortunately 😫. I can replicate it in both Internet Explorer and Firefox but not Chrome. Chrome always works for me which is good but I don't like the idea of Chassis having to make people on Windows 10 "have" to use Chrome.

I've tried changing a lot of security settings in both IE and FF but alas I've had no success.

I'll take my old Windows laptop into the office and try and rubber duck this with @rmccue when I'm back at work in a few weeks. It'll probably only take Ryan half an hour to get to the bottom of this knowing him!

**Comment by cameronjonesweb** [comment]
I tried to set up a new site yesterday on my laptop and I was getting this error even in Chrome. Hannah's temporary fix [here](https://github.com/Chassis/Chassis/issues/417#issuecomment-320874859) wasn't even working. I also couldn't re-provision. That said, today on my work machine the same process is working so I'll have to keep testing

**Comment by emdashbuck** [comment]
Set up a new site today on Windows 10, using Chrome - same issue. I successfully used Chassis on Win10 with Chrome etc. around March 2017 and earlier with this same exact setup (although Bonjour was installed through iTunes instead of Print Service).

#424 did not help.

Happy to do testing etc. since I can't move forward with my project until this is fixed!

**Comment by cameronjonesweb** [comment]
I've run into an interesting aspect of this bug. Using an up-to-date Chassis box, I've found that Chrome only works with an active internet connection. Attempting to work on the train and I'm getting the welcome to nginx screen in all browsers, but as soon as I hotspot off my phone Chrome starts working properly. Don't need to provision or anything once connected, it just works. Once I disconnect the internet, almost straight away it's 404/welcome to nginx again

**Comment by rmccue** [comment]
@cameronjonesweb Are you perchance connected to the Queensland Rail free wifi? I've found connecting to that can cause your hostname to change, which in turn causes the Chassis box name to change.

**Comment by cameronjonesweb** [comment]
Nope, no wifi on this train.

**Comment by cameronjonesweb** [comment]
And back to broken again. Which is really not helpful when half the Gold Coast is without power

**Comment by missjwo** [comment]
Hi, just to comment I'm getting this error. Is there any way to fix this?

**Comment by BronsonQuick** [comment]
So I still haven't been able to replicate this but there is a bit more progress as @rmccue approved my PR that at least changes it from the default page to a troubleshooting page. https://github.com/Chassis/Chassis/pull/564 It's a step forward but I know you were seeing this the other day again @missjwo

**Comment by missjwo** [comment]
Happy to test out the new fixes and share with you the trobleshooting page.

**Comment by BronsonQuick** [comment]
@missjwo Thanks lovely! 🤗 Most appreciated!

**Comment by rmccue** [comment]
See #622; this appears to be an issue with IPv6 connections.

**Comment by rmccue** [comment]
@KawaiiHannah @cameronjonesweb if you have time, could you test out #622 now that it's merged and see if this fixes the issue?

**Comment by BronsonQuick** [comment]
I'm gonna close this one out now as I think @rmccue fixes it in #622.
