### ISSUE TITLE
Allow using multisite with subdomains

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#42]
Here's how we can handle it:
- Drop vagrant-hostsupdater
- Enable avahi-daemon and [avahi-aliases](https://github.com/airtonix/avahi-aliases)
- Output the aliases in `/etc/avahi/aliases.d/default` via erb

Requires Bonjour on Windows hosts.

**Comment by BronsonQuick** [comment]
Fixed in https://github.com/Chassis/Chassis/pull/75
