### ISSUE TITLE
Explicitly Forward Port 80 to Guest

### ISSUE THREAD

**Issue by mike-healy** [Chassis/Chassis#424]
Attempting to setup a Chassis VM on Windows 10 failed as HTTP requests to http://vagrant.local/ were not reaching the VM. SSH connections worked and the VM was running, but HTTP requests were getting stuck on my host machine.

Adding the following line to Vagrantfile seems to have resolved the issue for me:
`config.vm.network "forwarded_port", guest: 80, host: 8000`

I now access the Chassis WordPress instance at http://vagrant.local:8000

I found this behaviour on two different systems, both of which did have Apache running on the host. Stopping the Apache service on the host did not resolve the problem.

## Software
Windows 10 (Pro and Home)
Vagrant 1.9.5
VirtualBox 5.1.22

**Comment by BronsonQuick** [comment]
I think we fixed this in: https://github.com/Chassis/Chassis/pull/623
