### ISSUE TITLE
wp-cli packages failing to install

### ISSUE THREAD

**Issue by indietravel** [Chassis/Chassis#425]
On master (commit d8dfdb59f35af252f9fff3a057d20367289e87c5) with OSX, can't install cli packages.

config.local.yaml has two changes: 
```
- vagrant.local~test.local
content: content~content: content/wp-content
```
Everything else is out of the box.

Running a package install fails silently: 
```
$ wp package install petenelson/wp-cli-size
Installing package petenelson/wp-cli-size (dev-master)
Updating /home/vagrant/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
$ composer --help
-bash: composer: command not found
```
Looking in /home/vagrant/.wp-cli/packages/composer.json I can see the expected text:
```
    "require": {
        "petenelson/wp-cli-size": "dev-master"
    },
```

Package list remains empty; command fails. 
```
$ wp package list
+------+---------+---------+--------+----------------+
| name | authors | version | update | update_version |
+------+---------+---------+--------+----------------+
+------+---------+---------+--------+----------------+
```
Have replicated with several community packages over two chassis installs on the same machine.

**Comment by BronsonQuick** [comment]
Hey @indietravel, that's because we don't install composer by default in Chassis. You should be able to add https://github.com/Chassis/Composer to your Chassis [extensions](https://github.com/Chassis/Chassis/blob/master/config.yaml#L97) and run `vagrant provision` to solve this.

**Comment by indietravel** [comment]
🤦‍♂️  Sorry :( When I get back from holiday, I might try and get a patch into the docs, in order to make that clearer up front. Makes perfect sense, but I overlooked it.

**Comment by BronsonQuick** [comment]
All good! A patch to the docs for that would be amazing. Thank you. Enjoy your holiday!
