### ISSUE TITLE
Add XHProf

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#43]
For those times when Query Monitor isn't enough.

**Comment by BronsonQuick** [comment]
This is definitely extension material! I've made some progress on it here: https://github.com/Chassis/xhprof. I need to iron out a few more things though.

**Comment by rmccue** [comment]
Closing, as there's an extension now (although, the degree to which it works, I'm unsure).

**Comment by BronsonQuick** [comment]
@rmccue It doesn't work yet. I have notes on my desktop about the issue I had. Will chat to you about it on the morrow.
