### ISSUE TITLE
How to connect to DB without SSH tunnel?

### ISSUE THREAD

**Issue by TangRufus** [Chassis/Chassis#439]
1. What operating system do you use?

macOS 10.12.6

2. What version of Vagrant are you running?

Vagrant 1.9.7

3. Are you using VirtualBox or VMWare and which version are you using?

VirtualBox 5.1.26 r117224 (Qt5.6.2)

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

No

5. Do you have any Chassis extensions installed? If so, what are they?

None

-------------------

How to connect to DB without SSH tunnel?

Use case: Run Codeception tests from Mac against Chassis hosted WP sites.

See: [Codeception DB module](http://codeception.com/docs/modules/Db)

**Comment by rmccue** [comment]
You can do this one of two ways.

1) Use the SSH tunnel, but use it to tunnel a specific port to MySQL inside the box. First, run `vagrant ssh-config` to find the port for the connection. Then:

   ```
   ssh vagrant@127.0.0.1 -p {port} -i ./.vagrant/machines/default/virtualbox/private_key -L 12345:127.0.0.1:3306
   ```

   This doesn't require changing your box at all.

2) Configure MySQL inside the box to listen to all IPs by changing `bind-address` to `0.0.0.0` in `/etc/mysql/my.cnf`.
