### ISSUE TITLE
Update documentation on Bonjour for Windows and iTunes

### ISSUE THREAD

**Issue by danielpowney** [Chassis/Chassis#454]
Hey,

It appears the latest iTunes for Windows does not come with Bonjour (on inspection using WinRAR). 

I'm using Windows 10. I followed the recommended instructions to install iTunes. But once my Vagrant box was up, the DNS resolution of vagrant.local did not work. I simply installed Bonjour Print Services and this fixed things. 

Please review and consider updating the website documentation to help others.

Thanks,
Daniel

**Comment by BronsonQuick** [comment]
@danielpowney Ahh awesome. Thanks so much for pointing that out! I'll try and update the documentation for that this week!
