### ISSUE TITLE
Need a way to update the extension list more easily

### ISSUE THREAD

**Issue by shadyvb** [Chassis/Chassis#458]
We need to update the current extension list on the site, and provide an easy way for people to add their own.

Current list is so outdated as we have many more available extension in this org alone.

**Comment by shadyvb** [comment]
Possibly adding a command to install an extension by name from the command line ? Probably using the list on extension index from the site :/

**Comment by rmccue** [comment]
If you mean [this extension list](http://beta.chassis.io/extensions/), it's actually generated from [YAML data on the website repo](https://github.com/Chassis/chassis.io/blob/master/_data/extensions.yaml). You can also get the extension data from the website [as JSON](http://beta.chassis.io/extensions.json). :)

I already started work on building this into [Desktop](https://github.com/Chassis/Desktop/pull/11), not sure if we want to implement anything for the CLI.

**Comment by shadyvb** [comment]
Aha, I guess I didn't know that, maybe some docs on the site to let people know how to publish their extension to the list, and actually adding our own extensions in there ( I've found a few not on that list ).

I don't think adding a CLI command is necessary if we got the desktop version doing that, just acknowledging the full list and making updates accessible is mainly what I'm after.

**Comment by shadyvb** [comment]
Closing this one, issued a PR at https://github.com/Chassis/chassis.io/pull/3.
