### ISSUE TITLE
Using Chassis in a sub-directory

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#46]
I got an email from @rezzz-dev regarding using Chassis in a sub directory:

> One thing I noticed was that Chassis doesn't play nicely under a directory.  Mainly due to this line in the wp-config.php directory.
> `defined('WP_CONTENT_URL') or define( 'WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/content' );`
> 
> So I have a domain called `somedomain.com`.  I normally use it as just a staging spot for some projects, so I drop each project into a subdirectory under that domain.  So the URL may be like `http://somedomain.com/projects/somenewproject` - I know exactly why that's in there, but maybe there's a better way?  For now I just put it in hardcoded since it's just a staging spot, but figured I'd bring it up for future reference/roadmap. 

I'll have a look into this on our next hack day in a couple of weeks.

**Comment by zanematthew** [comment]
Possibly as easy as setting an ANAME?

I haven't dove under the hood of Chassis yet, currently the install is running. I came across this by browsing old issues of issues I may have. One of which sounds like this, let me explain my current set-up I'm trying to emulate, and how I achieve it on a non-Chassis box.

WordPress Networking install, with *sub-domain*

* http://site.com/
* http://site.com/foo

WordPress Networking install, with *sub-folder* on a *sub-domain*

This is achieve by setting an ANAME pointing to a different IP address. Note I'm not sure if Chassis would give you the option to have multiple local IP's (possibly by editing your /etc/hosts file)

* http://clients.site.com/apple
* http://clients.site.com/chrome

Thats my current set-up I achieve via AWS, and I hope to mimic this using Chassis.
