### ISSUE TITLE
Multiple versions of PHP in parallel

### ISSUE THREAD

**Issue by noplanman** [Chassis/Chassis#464]
The way chassis works, is that only a single version of PHP can be used at a time.
To change that, a provision is required, which takes time.

It would be cool if multiple versions could be installed next to each other, to make testing different PHP versions more breezy.

Is that even easily possible with the current setup?

**Comment by rmccue** [comment]
Once you’ve installed a version, I don’t think it’s purged when you switch, so provisioning the switch should be quick. I’ll have to double-check that.

Switching versions quickly isn’t a common use case though, and installing multiple would make the provisioning slower for most people, so it’s not likely to be something we’d do. You should be able to make an extension to download the various versions by default though.

**Comment by BronsonQuick** [comment]
I'm going to close this one out as it's not something we're looking to support.
