### ISSUE TITLE
Vagrant Share fails due to no port forwarding

### ISSUE THREAD

**Issue by joehoyle** [Chassis/Chassis#465]
`vagrant share` appears to fail on OS X / Virtualbox atleast with the following:

```vagrant share
Vagrant Share now defaults to using the `ngrok` driver.
The `classic` driver has been deprecated.

For more information about the `ngrok` driver, please
refer to the documentation:

  https://www.vagrantup.com/docs/share/

==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:
Vagrant was unable to detect an HTTP port for your machine.

Because your machine appears to have no static IP associated with
it, Vagrant scans through your forwarded ports, looking for one
that responds to an HTTP request. Vagrant couldn't find any
functioning HTTP port!

There are a few options to fix this error:

  1. Create a forwarded port pointing to your HTTP server inside
     your Vagrant machine.

  2. Specify an HTTP port manually with `--http` to this command.

  3. Assign a non-local address to your machine. This may or may
     not be possible depending on what provider you're using.

  4. Make sure that the HTTP server is up and running within
     your machine. Vagrant share won't start until it is
     reachable.
```

Due to the fact that port forwarding is not enabled. TBH I don't really understand _how_ the port forwarding is done, as Virtual Box only shows that port 22 is forwarded, and I don't know the internal IP of the vagrant box (or even if I did, we'd need to port forward anyway IIRC).

I followed https://github.com/Chassis/Chassis/wiki/Accessing-Chassis-on-other-devices-for-testing-purposes to get to this point, so that seems to be broken too.

**Comment by rmccue** [comment]
We don't use port forwarding, just private networking, which is why Vagrant doesn't use it. Vagrant is actually meant to be able to detect port 80 on private networking, but the support for it is broken, and unfortunately it's not open source: https://github.com/hashicorp/vagrant/issues/8766

You can still get it working; I believe @BronsonQuick is writing up some instructions :)

**Comment by BronsonQuick** [comment]
@joehoyle I've add some docs to a new [PR](https://github.com/Chassis/Chassis/pull/466). Could you have a go at following through those and let me know if that works for you please? Thanks!

I've also deleted the Wiki page you linked to seeing I hadn't updated that since 2014 😱

**Comment by BronsonQuick** [comment]
P.S. The docs have been generated now so they are nicer to read here: http://docs.chassis.io/en/latest/guides/#vagrant-share

**Comment by BronsonQuick** [comment]
Based on a Slack convo we can close this! :shipit:
