### ISSUE TITLE
Add docs for Chassis migrations

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#47]
We should add migration docs to assist with people who are new to Chassis and want to move a Chassis site from local to staging/production.

**Comment by benjaminwil** [comment]
I'm pretty new to this stuff, and might just be missing something. But after following these directions, the `wordpress.sql` file I exported still have asome relative links referencing `/vagrant/content/plugins/`, etc. and `/vagrant/wp/wp-content/`. I'm going to try and get rid of them manually now. But hopefully if and when docs get created (and I'd love to help!) it can address this?

**Comment by tidalvirus** [comment]
It would be great if the documentation could include help on this front too, yes. :)

I've not tried it, but would a wp search-replace work on these entries in the DB with these as the path?

e.g. change /vagrant/content to /directory/wp/wp-content, and same for /vagrant/wp to /directory/wp?

**Comment by benjaminwil** [comment]
Yeah, it did!

**Comment by adeluccar** [comment]
+1 I'm dealing with this problem right now. I want to use Chassis as a starting point for my sites.

**Comment by stuartshields** [comment]
Insert witty 🍆  to get @BronsonQuick to work on this ticket.

**Comment by ntwb** [comment]
@adeluccar The steps in https://github.com/Chassis/Chassis/issues/47#issuecomment-38126683 here should cover what is needed, is there something there that did not work for you ?

**Comment by stuartshields** [comment]
@ntwb I think it's more so with updating the documentation for this ticket.

**Comment by indietravel** [comment]
I'm working on a local bash script using a $project and $repo variable to quick-start projects. Helpful?

**Comment by BronsonQuick** [comment]
@indietravel That sounds awesome! I'd love to see it when you're done!
