### ISSUE TITLE
Can't Login to WP

### ISSUE THREAD

**Issue by eridu-origin** [Chassis/Chassis#486]
Wordpress launches but it is not possible to enter the Administration. A URL like http://vagrant.local/login/ just loops back to Home page.

1. What operating system do you use? MacOSX

2. What version of Vagrant are you running? Vagrant 2.0.1

3. Are you using VirtualBox or VMWare and which version are you using? 5.2.4r119785

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file) No customizations

5. Do you have any Chassis extensions installed? If so, what are they? Only "Example"

**Comment by eridu-origin** [comment]
Wordpress launches but it is not possible to enter the Administration. A URL like http://vagrant.local/login/ just loops back to Home page.

**Comment by BronsonQuick** [comment]
Hey @eridu-origin try http://vagrant.local/wp/wp-admin for the login.

**Comment by devjack** [comment]
@eridu-origin I had a similar issue just yesterday on exactly the same version combination/env. I also found vagrant ssh failed to connect (rather `vagrant ssh --debug` would establish a connection and then fail to complete a handshake). I'm curious are you experiencing _only_ wp-admin issues or also ssh?

**Comment by eridu-origin** [comment]
http://vagrant.local/wp/wp-admin works perfectly, Thanx!

Could be a worthwhile documentation enhancement
