### ISSUE TITLE
Add offline documentation to Dash

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#517]
I've been catching up on some [LoopConf](https://www.youtube.com/channel/UCAwOVsWiMdlz6snWRF2HdSQ) talks and one of those talks was [Zen Mode](https://www.youtube.com/watch?v=q93YcVryNYU) and during that @johnbillion talks about Dash. I use Dash a lot while I'm travelling and when I'm offline so I think it would be worth seeing if we can add this to Chassis.

Currently we use [Sphinx](http://www.sphinx-doc.org/en/master/) for our docs and from the looks of it we should be able to add support for Dash with [doc2dash](https://github.com/hynek/doc2dash).

**Comment by johnbillion** [comment]
This might be helpful: https://github.com/wp-cli/dash-docset-generator

**Comment by BronsonQuick** [comment]
I've added a Pull Request upstream to get this into Dash: https://github.com/Kapeli/Dash-User-Contributions/pull/2503
