### ISSUE TITLE
Unable to provision a Multisite

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#520]
When attempting to provision a site with `Multisite: Yes` in the config, the following error occurs:

```
$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /sites/sun/Vagrantfile
Line number: 81
Message: TypeError: no implicit conversion of nil into String
```

1. What operating system do you use?
macOS 10.12.6

2. What version of Vagrant are you running?
1.9.2

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox 5.1.14

4. Do you have a custom YAML file? If so, what does it contain?
See above

5. Do you have any Chassis extensions installed? If so, what are they?
None

**Comment by fklein-lu** [comment]
After spending quite some time trying to provision a path based multisite install with a custom content directory and WordPress in a sub-directory, I can confidently say that this reliably fails.

This is the `config.local.yaml`:
```yaml
paths:
    base: ..
    content: content
    wp: wordpress
multisite: Yes
```

And this is the bash script used to setup the project, and with that Chassis:
```bash
#!/bin/bash
# Fail on any error (and yes, I know this not perfect).
set -e

# Create a local wp-config file if we need it.
if [[ ! -f wp-config-local.php ]]; then
    cp wp-config-local-sample.php wp-config-local.php
fi

# Clone down Chassis if we need to.
if [[ ! -d chassis ]]; then
    echo "Grabbing Chassis..."
    git clone --progress --recursive git@github.com:Chassis/Chassis.git chassis

    # Set up Chassis configuration.
    cp .config/config.local.yaml chassis/config.local.yaml

# If Chassis is set up...
elif [[ -d chassis ]] && [[ -f chassis/config.local.yaml ]]; then

    # Check if our config has changed.
    if [[ $(echo -n "$(cat chassis/config.local.yaml)") != $(echo -n "$(cat .config/config.local.yaml)") ]]; then

        # If the config has changed, ask if we want to use the changes.
        UPDATE_CONFIG=$(ask "Chassis config changes detected. Update config and provision?")
        if [[ ! -z $UPDATE_CONFIG ]]; then
            echo "Updating config and then provision..."
            cp .config/config.local.yaml chassis/config.local.yaml
            cd chassis
            vagrant provision
            cd ..
        fi
    fi
fi

# Start the machine.
echo "Starting Chassis..."
cd chassis
export VAGRANT_CWD=./
vagrant --color up | sed -e "s/^/${CMD_START}[vagrant]${CMD_END} /"
cd ../

```

**Comment by BronsonQuick** [comment]
@fklein-lu I'll try and replicate this later tonight for you. Just a quick question, were you altering the paths at all? The paths will only update with a `vagrant reload` and sometimes that catches people out.

**Comment by BronsonQuick** [comment]
@fklein-lu I think it's a configuration issue for you. You'll probably want something like the following in your `wordpress/wp-config.php` file:
```
<?php

/**
 * The base configurations of the WordPress.
 *
 * This file has the following configurations: MySQL settings, Table Prefix,
 * Secret Keys, WordPress Language, and ABSPATH. You can find more information
 * by visiting {@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} Codex page. You can get the MySQL settings from your web host.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to "wp-config.php" and fill in the values.
 *
 * @package WordPress
 */

// sane default for wp-cli etc
if ( ! isset( $_SERVER['HTTP_HOST'] ) ) {
	$_SERVER['HTTP_HOST'] = '';
}

/**
 * Don't edit this file directly, instead, create a local-config.php file and add your database
 * settings and defines in there. This file contains the production settings
 */
if ( file_exists( '/vagrant/local-config-db.php' ) ) {
	// Chassis mode
	include '/vagrant/local-config-db.php';

	if ( file_exists( '/vagrant/local-config-extensions.php' ) ) {
		include '/vagrant/local-config-extensions.php';
	}
	defined( 'WP_DEBUG' ) or define( 'WP_DEBUG', true );
	defined( 'SAVEQUERIES' ) or define( 'SAVEQUERIES', true );

	// We also load wp-config-local.php, just in case.
}

if ( file_exists( dirname( __FILE__ ) . '/wp-config-local.php' ) ) {
	include dirname( __FILE__ ) . '/wp-config-local.php';
	defined( 'WP_DEBUG' ) or define( 'WP_DEBUG', true );
	defined( 'SAVEQUERIES' ) or define( 'SAVEQUERIES', true );

}

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each a unique
 * prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_';

/**
 * WordPress Localized Language, defaults to English.
 *
 * Change this to localize WordPress. A corresponding MO file for the chosen
 * language must be installed to wp-content/languages. For example, install
 * de_DE.mo to wp-content/languages and set WPLANG to 'de_DE' to enable German
 * language support.
 */
define( 'WPLANG', '' );

define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', 'utf8mb4_unicode_ci' );

// Load configuration.
require_once __DIR__ . '/.config/load.php';

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', dirname( __FILE__ ) . '/wordpress/' );
}

/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );

```

If you're using HM's hosting you'll need some additional logic in it to load `wp-config-production.php` and `/var/cloudformation-vars.php` from memory too but the HM team will be able to help you with that.

Without seeing your config files I can't really guess much more. Someone in #dev-chassis in the HM Slack should be able to assist you further and you can provide more sensitive config info there.

**Comment by BronsonQuick** [comment]
I should've mentioned too that a good place to find out more detail on provisioning errors is `logs/php` of they should be in `content/debug.log` if you have `WP_DEBUG` and `WP_DEBUG` set to `true`.

**Comment by BronsonQuick** [comment]
I have a hunch that this might work now because of https://github.com/Chassis/Chassis/pull/692 but I don't have a VMWare licence anymore to test it. @roborourke or @rmccue reckon you could grab HM's licence for VMWare and test this for me please? 🙇‍♂️

**Comment by BronsonQuick** [comment]
@roborourke I'm thinking we should build a VMWare version as well. Are you or any of the HM team using it? If so can you please get one of them to generate a base box using VMWare please? I think I added you to the Vagrant Cloud Chassis organisation so you should be able to generate an API key to upload the base box.. If not then ping me and I'll do that! Taa muchly

**Comment by BronsonQuick** [comment]
Seeing multisite is working I'm going to close this issue and I've opened a new one here: https://github.com/Chassis/Chassis/issues/728
