### ISSUE TITLE
Incompatible character encodings

### ISSUE THREAD

**Issue by jotazzu** [Chassis/Chassis#524]
1. What operating system do you use?
Win 10, Creators Fall Update
2. What version of Vagrant are you running?
vagrant 2.1.1
3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

5. Do you have any Chassis extensions installed? If so, what are they?
No. Just the first install.

Started 'vagrant up'. The download of the "Base box 'bento/ubuntu-16.04'..." was interrupted once, and with the next try continued successfully.

Then I got the following error output which repeats when calling 'vagrant up' again (see attached file, too)

E:\Develop\Chassis WP>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-16.04'...
C:/Vagrant/embedded/gems/2.1.1/gems/childprocess-0.6.3/lib/childprocess/windows/process_builder.rb:43:in `join': incompatible character encodings: Windows-1252 and UTF-8 (Encoding::CompatibilityError)
         ...

[Chassis_Vagrant_Install_Error.txt](https://github.com/Chassis/Chassis/files/1997618/Chassis_Vagrant_Install_Error.txt)

**Comment by jotazzu** [comment]
I get the same error when installing 'Varying Vagrant Vagrants' v2.1.0 https://github.com/Varying-Vagrant-Vagrants/VVV

**Comment by BronsonQuick** [comment]
I'm going to close this issue out for now. Feel free to open it again if you have any more information. Thanks!
