### ISSUE TITLE
Question on how to set up Chassis with WordPress and standalone PHP code

### ISSUE THREAD

**Issue by RoseanneD** [Chassis/Chassis#527]
I am working on getting a project set up in Chassis. So I can add the wp-content folder to a repo and that part is fine - I'll have the wordpress installation locally

However on the site I have a subdomain called admin. This has php forms where I can enter data and this is stored in a separate database (not in the wordpress db). Then on the site, we have some custom templates where the data from the standalone database is pulled to create dynamic pages. In case it helps to have more context - the standalone db stores data about students that the charity supports and also about wells they have installed. Then on the wordpress site a page is generated about each student/well.

At the moment I have a repo with just a handful of the wordpress files (mainly template files for the pages that get generated for each student/well). I could add the full wp-content folder in there..

I have a separate repo for the admin part. It has a number of top level folders like wells, education etc. I could possibly add the wp-content folder there either.

But how can I get this to work with standalone code - what would the folder structure look like if this is even possible with Chassis? For the database I see there is the phpmyadmin extension so setting up the standalone db should be fine - it's just the code. The reason I want to set this up is that I wll have a number of volunteers working on it in a few days and I want to make the setup as quick/easy as possible. Any help hugely appreciated. And if it is something that is just not suitable with Chassis please let me know that too.

**Comment by BronsonQuick** [comment]
Hey @RoseanneD, sorry for the delay! I've been on holidays interstate.

I _think_ this kind of a setup should be possible but I believe it'll require a custom Chassis extension to handle some rewrite rules in Nginx. It'll need something similar to this extension: https://github.com/grappler/chassis-custom-rewrites however the [rewrites](https://github.com/grappler/chassis-custom-rewrites/blob/master/modules/custom-rewrites/templates/site.nginx.conf.erb) would need to be different for subdomains. So you could have `http://admin.vagrant.local` point to an `admin` folder in the root directory.

If you haven't already found an alternative setup for your project I could probably find some time next week to experiment creating a new Chassis extension for you to see if it's possible?

**Comment by RoseanneD** [comment]
Thank you very much for the reply.  I went with VVV in the end. Seemed to
fit what I needed better with having a wordpress site and a non wordpress
one.

Thank you,
Roseanne

**Comment by BronsonQuick** [comment]
Hey @RoseanneD, I'm glad VVV suited your project!

I'll close this issue now and remember to suggest VVV if anyone else needs a similar setup in the future. Thanks for letting me know!
