### ISSUE TITLE
Unable to provision 

### ISSUE THREAD

**Issue by spacedmonkey** [Chassis/Chassis#528]
1. What operating system do you use?

Ubuntu 16.04. 

2. What version of Vagrant are you running?

2.1.1

3. Are you using VirtualBox or VMWare and which version are you using?

VirtualBox 5.1.34_Ubuntu r121010

4. Do you have a custom YAML file? If so, what does it contain?
No custom YAML

5. Do you have any Chassis extensions installed? If so, what are they?
No extensions 

I get the following errors when trying to provision. 

```
    default: Reading package lists...
    default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
    default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
    default: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
    default: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
    default: W: Some index files failed to download. They have been ignored, or old ones used instead.
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: E
    default: : 
    default: Unable to locate package puppet
==> default: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.
```

Seems like puppet isn't running and this just exists outs. I can give more detail if required.

**Comment by rmccue** [comment]
Seems like a possible DNS resolution error. Can you access http://archive.ubuntu.com/ in a browser?

**Comment by spacedmonkey** [comment]
I can access it in the url. I sshed into the box and pinged google and got this.

```
vagrant@vagrant:~$ ping www.google.com
ping: unknown host www.google.com
```

**Comment by spacedmonkey** [comment]
Run and no luck. 
I run it a couple of times, just see and never worked. Tried with and without Sudo. See attached the output from console. 
[output.txt](https://github.com/Chassis/Chassis/files/2133011/output.txt)

I personally think it is a issue with Ubuntu.

**Comment by spacedmonkey** [comment]
If it helps, I am going to be reinstalling my laptop to ubuntu 18.04 sometime in the next week, so I will try and again and report back.

**Comment by BronsonQuick** [comment]
@spacedmonkey That'd be awesome thanks! I have 14.04 on an old dual boot laptop here. I'll fire it up and bump it up to 16.04 to see if I can replicate it too.

**Comment by BronsonQuick** [comment]
Hey @spacedmonkey, I just installed a fresh Ubuntu 16.04 distribution one of my laptops and installed VirtualBox 5.1.34_Ubuntu r121010 and Vagrant 2.1.1 and the installation worked fine for me. I did have to run `vagrant reload` after my first `vagrant up` to get the shared folders working. I've attached a file with the terminal output so you can see how it went for me.

Hopefully a fresh install works for you too!
[chassis-ubuntu-1604.txt](https://github.com/Chassis/Chassis/files/2135785/chassis-ubuntu-1604.txt)

**Comment by BronsonQuick** [comment]
I just decided to update to Bionic Beaver (18.04) just to check everything works fine with that as well and it does.

**Comment by BronsonQuick** [comment]
I'm going to close this out for now. Feel free to open it again if you encounter this issue again.
