### ISSUE TITLE
Add Xdebug extension

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#53]
Now that we have `extensions` we should remove Xdebug from the base box and create an extension https://github.com/Chassis/Xdebug

**Comment by aendrew** [comment]
What needs to be done to move this forward? It's over a year later and I desperately need xdebug support right now...

**Comment by franz-josef-kaiser** [comment]
@aendrew See related issues for instructions for a manual install.

**Comment by aendrew** [comment]
@franz-josef-kaiser Totally didn't look at those issues. Many thanks!

**Comment by BronsonQuick** [comment]
I made a Chassis extension that works with PHP 5.6. https://github.com/Chassis/Xdebug
