### ISSUE TITLE
Autoinstall extensions from Git

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#55]
We should allow specifying an `extensions` option in config.yaml that will autoinstall extensions correctly.

```yaml
# Autoinstall the following extensions
# (Note that all directories in extensions will be loaded; this is only for initial provisioning)
extensions:
  memcache: Chassis/memcache # mapped to https://github.com/Chassis/memcache.git
  xhprof: https://github.com/Chassis/xhprof.git
```

**Comment by shadyvb** [comment]
@rmccue I've pinged @BronsonQuick about something similar on Slack, regarding the ability to choose extensions ( from a pre-defined list ) as part of the provisioning process.. not sure if we can get it to work in the correct timing though, probably through custom Vagrant scripting.

**Comment by shadyvb** [comment]
One question here would be how to provide a way for people to register their extensions to be displayed in this process, probably through a yaml file and PRs to this repo.

**Comment by shadyvb** [comment]
Answering my own question, we can list the repos as `Chassis/something` which eliminates the need to pre-register extensions. props @rmccue

**Comment by rmccue** [comment]
Ideally, I'd like to support both `username/repo` which maps to GH, and full git URLs as well.
