### ISSUE TITLE
Make PHP ini file configuration part of core

### ISSUE THREAD

**Issue by roborourke** [Chassis/Chassis#551]
The extension over at https://github.com/Chassis/phpini is really useful, but I think given that PHP is provisioned and part of the core chassis set up it might make sense to bake that functionality in.

It'd be awesome to be able to do this via config too to reduce the number of dev specific committed files and allow local overrides eg:

```yaml
php-ini:
  memory_limit: 256M
```

**Comment by rmccue** [comment]
I'd still prefer to keep it as a separate extension unless there's some compelling reason to include it in Chassis itself. I don't think the majority of users are going to need this functionality, and the extension is easy enough to add (it's one extra line in your config).

Adding this stuff to the config makes sense though, and should be possible to do with the extension already.

**Comment by roborourke** [comment]
To be fair 128Mb is usually enough and means you can have more concurrent processes on a box, it's generally better for performance. When you get to some of the more complex edge cases like working with large amounts of binary data you may need to tweak those settings and it should be as easy as possible. Obviously in an ideal world we find ways of handling things that free up memory as they go so code is as portable as possible but that's not always possible.

> I'd still prefer to keep it as a separate extension unless there's some compelling reason to include it in Chassis itself.

With regards to including this in Chassis itself my thinking was that it would be neater to handle PHP setup & configuration in one place as all the version handling is pretty complex and has to be repeated in any extensions that need to install php modules or add config files. It's also less overhead for devs who find they need to test with and make such modifications.

It would also simplify building extensions that add specific PHP modules as the extension's `chassis.yaml` file could just be used to extend the PHP extensions list and override default ini settings. For example the xdebug & memcache extensions could be simplified a fair amount this way.

Last issue is I know the referenced PR goes beyond the scope of this issue a bit by including PHP extension support. I've definitely worked on a few projects where I've needed a couple of non-standard libraries for example internationalisation, SOAP and LDAP that we've made available in production. Writing an extension just for a specific project and replicating the PHP version logic seems like overkill.

**Comment by rmccue** [comment]
The version logic motivation makes sense, but I wonder whether we could actually simplify that, as the packages have changed since we originally wrote that. (IIRC, nothing <5.6 is supported or available any more anyway.)

In any case, we should be able to provide Puppet resources in Chassis that extensions can use to simplify this. I'm not sure how extensions would use this config anyway, as extensions can't add items to the user-specified configuration?

I'm also OK with adding PHP extensions to the configuration, given we already have a list of them that we need to install, so that code is already there. I don't want to add arbitrary php.ini support though.

**Comment by rmccue** [comment]
> (IIRC, nothing <5.6 is supported or available any more anyway.)

In fact, @BronsonQuick just merged this in #534, which has simplified the handling in `php.pp`.

**Comment by roborourke** [comment]
Oh neat. Fair enough then, can improve the phpini extension a bit instead.

I think I got the idea that the extension's `chassis.yaml` was rolled into the overall config for some reason. My mistake there.

I'll update my PR to just add a `php_extensions` key.

**Comment by BronsonQuick** [comment]
I'll close this one now as you folks look like you came to an agreeance that we'll keep this in the extension.
