### ISSUE TITLE
Set DB_CHARSET and DB_COLLATE

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/Chassis#554]
In its wp-config.php, Chassis sets:

`
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );
`

Can we get these, at the very least, wrapped in `defined()` checks so we can override them in `local-config.php` etc, and/or the defaults changed to match WordPress core's defaults (`utf8mb4` and `utf8mb4_unicode_ci`).

**Comment by ntwb** [comment]
@paulgibbs via https://github.com/Chassis/Chassis/pull/530#issuecomment-399658476

> "The optimal combination is `utf8mb4` for the charset and `utf8mb4_unicode_520_ci`, which are both triggered by just setting `DB_CHARSET` to `utf8` and not setting `DB_COLLATE` (same as currently set up)."
