### ISSUE TITLE
Warn the user if they use a domain other than `.local`

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#571]
As a user I should get a warning if I've tried to use a domain other than `.local`

**Comment by johnbillion** [comment]
Is there a reason Chassis requires the use of the `.local` TLD? Using `.test` is common now too.

**Comment by BronsonQuick** [comment]
@johnbillion Yeah we use that so we can use Avahi to automatically resolve the DNS so you don't have to edit your hosts file and/or use something like the Vagrant Hostsupdater plugin.

**Comment by rmccue** [comment]
Specifically: `.local` is the TLD for [multicast DNS](https://tools.ietf.org/html/rfc6762), which is what we use to resolve names (Avahi as the server on Ubuntu, Bonjour as the client on macOS). While this can be customised per network, it requires every client and server to be reconfigured, so it would be a total pain to set up.

(Also: we're using `.local` specifically as the specification provides, and for the purpose of the spec, so we don't need to use test or example TLDs.)
