### ISSUE TITLE
Disable PHP short tags in ini

### ISSUE THREAD

**Issue by pdewouters** [Chassis/Chassis#572]
1. What operating system do you use?

MAC OS

2. What version of Vagrant are you running?

2.1.2

3. Are you using VirtualBox or VMWare and which version are you using?
VBox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

5. Do you have any Chassis extensions installed? If so, what are they?
xdebug

PHP attempts to parse svg files as PHP code because they start with `<? xml...` and `short_open_tag` is set to `On` in the default `php.ini`

So in a statement such as `require_once get_template_directory() . '/assets/images/search.svg';` this will cause a parsing error

`[31-Aug-2018 14:01:39 UTC] PHP Parse error:  syntax error, unexpected 'version' (T_STRING) in /chassis/content/themes/yell/assets/images/search.svg on line 1`

As a fix I suggest setting this to `Off`

**Comment by BronsonQuick** [comment]
Good catch @pdewouters! I've done a quick PR for this and it's awaiting review.
