### ISSUE TITLE
Vagrantfile:25: warning: already initialized constant CONF

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#577]
Currently I see these warnings whenever I run any `vagrant *` commands.
```
/Volumes/Sites/sitedemo/Vagrantfile:25: warning: already initialized constant CONF
/Volumes/Sites/sitedemo/Vagrantfile:25: warning: previous definition of CONF was here
```

1. What operating system do you use?
MacOS High Sierra

2. What version of Vagrant are you running?
2.1.4.

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 5.2.18r124319

5. Do you have any Chassis extensions installed? If so, what are they?
- Mailhog
- Xdebug

**Comment by mikeselander** [comment]
I get the same errors, with a multitude of configurations/sites & with and without extensions.

**Comment by BronsonQuick** [comment]
I'm gonna close this for now as per https://github.com/Chassis/Chassis/pull/578#issuecomment-471932890
