### ISSUE TITLE
Update Apt automatically

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#582]
As a developer, my apt packages should update frequently otherwise I run the risk of bumping a PHP version in my configuration file and I can get a failed provision.

I have had code for this here: https://github.com/Chassis/Chassis/pull/476/files#diff-556e699d648d31f209eec94844939770R15 it's important that we ship this for developers.

**Comment by johnbillion** [comment]
I just ran into this exact issue when attempting to install an extension on an existing box. The extension's Debian package returned a `404`. Turns out I had to run `sudo apt-get update`.

**Comment by rmccue** [comment]
IMO, best way to fix this is to add into the preprovision.sh. Rather than just checking whether the did-update file exists, we should write a timestamp into it, and check that isn't older than ~2 weeks (or something; if there's a better period to use, let's do that).

**Comment by BronsonQuick** [comment]
Hah it's interesting that you suggested the time stamp. I was actually thinking I should touch a file and add a timestamp for my auto updates branch so it only runs once a week. I'll think about making that approach reusable here as well!

**Comment by rmccue** [comment]
👍 Only potential issue might be that the apt updates run inside the machine, whereas the others have to run outside the machine (in case there's private repos or anything).

**Comment by BronsonQuick** [comment]
Ahh yeah. Good point! 🍆

**Comment by BronsonQuick** [comment]
I've handled this in another PR: https://github.com/Chassis/Chassis/pull/476/files#diff-ebb1484b5498abe97a80e94aac9365cdR17

**Comment by rmccue** [comment]
This was alas not fixed by #476, and now that we have a basebox, the issue is popping up on initial provisions too. #720 will fix that temporarily, but IMO we should consider the time-based fix instead.
