### ISSUE TITLE
Increase nginx's proxy timeout

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#585]
When stepping through breakpoints in PHP, the proxy timeout often gets hit, causing nginx to respond with a 504.

It would be great if the default proxy timeout was significantly increased in order to avoid this problem.

**Comment by BronsonQuick** [comment]
Good call! Do you think we should increase `proxy_connect_timeout`, `proxy_send_timeout` or `proxy_read_timeout` or all of them to fix this?

**Comment by johnbillion** [comment]
Off the top of my head I'm not sure which directive controls this timeout.

**Comment by BronsonQuick** [comment]
@johnbillion Sorry for the massive delay on this. I don't know how to replicate this but I'm guessing maybe you were using Charles Proxy perhaps and you hit this? I've had a crack at adding some additional nginx settings for proxies. Can you please test out https://github.com/Chassis/Chassis/pull/614 for me and let me know if that fixes it? Taa muchly! 💖
