### ISSUE TITLE
Support Dictator

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#59]
Now we've got Puppet extensions working the next challenge is maintaining state. Daniel's had two passes at the readme for Dictator and has a [blog post](https://github.com/danielbachhuber/dictator/issues/23) on the way so I'd like us to have a play around with implementing it into Chassis.

**Comment by BronsonQuick** [comment]
Related: https://github.com/Chassis/Chassis/issues/151#issuecomment-257838482

**Comment by rmccue** [comment]
Closing this out; if it happens, it happens, but otherwise no need to have it open here. :)
