### ISSUE TITLE
Vagrant share not working and loads the default Nginx root with latest versions

### ISSUE THREAD

**Issue by chadaort** [Chassis/Chassis#595]
I have not been able to get Ngrok (2.2.8) domains to resolve after updating Vagrant and VB to the latest versions using Vagrant share. It always resolves to the default Nginx root and not the custom local domain. I’ve tried `reload` after `provision` didn’t work and have brought the machine up and down with no success. 

1. What operating system do you use?
Mac High Sierra

2. What version of Vagrant are you running?
2.2.2

3. Are you using VirtualBox or VMWare and which version are you using?
Virtual Box - Version 5.2.22 r126460 (Qt5.6.3)

4. Do you have a custom YAML file? If so, what does it contain?
[config.local.yaml.zip](https://github.com/Chassis/Chassis/files/2713215/config.local.yaml.zip)

5. Do you have any Chassis extensions installed? If so, what are they?
Cavalcade, Memcache, SequalPro, Tester, Xdebug

**Comment by BronsonQuick** [comment]
Hey @chadaort, thanks for the bug report. I hadn't used Vagrant Share in Chassis for a while so I wasn't aware that it had broken at some point!

Could you please checkout https://github.com/Chassis/Chassis/pull/597 and test that to see if it starts working again for you and let me know how you go? That fix worked for me on the latest versions of Vagrant, VirtualBox and Ngrok. http://docs.chassis.io/en/latest/guides/#vagrant-share

Thanks!

**Comment by chadaort** [comment]
@BronsonQuick - Sorry for the slow response, but I finally found time to update locally and this is working great. Appreciate the quick response!
