### ISSUE TITLE
Support MariaDB

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#60]
Currently, we only support MySQL. It'd be nice to support MariaDB as well, as it seems like there's significant movement towards it and they just [pumped out a new release](https://blog.mariadb.org/the-mariadb-foundation-announces-general-availability-of-mariadb-10/).

Sounds like it's as easy as `apt-get install mariadb-server`, aka:

``` puppet
package { 'mariadb-server':
    ensure => latest
}
```

Relevant:
- [Moving from MySQL](https://mariadb.com/kb/en/moving-from-mysql/)
- [Compatibility](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/)
- [Puppet and MariaDB](https://mariadb.com/kb/en/puppet-and-mariadb/)

**Comment by tikot** [comment]
+1 for the MariaDB. It's worth it

**Comment by johnbillion** [comment]
VIP Go uses MariaDB, so it would be good to have this as an option in Chassis.

**Comment by BronsonQuick** [comment]
So it took me over 3 years to find time to do this. I had a few goes in the past at sorting this out and failed miserably. This afternoon I rethought how we can handle this and I've made this extension: https://github.com/Chassis/MariaDB 

That extension won't work until https://github.com/Chassis/Chassis/issues/445 is merged though.

**Comment by BronsonQuick** [comment]
I finally got back to having another play around with this and got it working! https://github.com/chassis/mariadb 🚀
