### ISSUE TITLE
PHP 7.3 doesn't appear to work

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#604]
When specifying PHP 7.3 in the config file for a brand new project, everything appears to install correctly but the site ends up not being available and displays a 502 Bad Gateway error message. It looks like php-fpm might not be running.

Switching to PHP 7.2 works as expected.

**Comment by BronsonQuick** [comment]
I can't replicate this with a default install and altering the version to 7.3.

<img width="1440" alt="chassis_site__just_another_wordpress_site_2019-01-22_12-17-20" src="https://user-images.githubusercontent.com/1377956/51508145-c2b62280-1e3f-11e9-9966-5d858e3fa436.png">
<img width="1440" alt="php_7 3 1-1ubuntu16 04 1deb sury org1_-_phpinfo_2019-01-22_12-17-48" src="https://user-images.githubusercontent.com/1377956/51508162-da8da680-1e3f-11e9-96c3-106d234f7870.png">

What extensions and/or plugins are you using? Can you please supply me with your custom yaml file? Thanks!

**Comment by BronsonQuick** [comment]
Thanks @johnbillion. I can replicate it with that configuration. I'll start debugging it for you now!

**Comment by BronsonQuick** [comment]
@johnbillion After some debugging I've tracked it down to the Xdebug extension and opened a ticket [here](https://github.com/Chassis/Xdebug/issues/49) to track it. Hopefully I can fix it up for you this afternoon. I'll close this issue as it's not related to Chassis core.
