### ISSUE TITLE
404 Not Found after running vagrant resume

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#607]
<img width="1438" alt="404_not_found_2019-02-08_12-52-43" src="https://user-images.githubusercontent.com/1377956/52456444-835a3680-2ba0-11e9-9cb7-8bfa15f823c1.png">

# Steps to replicate:
1. Boot up a Chassis box.
2. Run `vagrant suspend`.
3. Reboot your machine.
4. Run `vagrant resume`.

# Current workaround
1. Run `vagrant reload`.

**Comment by BronsonQuick** [comment]
From the looks of it I think it's because the shared folders aren't remounting when you run `vagrant resume`

**Comment by BronsonQuick** [comment]
This is from the Vagrant docs:
>Synced folders are automatically setup during `vagrant up` and `vagrant reload`.

**Comment by BronsonQuick** [comment]
@kucrut I'm gonna close this one out as it's by design in Vagrant. You'll either have to do `vagrant halt` then `vagrant up` or `vagrant suspend` then `vagrant resume && vagrant reload` to make sure the shared folders are mounted.

The only other way I can think of "fixing" it would be to write a vagrant plugin just for you to remount the folders when you run `vagrant resume` but it's a lot of effort!

**Comment by kucrut** [comment]
Thanks for looking into this. Don't worry about it, I can do halt + up.

**Comment by BronsonQuick** [comment]
No probs Sir! BQ always looks into code related things. I'd still love to know the rationale for not remounting folders on `vagrant resume` as I can't think of a logical reason for it.

**Comment by rmccue** [comment]
Note that this only occurs because of the reboot. `vagrant suspend` then `vagrant resume` does maintain the shared folders, it's only when you reboot that they unmount.

I suspect that `vagrant resume` doesn't try to remount the folders because it assumes there's no reason they'd be unmounted. Basically, I think this is a bug in Vagrant rather than intended behaviour.

**Comment by BronsonQuick** [comment]
@rmccue in that case do you think I should report this upstream in Vagrant to see what they say?

**Comment by rmccue** [comment]
Might be a good idea yeah!
