### ISSUE TITLE
Consider adding global extension installation information to frequently used extensions

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#619]
Every developer has a different workflow and we all have our preferred extensions. I know most of the time I will need to have the following extensions:
```
  - chassis/xdebug
  - chassis/mailhog
  - chassis/composer
  - chassis/sequelpro
```
So it might be worth updating the readmes like
@rmccue did here https://github.com/Chassis/SequelPro/pull/8/files#diff-04c6e90faac2675aa89e2176d2eec7d8R8

**Comment by rmccue** [comment]
👍 for these dev tools things, I'd say we recommend installing them globally.

I wouldn't do that for `chassis/composer` though, as that might be an actual requirement of a project's install script.

**Comment by BronsonQuick** [comment]
I've opened issues in the extensions for those updates so I'll close this issue now.
