### ISSUE TITLE
Whitescreen via IPv6

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#622]
After some very strange debugging with @missjwo, I managed to crack why she's seeing a whitescreen in Firefox but not Chrome: Firefox uses IPv6, whereas Chrome uses IPv4.

As it turns out, nginx is failing to match based on the `listen 80` directive. This doesn't match IPv6 ports.

We need to update our site config to add `listen [::]:80` as well, per https://serverfault.com/questions/638367/do-you-need-separate-ipv4-and-ipv6-listen-directives-in-nginx

**Comment by BronsonQuick** [comment]
@rmccue Could this maybe fix https://github.com/Chassis/Chassis/issues/417 as well?

**Comment by BronsonQuick** [comment]
@rmccue Sorry dude. I was going through my inbox from top down rather than bottom up so I saw you cross referenced it. 🤦‍♂️
