### ISSUE TITLE
Manually set machine name if the name is too generic

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#628]
Vagrant sets the [name](https://www.vagrantup.com/docs/virtualbox/configuration.html#virtual-machine-name) of the machine to the directory name + timestamp by default. This isn't useful if the directory name is generic though, so we should detect this and set it manually.

IMO, we should set it to the parent directory's name if the directory name is one of:
* `chassis`
* `vagrant`

Any others? (Related: #404.)

**Comment by roborourke** [comment]
Could possibly allow setting the name via the `config.yaml` too.

Rather than assume the parent directory I think it'd be better to look at the `paths.base` value and take that directory name. If it's still `chassis` or `vagrant` then underscore separate the absolute path on disk? Eg. `/Users/bob/chassis` becomes `users_bob_chassis`.

Maybe even just do the latter.

**Comment by BronsonQuick** [comment]
After some messing around in a multi VM situation we need to do `config.vm.define` and `vb.name` will give it a name in the VirtualBox GUI. I did a quick and dodgy start on this and I pushed some work in progress so if either of you wanna pick it up then feel free to. I might get back to it on the weekend.

**Comment by rmccue** [comment]
> Rather than assume the parent directory I think it'd be better to look at the `paths.base` value and take that directory name. If it's still `chassis` or `vagrant` then underscore separate the absolute path on disk? Eg. `/Users/bob/chassis` becomes `users_bob_chassis`.

I think that's going to be quite long; I'd have `users_rmccue_work_human made_hmn.md_chassis-hmnlocal` for example. IMO, just the directory name should do.

**Comment by roborourke** [comment]
Playing with this a bit there's a challenge in terms of backwards compatibility. It's a breaking change if the expected VM name suddenly changes so it might just be best to leave it as the default unless the `machine_name` is set in the config.

**Comment by BronsonQuick** [comment]
Alternatively we change https://github.com/Chassis/Chassis/pull/633/files#diff-259fe82e12a866f01123927480c7851bR111 to be `machine_name: default` and add an example name in the comment on the line above?

**Comment by roborourke** [comment]
Agreed - in terms of backwards compat we should only use something other than `default` if explicitly defined in the config.

**Comment by roborourke** [comment]
Alrighty - done & documented!

**Comment by BronsonQuick** [comment]
Oopphhh! Nice one @roborourke 🍆
