### ISSUE TITLE
Provide helpful feedback or debugging steps when packages fail to install

### ISSUE THREAD

**Issue by johnbillion** [Chassis/Chassis#639]
As a general rule, when a package from `ppa.launchpad.net` fails to install either due to network connectivity issues or due to the package not existing at all and returning a 404, the output provided to the user isn't very helpful. The problem is exacerbated due to the cascading failures, and the problem that caused provisioning to fail is usually much further back in the scroll back.

Is there a way that Chassis can provide some guidance to the user as to what debugging steps they can take if provisioning fails?

My usual approach is to start commenting out Chassis extensions and changing the PHP version number until it starts working again. Is there a better way?

**Comment by BronsonQuick** [comment]
Related: https://github.com/Chassis/Chassis/issues/612 I'm waiting on some feedback about how to start coding something up for this.

I'll just copy and paste something I mentioned in Slack in case it helps someone else if they hit this situation:
>Yeah Ryan is probs on the money about apt not updating. Try `vagrant ssh` then `sudo apt-get update` exit the box then do `vagrant provision` and hopefully shit should work

https://github.com/Chassis/Chassis/issues/582 is also related to this as well so I've reopened this.

**Comment by BronsonQuick** [comment]
I've added some info about `logs` to our documentation and I've also added the ppa update command for when we get to #612. So I'll close this off for now and tackle it there.
