### ISSUE TITLE
Vagrant Share doesn't work with ngrok after version 2.2.8

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#644]
@kadamwhite was unable to get ngrok to work on version `2.3.29`. After some debugging it seems that something is broken in ngrok so for the moment we should document that version `2.2.8` is required to work.

The ngrok archives are available here: https://dl.equinox.io/ngrok/ngrok/stable/archive

**Comment by BronsonQuick** [comment]
I've just dug into this a little more and it turns out that ngrok is working still and it's `vagrant share` that isn't outputting the URL that ngrok is generating.

Currently if I run `vagrant share --http=vagrant.local:80` then it looks like ngrok isn't working:

<img width="1440" alt="chassis__vagrant_VolumesSiteschassis__ngrok__vagrant_share_--httpvagrant local80__15841_2019-08-01_15-41-37" src="https://user-images.githubusercontent.com/1377956/62268416-2d8d8980-b473-11e9-8994-31baa9b60a18.png">

However, if I run `vagrant share --http=vagrant.local:80 --debug` then I can see the ngrok URL and I can use it as expected:

<img width="1437" alt="chassis__vagrant_VolumesSiteschassis__ngrok__vagrant_share_--httpvagrant local80_--debug__15841_2019-08-01_15-45-03" src="https://user-images.githubusercontent.com/1377956/62268495-6594cc80-b473-11e9-9ebe-0376e72ab11a.png">

<img width="1439" alt="Chassis_Site__Just_another_WordPress_site_2019-08-01_15-45-59" src="https://user-images.githubusercontent.com/1377956/62268539-80674100-b473-11e9-86ae-ea62665510d1.png">

Related: https://github.com/hashicorp/vagrant/issues/10799

**Comment by pe5er** [comment]
Looks like this is fixed properly by https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1036

Perhaps that could be merged, so that the latest ngrok binaries can be used instead of an old verison?
