### ISSUE TITLE
DirectoryIterator is not working

### ISSUE THREAD

**Issue by joeleenk** [Chassis/Chassis#656]
1. What operating system do you use?
macOS Mojave Version 10.14.5

2. What version of Vagrant are you running?
Vagrant 2.2.5

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox Version 5.2.30 r130521 (Qt5.6.3)

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
I don't have a `chassis.local.yaml` file.

5. Do you have any Chassis other extensions installed? If so, what are they?
- nodejs
- cavalcade
- composer
- npm
- chassis/tachyon
- shadyvb/chassis-redis

@joehoyle was helping me to debug my local chassis site, and had some thing for me to paste in here:

Terminal info:
```
vagrant@platform-site:~$ php -v
PHP 7.3.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 10 2019 06:54:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans
vagrant@platform-site:~$ ls -la /chassis/wordpress/
total 184
drwxrwxrwx 1 vagrant vagrant   704 Jul 30 18:02 .
drwxrwxrwx 1 vagrant vagrant  1024 Aug  1 19:10 ..
-rwxrwxrwx 1 vagrant vagrant   796 May  7 20:42 composer.json
-rwxrwxrwx 1 vagrant vagrant   420 May  7 20:42 index.php
-rwxrwxrwx 1 vagrant vagrant 19935 May  7 20:42 license.txt
-rwxrwxrwx 1 vagrant vagrant  7447 May  7 20:42 readme.html
-rwxrwxrwx 1 vagrant vagrant  6919 May  7 20:42 wp-activate.php
drwxrwxrwx 1 vagrant vagrant  2976 May  7 20:42 wp-admin
-rwxrwxrwx 1 vagrant vagrant   369 May  7 20:42 wp-blog-header.php
-rwxrwxrwx 1 vagrant vagrant  2283 May  7 20:42 wp-comments-post.php
-rwxrwxrwx 1 vagrant vagrant  2898 May  7 20:42 wp-config-sample.php
drwxrwxrwx 1 vagrant vagrant   160 May  7 20:42 wp-content
-rwxrwxrwx 1 vagrant vagrant  3847 May  7 20:42 wp-cron.php
drwxrwxrwx 1 vagrant vagrant  6528 May  7 20:42 wp-includes
-rwxrwxrwx 1 vagrant vagrant  2502 May  7 20:42 wp-links-opml.php
-rwxrwxrwx 1 vagrant vagrant  3306 May  7 20:42 wp-load.php
-rwxrwxrwx 1 vagrant vagrant 39574 May  7 20:42 wp-login.php
-rwxrwxrwx 1 vagrant vagrant  8403 May  7 20:42 wp-mail.php
-rwxrwxrwx 1 vagrant vagrant 18962 May  7 20:42 wp-settings.php
-rwxrwxrwx 1 vagrant vagrant 31085 May  7 20:42 wp-signup.php
-rwxrwxrwx 1 vagrant vagrant  4764 May  7 20:42 wp-trackback.php
-rwxrwxrwx 1 vagrant vagrant  3068 May  7 20:42 xmlrpc.php
```

PHP:
```
$iterator = new DirectoryIterator( ABSPATH );
foreach ( $iterator as $leaf ) {
	var_dump( $leaf->getPathname() );
}

exit;
```

Browser output:
```
/chassis/content/mu-plugins/test-directoryiterator.php:6:string '/chassis/wordpress/.' (length=20)
/chassis/content/mu-plugins/test-directoryiterator.php:6:string '/chassis/wordpress/..' (length=21)
```

**Comment by joehoyle** [comment]
Just to add some info `DirectoryIterator` is not finding the files as expected, seemingly only in the shared folders. `DirectoryIterator( `/tmp/` )` correctly found files in that folder, but `/chassis` did not. The permissions from @joeleenk's `ls -la /chassis/wordpress/` output all look good.

**Comment by joehoyle** [comment]
Can also confirm `glob` _was_ able to find the files correctly.

**Comment by BronsonQuick** [comment]
Does `$iterator = new DirectoryIterator( dirname( __FILE__ ) );` work by any chance? I'm guessing `ABSPATH` might not be set in `test-directoryiterator.php`

**Comment by BronsonQuick** [comment]
<img width="895" alt="vagrant local_2019-08-02_12-38-36" src="https://user-images.githubusercontent.com/1377956/62340309-7fd9b380-b522-11e9-8551-414075d2334e.png">

I can confirm that the code works with a default Chassis install.

**Comment by BronsonQuick** [comment]
Hey @joeleenk, I was wondering if you were still having issues with this or if you had any additional information for me to try and replicate it for you? Thanks!

**Comment by joeleenk** [comment]
@BronsonQuick Sorry for the inattention here, I was allocated to another project and forgot to follow up. Thanks for the reminder and for your help!

> Does `$iterator = new DirectoryIterator( dirname( __FILE__ ) );` work by any chance?

Here's the browser output from this:

```
/chassis/content/mu-plugins/test-directoryiterator.php:5:string '/chassis/content/mu-plugins/.' (length=29)
/chassis/content/mu-plugins/test-directoryiterator.php:5:string '/chassis/content/mu-plugins/..' (length=30)
```

**Comment by BronsonQuick** [comment]
@joeleenk Hrm. This is a weird one. Can you check the output of `ABSPATH` please? That might help me replicate it. Thanks!

**Comment by joeleenk** [comment]
@BronsonQuick Here you go:

```
/chassis/content/mu-plugins/test-directoryiterator.php:5:string '/chassis/wordpress/.' (length=20)
/chassis/content/mu-plugins/test-directoryiterator.php:5:string '/chassis/wordpress/..' (length=21)
```

**Comment by g4li** [comment]
This problem may occur when the version of VirtualBox guest additions is mismatching the version of VirtualBox.

**Comment by BronsonQuick** [comment]
I think I'm going to close this one based on @g4li's comment. Thanks for the info!
