### ISSUE TITLE
PUT requests appear to be rejected by nginx, breaks compatability with Multilingualpress3 caching system

### ISSUE THREAD

**Issue by pdewouters** [Chassis/Chassis#665]
Steps to reproduce:
On a chassis install, ssh in to the box
run `curl -XPUT servus.local`
Notice the output:
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

**Comment by BronsonQuick** [comment]
@pdewouters Did you have any more information on this by any chance Sir? Thanks!

**Comment by pdewouters** [comment]
no sorry, we abandoned multilingualpress on this project anyway

**Comment by BronsonQuick** [comment]
No problem. Thank you Sir. I'll close this one out!
