### ISSUE TITLE
Parent dir with - in name triggers extension renaming notice

### ISSUE THREAD

**Issue by kadamwhite** [Chassis/Chassis#689]
The check to display the "we are renaming your extensions" warning appears to trigger based on the presence of a `-` dash character anywhere within the directory path, where it really only matters if the dash occurs within the `extensions` folder tree. This is most obvious when using an extension with no dash at all, such as `xdebug`, within a Chassis root folder named with a hyphen in the folder title.

For example, I have Chassis checked out to `/wp/core-vm` for my WP development repository. When I provision, I see this error:
```
We're renaming the following extensions:
- /wp/core-vm/extensions/xdebug to /wp/core_vm/extensions/xdebug
```
No rename has occurred, nor was one needed. The `core-vm` directory part is outside of the virtual machine's awareness so it will not impact provisioning.

I believe we could improve the logic for displaying this error by excluding the Chassis root path before detecting for dashes.

System info, though I don't believe it's relevant this time:

Ubuntu 19.04, Vagrant 2.2.4, VBox 6.0.6. Custom config file specifying `chassis/xdebug` in my extensions list.

**Comment by rmccue** [comment]
Ooh, that definitely looks unintentional.
