### ISSUE TITLE
Xdebug temp work around

### ISSUE THREAD

**Issue by franz-josef-kaiser** [Chassis/Chassis#71]
As #10 and #53 currently state that `php5-xdebug` is not available and adding it to the extensions in `senzza::php` fails during the provisioning, here's a temporary work around:
1. Log into your box using `vagrant ssh`
2. Install XDdebug by entering: `sudo apt-get install php5-xdebug`
3. Enter `php --ini` to find your `php.ini` file (and additional `ini` files for PHP5 extensions). You will find all pathes with `cli` in between, as the env(/user) currently is `cli`.
4. Open the ini file as admin user and replace `cli` with `fpm`: `sudo -e /etc/php5/fpm/conf.d/20-xdebug.ini` (or use the main file: `sudo -e /etc/php5/fpm/php.ini`).
5. Enter the following lines at the end of the `php.ini` file that you got open in Nano/Pico
   
   ```
   xdebug.default_enable=1
   xdebug.remote_enable=1
   xdebug.remote_handler=dbgp
   xdebug.remote_host=vagrant.local
   xdebug.remote_port=9000
   xdebug.remote_autostart=0
   xdebug.remote_connect_back=1
   xdebug.idekey=PHPSTORM
   html_errors=On
   ```
6. Restart Nginx with `sudo service nginx restart`
7. Restart PHP5 FPM with `sudo service php5-fpm restart`
8. Take a look at the output of `phpinfo()` to see `xdebug` as running library or add `var_dump( $GLOBALS['wp'] );` (or any other thing to test-dump) to confirm that XDebug has taken over `var_dump()` with pretty print.
9. If you want to be nice to yourself, you _might_ want to consider adding the following to your `.ini` config:
   
   ```
   xdebug.var_display_max_children=-1
   xdebug.var_display_max_data=-1
   xdebug.var_display_max_depth=-1
   ```

**Comment by aendrew** [comment]
This isn't working for me anymore —
```
The following packages have unmet dependencies:
 php5-xdebug : Depends: phpapi-20131226
E: Unable to correct problems, you have held broken packages.
```
