### ISSUE TITLE
Initial provisioning errors with basebox

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#720]
We're hitting errors when provisioning now that we're using the basebox (#476). I think what's happened is that the URLs are expiring or something.

To replicate, simply start a new machine on the latest commit. Initial provisioning will fail with errors like:

```
==> default: Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.2-common amd64 7.2.22-1+ubuntu16.04.1+deb.sury.org+1
==> default:   404  Not Found
==> default: Err:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 php7.2-zip amd64 7.2.22-1+ubuntu16.04.1+deb.sury.org+1
==> default:   404  Not Found
```

([Full log here](https://gist.github.com/abhishek-kaushik/ceaf855cd71108c95279efc01b6b342b).)

**Comment by rmccue** [comment]
(Semi-related: #582)

**Comment by rmccue** [comment]
Sidenote: seems like the basebox may have been built with a chassis.local.yaml which has non-default settings including `php: 7.0` in it?

**Comment by BronsonQuick** [comment]
>Sidenote: seems like the basebox may have been built with a chassis.local.yaml which has non-default settings including php: 7.0 in it?

Is there ant chance that you have a stale basebox from when you first pulled down this branch many moons ago when I first built the `1.0.0` box? Can you please try deleting the `chassis/chassis` box so the `1.0.0` is pulled from Vagrant Cloud and check the pho version for me? I won't have my laptop with me for a couple of weeks to check this myself

**Comment by rmccue** [comment]
Good catch, removing and retrying has the correct PHP version, and it appears the original error now doesn't occur either.

Might be that we need a new version publishing in any case for others who may have 1.0.0 locally already; I'll double-check whether this is fixed for them by doing these steps too.

(It's possible we'll still get this error in the future though after the apt repo updates again, so this may just be a factor of time.)

**Comment by BronsonQuick** [comment]
Yeah I'm happy for us to bump the base box version to `1.0.1`. reckon you can do that for me please at I won't have my laptop back for a few weeks. I've documenting how to do it all 😁

**Comment by tomjn** [comment]
This is still happening for me with the latest box and `master` branch
