### ISSUE TITLE
Ability to Bypass the Base Box

### ISSUE THREAD

**Issue by tomjn** [Chassis/Chassis#727]
Right now I'm unable to do work due to Chassis issues, and would like to bypass the `chassis/chassis` box ( high probability everybody who can fix/rebuild it are AFK or doing WCUS things ). I'd like to use the Ubuntu 16 box and trade the extra 5 minutes provisioning things for reliability

The original pull request implies I can use `_mode: base` in the config to do this, but it's non-functional and still provisions with the `chassis/chassis` vagrant box :(

**Comment by BronsonQuick** [comment]
Hey @tomjn, sorry to here your having a few issues. I still don't have my laptop with me so I can't test this to replicate it 😓

For now you should be able to comment out the if statement here: https://github.com/Chassis/Chassis/blob/e37a9e965d1b264924c5907c81fab52ffe929c0f/Vagrantfile#L105 to go back to using the bento box

**Comment by tomjn** [comment]
I'm closing this out as you can specify `_mode: base` in the config and it has the same effect
