### ISSUE TITLE
Lower-case all extension folder names

### ISSUE THREAD

**Issue by kadamwhite** [Chassis/Chassis#733]
On a case-sensitive file system, if you manually install an extension and then later add that extension to your `config.yaml`, if the casing you used for your initial install differs from the casing of the repository string in the yaml file then your extension will be cloned again into a new folder rather than using the existing extension. For example, `chassis/xdebug` in your `config.yaml` and `extensions/Xdebug` in your local folder would result in the extension being re-downloaded into the `xdebug` folder. This leads to confusing behavior when those two identical plugins conflict.

We were also discussing in Slack today the possibility that a mismatch between the casing of a `disabled_extensions` entry and the casing of the extension being disabled would cause the disable rule to have no effect, though this is not verified.

I propose we automatically lower-case all extension repository paths when performing any checks or comparisons, and coerce the name to lower case before creating any local directories, to preclude casing issues on case-sensitive environments (like Ubuntu with the default format of ext4).

**Comment by BronsonQuick** [comment]
Thanks for logging this issue. I've partially handled this in places like https://github.com/Chassis/Chassis/blob/master/puppet/chassis.rb#L219 https://github.com/Chassis/Chassis/blob/master/puppet/chassis.rb#L225
https://github.com/Chassis/Chassis/blob/master/puppet/chassis.rb#L257 and https://github.com/Chassis/Chassis/blob/master/puppet/chassis.rb#L260 but we definitely need to handle it better for people who manually `git clone` extensions. I'll probably have a crack at this over the weekend.
