### ISSUE TITLE
Chassis Global Extensions conflict with Chassis Extension Updates

### ISSUE THREAD

**Issue by ntwb** [Chassis/Chassis#747]
When trying to update Chassis extensions if there is a Chassis Global Extension installed this causes Vagrant provisioning to fail:

Global Extension Config at `~/.chassis`

> `~/.chassis/extensions/SequelPro`

Chassis Extension Config `config.local.yaml`:

```yaml

extensions:
  - chassis/sequelpro
```

Running `vagrant up --provision`:
```shell
❯ vagrant up --provision

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running action triggers before up ...
==> default: Running trigger...
==> default: Please change chassis/chassis-elasticsearch to chassis/chassis_elasticsearch in your yaml configuration file.
==> default: Checking if box 'bento/ubuntu-16.04' version '201906.18.0' is up to date...
==> default: Running provisioner: shell...
    default: Running: /var/folders/33/6sh192cx64v_v4st4f6vpjsh0000gn/T/vagrant-shell20191120-12465-1891vx.sh
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Error: Duplicate declaration: Class[Sequelpro] is already declared in file /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:13; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node my.local
==> default: Error: Duplicate declaration: Class[Sequelpro] is already declared in file /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:13; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:19 on node my.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Manually updating the Sequel Pro extensions, both the local and the global has no effect, the same error is observed.

The only workaround I found was to rename the global `~/.chassis` config folder which makes it then ignored.

1. What operating system do you use?
MacOS
2. What version of Vagrant are you running?
Vagrant 2.2.5
3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.0.12
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```yaml
paths:
  base: ..
  content: content
  wp: wordpress

hosts:
  - my.local
multisite: true

# Define database prefix, since we have tests as well
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_
# Define the extensions we want
extensions:
  - chassis/xdebug
  - chassis/sequelpro
  - chassis/cavalcade
  - chassis/composer
  - chassis/phpcs
  - chassis/mailhog
  - chassis/chassis-elasticsearch
  - chassis/intl
  - chassis/tester
  - chassis/phpini
  - chassis/nodejs
  - chassis/npm
elasticsearch:
  version: '5.3.3'
  jvm_options:
    - '-Xms1024m'
    - '-Xmx1024m'
composer:
  paths:
    - /chassis/content/plugins-mu/vendor/memcached-adapter
    - /chassis/content/plugins-mu/vendor/simple-cache-bridge
    - /chassis/content/plugins-mu/vendor/PhpSpreadsheet
php: 7.2
virtualbox:
    memory: 8192
    cpus: 3
```
5. Do you have any Chassis other extensions installed? If so, what are they?

**Comment by ntwb** [comment]
Note, #743 does *not* fix this issue, the issue persists.

**Comment by BronsonQuick** [comment]
I think I know what the issue here is as I've been able to replicate it. Can you please verify that lower casing the global extension name fixes provisioning for you? i.e. `~/.chassis/extensions/SequelPro` becomes `~/.chassis/extensions/SequelPro`. If you can provision successful with that then that'll confirm for me that it's a casing issue and I'll update the logic to handle that as well. Thank you Sir! 🎸🤘

**Comment by ntwb** [comment]
Yup, resolved by switching to `~/.chassis/extensions/sequelpro` 💯

**Comment by BronsonQuick** [comment]
Champion. Thank you Sir. I'll reopen this as it's an issue we should still handle!
