### ISSUE TITLE
wp_lostpassword_url() goes to a 404

### ISSUE THREAD

**Issue by colmtroy** [Chassis/Chassis#770]
I'm pretty sure this is because core WP lives in /wp - but thought I'd ask anyway.
When I link to `wp_lostpassword_url()` on a WP site running in Chassis, it leads to a 404 at: `http://mysite.local/wp-login.php?action=lostpassword`

Of course if I manually create the link to go to `http://mysite.local/wp/wp-login.php?action=lostpassword` - everything works fine.

But shouldn't core WP functions work as designed under Chassis?

**Comment by colmtroy** [comment]
Another side effect of this issue is that password reset emails contain a url in the format:
`http://mysite.local/wp-login.php?action=rp&key=snip&login=something%40gmail.com`
These also lead to a 404 with a Chassis WP instance.

**Comment by BronsonQuick** [comment]
Hey @colmtroy, thanks for opening this issue. I've just been trying to replicate this and I haven't had any success. I've setup a new Chassis instance and I've edited `twentytwenty/template-parts/content.php` to include the following code to output the lost password link: ` <p><?php echo wp_lostpassword_url(); ?></p>`.

This functions correctly for me: 
<img width="1438" alt="Hello_world__Chassis_Site_2020-01-13_05-49-52" src="https://user-images.githubusercontent.com/1377956/72224698-f8ac6380-35c8-11ea-8ecd-2fbae1e524d7.png">

Could you please provide me with some more information on your local setup? I'm wondering if it might be a multisite setup perhaps? Thanks!

**Comment by BronsonQuick** [comment]
Cancel that question, as I've just created a new Chassis multisite install and I can replicate this. Looks like this is a WordPress core issue: https://core.trac.wordpress.org/ticket/21352

There is a fix for this and it's to use a [filter](https://core.trac.wordpress.org/ticket/21352#comment:21). I'm going to close this issue seeing it's a WordPress core issue. Thanks for reporting it though as I wasn't even aware of this bug!

**Comment by rmccue** [comment]
Note that in multisite, `/wp/` isn't required (and can't be, due to the way multisite works), so we have additional routing in nginx for it. `/wp-login.php` on multisite shouldn't be 404ing.
