### ISSUE TITLE
can't connect to chassis host while on VPN

### ISSUE THREAD

**Issue by photocurio** [Chassis/Chassis#773]
1. What operating system do you use?
Mac OS 10.13.6
2. What version of Vagrant are you running?
Vagrant 2.2.6
3. Are you using VirtualBox or VMWare and which version are you using?
6.0
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```notice: |
    # THIS FILE IS MANAGED BY ALTIS, ANY CHANGES MADE MAY BE LOST
    #
    # Find out how to modify this file through config here:
    # https://www.altis-dxp.com/resources/docs/local-chassis/
php: '7.2'
paths:
    base: ..
    wp: wordpress
    content: content
multisite: 'Yes'
extensions:
    - humanmade/platform_chassis_extension
    - sequelpro
    - xdebug
    - memcache
    - phpini
elasticsearch:
    repo_version: 6.x
    version: 6.3.1
    plugins: [analysis-icu, ingest-attachment]
hosts:
    - fresenius.local
ip: 198.51.100.44
machine_name: fresenius.local
```

5. Do you have any Chassis other extensions installed? If so, what are they?
no

Chassis runs nicely, as long as I'm not connected to my employer's corporate VPN.  If I'm on VPN I get a Can't Connect error in my browser.  According to this post: [fixing local development issues with vpns](https://wearnhardt.com/2018/09/fixing-local-development-issues-with-vpns/) the issue appears to be that the VPN hogs the typical private network IP ranges. 

Note the IP address in the confg above.  I'd like to know if setting an "ip" value this way is the same as setting a _private network ip_, as  described in the linked post.  I have tried various addresses (in ranges TEST NETS 1, 2 and 3) in my config file, such as the one above, and none of them work (unlike the post author, my VPN is not so helpful to  tell me which which IP ranges it controls).  Does anyone know if I am setting the private network ip correctly?

**Comment by rmccue** [comment]
Yep, the `ip` setting is equivalent to `private_network_ip` there; both are set on [the Vagrant private network configuration](https://github.com/Chassis/Chassis/blob/c61ffac6f9731bdd8562b3f5f1a9a308f72a3c5f/Vagrantfile#L141).

For the IP addresses, you may be able to run `ifconfig` and check the `netmask` for the interface if it's in there. I don't know specifically how that ties in with the VPN's settings specifically though.

**Comment by photocurio** [comment]
It seems that setting the IP this way has no effect.  I tried provisioning the VM, and restarting the machine.  running `traceroute fresenius.local` on my laptop always gives the same result: 172.28.128.3.

Looking at my Virtualbox, in the machine settings, the Adapter 2, is set to Host-only->vboxnet0->172.28.128.1

If I change the machine in Virtualbox to vboxnet1, it always reverts to vboxnet0.  Is this a Chassis setting?

**Comment by BronsonQuick** [comment]
Hey @photocurio! Did you specify the ip address before your initial provision?

If not (and the data on the VM is okay to be lost) than can you please do `vagrant destroy -f && vagrant up` and see if that works?

Also, if you have issues running `ping fresenius.local` and it's not returning the IP address you specified then you might need to run `vagrant halt && vagrant up` after the initial provision. From the looks of it there might be an issue with Avahi not applying custom host names correctly on an initial provision so we might need to look into a fix for that.

>If I change the machine in Virtualbox to vboxnet1, it always reverts to vboxnet0. Is this a Chassis setting?

Off the top of my head I'm not sure about that. I might need to look into that further.

**Comment by photocurio** [comment]
Thanks Bronson. I'll try setting up a brand new box, and see if that changes it.

**Comment by BronsonQuick** [comment]
I'll close this one out for now. Feel free to open it again if you're still having this issue.
