### ISSUE TITLE
Revert our monkey patch for Vagrant

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#774]
We had to merge a monkey patch to temporarily fix: https://github.com/Chassis/Chassis/pull/772. Once Vagrant `2.2.8` is released we can revert that as [this fix](https://github.com/hashicorp/vagrant/issues/11403) resolves the issue.

**Comment by roborourke** [comment]
I'd hold off on reverting too quickly or even at all if the monkey patch works fine with Vagrant 2.2.8 - we can't assume everyone will update straight away.

**Comment by BronsonQuick** [comment]
Yeah sounds good. I might wrap it in a `Vagrant.require_version` check to start with and phase it fully out after a few more major Vagrant releases

**Comment by kadamwhite** [comment]
I could not use VirtualBox 6.1 and Vagrant 2.2.7 until I manually disabled the monkey patch. Attempted about a dozen individual VM installs, on both an Ubuntu 19.10 and Ubuntu 20.04 host OS, and nothing worked until removing the patch. Based on that experience, I'd be more bullish on reverting it, because it lost me over a day of work on 2.2.7.

**Comment by kadamwhite** [comment]
Aaaand now that I've posted that, now my VM doesn't work _without_ the Monkeypatch, and I'm back to where I started with nothing working. So, disregard, I have no idea what's wrong with my machine but it's just hosed and I don't think the patch was the issue after all.

**Comment by BronsonQuick** [comment]
This is definitely a weird issue and it's upstream in Vagrant. I think if we remove the initial VirtualBox Host-Only interface then do `vagrant up` then we're back in action again. 

You can confirm this by running `VBoxManage list dhcpservers` then `VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0` should remove that then you should able to run `vagrant up` or `vagrant reload` and things should work again. We're kinda crippled by Vagrant because they haven't done another release yet to get handle this issue.

Note: The monkey patch should still be in place when you do this and you shouldn't need to set an IP or pass in the hostsupdater option.

**Comment by kadamwhite** [comment]
@BronsonQuick That set of `VBoxManage` commands did indeed resolve my issue, on 20.04 with Vagrant 2.2.7 and VBox 6.1. Thanks much.

**Comment by BronsonQuick** [comment]
@kadamwhite Glad to hear that worked for you. Looks like we might be all good again thanks to new a [Vagrant release](https://github.com/hashicorp/vagrant/releases/tag/v2.2.8)! 😅

I'll try and test this tonight.
