### ISSUE TITLE
Is it possible to run multiple chassis instances concurrently?

### ISSUE THREAD

**Issue by colmtroy** [Chassis/Chassis#779]
Howdy folks,
Sorry if this is documented but I couldn't find it anywhere.
Should it be possible to run multiple chassis instances concurrently?
I ask because at present it's not possible for me.
I've tried running 2 chassis instances concurrently and one of them always fails.

First config.yaml 
```
hosts:
    - vagrant.local
    - domain1.local
```

Second config.yaml 
```
hosts:
    - vagrant.local
    - domain2.local
```

I originally had instance 1 running fine with no issues (on both vagrant.local and the domain1.local alias). I then created and provisioned the second chassis instance. Everything looked to work properly from the terminal. But calling domain2.local simply times out.

I also tried installing hostsupdater and setting:
```
hostsupdater: yes
```
in both instances and re-provisioning - but no dice.

(Sidenote: in my /etc/hosts file - the local IP for both domain1.local and domain2.local is identical)

I would get domain2.local (and the separate chassis instance to work by running vagrant halt, vagrant up in the second instance, but then the first instance doesn't work!

I'm wondering if it's something peculiar to my setup or if I'm restricted to just a single chassis instance at any one time?

Vagrant 2.2.6 
VirtualBox 6.0.14
MacOS 10.15.1

**Comment by colmtroy** [comment]
Quick update on this issue.
I set static IP's for both instances and ran vagrant halt, vagrant up on both instances and now I can run both concurrently. (vagrant provision wasn't enough to reset their IP's).
Just wondering if this is a design feature or if my environment is wonky :)

**Comment by BronsonQuick** [comment]
Hey @colmtroy, sorry for the delay on getting back to you. You should be able to get this to work if you have one config.yaml as:
```
hosts:
    - domain1.local
```
and the other as:
```
hosts:
    - domain2.local
```
I think sometimes it does require a `halt` and and `up` still though. I'm glad that setting the IPs worked.

I'll try and replicate this and if I do have to set the IP addresses manually then I'll do a Pull Request to update the documentation! Thanks for reporting the issue.

**Comment by BronsonQuick** [comment]
I'm closing this out as I couldn't replicate it.
