### ISSUE TITLE
Symlink extensions?

### ISSUE THREAD

**Issue by banderon** [Chassis/Chassis#788]
Before I spend however long trying to figure out if I'm doing something wrong, figured it's best to ask if it's even possible.

I'm on macOS Catalina 10.15.4. We're working on a custom extension for our project, checked out into `/content`. We'd like to have this extension load in our Chassis build. I figured the easiest way to include it in the project, while allowing us to update it easily when needed, was to create a symlink from within `/content` into the `/extensions` folder in the project root: ``$ ln -s `pwd`/extensions/custom-ext ../extensions/custom-ext`` This way we can pull down the latest version of our project and Chassis would immediately have access to the updated extension when we reprovision.

<img width="234" alt="Screen Shot 2020-04-13 at 23 55 44" src="https://user-images.githubusercontent.com/533529/79185346-a146ab00-7de4-11ea-8929-758a2748178e.png">

However, Chassis seems to be ignoring the symlinked folder. Is this something Chassis doesn't support? Is there any way around this other than copying the folder in manually each time we update it? Following the symlink would mean that we can maintain the code for the extension entirely within our project and not have to keep track of copying in new versions.

**Comment by BronsonQuick** [comment]
Hey @banderon, so just to check I'm understanding your requirements here, you'd like to create a custom Chassis extension that can be made available to all your developers any time you provision a new Chassis instance or if you run `vagrant provision` yeah? If that's the case then it's best to publish the extension on Github and add it to your configuration. There are details on that setup here: https://docs.chassis.io/en/latest/config/#extensions We've also got docs on how to create your extension here: https://docs.chassis.io/en/latest/extend/#creating-your-own

Also, if it's an extension that we haven't created and it's a common package or tool that you'd like to work with Chassis then feel free to open an issue with a request for a new extension and I can try and whip something up for you if I think it's common enough for people to want to use it.

Lastly, if I've misinterpreted your requirements then please let me know. Maybe try and explain it again and I'll have another go at answering your question! Thank you Sir!

**Comment by banderon** [comment]
**Symlinking**

@BronsonQuick That's essentially correct. We've got an extension built out, but we don't really want to pull it out into its own repo for now. Making a dedicated repo would mean having to manually update the checkout of that repo when there's a code change... whereas, if the extension is directly in the project repo, any updates would be pulled down with the next pull on the project itself. For that reason, I figured the simplest way to bundle it into Chassis was to symlink the extension from inside our checkout in `/content` into the `/extensions` folder... but it seems Chassis ignores symlinks. That means that we'll still have to take a manual step (copying the folder) whenever we merge in an update. If that's something that's changeable, that'd be nice and would make life a bit simpler.

---

**The Extension**

The extension's purpose is to install the [runkit7](https://github.com/runkit7/runkit7) PHP extension, so I don't know how much demand there'd be for such a specific tool since it fills a fairly niche need. As for building out the extension itself, I've already kludged together a functioning version from code in the existing extensions you've built (thanks for those!). However, I don't know too much about devops, have no idea how Puppet works and hadn't seen those docs you linked above (those would've probably helped), and am an amateur when it comes to bash scripting... so my solution is probably a very inefficient and messy way of getting the job done, akin to making three lefts to turn right. It's worth noting that I discovered [Chassis/phpini](https://github.com/Chassis/phpini) a few minutes ago, after I'd already learned all about `awk` just to implement that part of setting this up; that extension can probably already simplify things somewhat.

If you'd like to take a look, I've attached the extension below. Feel free to make any suggestions/improvements. I imagine since you actually understand how all of this works, you could probably improve this without too much difficulty to allow loading in any custom PHP extension(s), which others might indeed find useful.

_Download:_ [runkit7.zip](https://github.com/Chassis/Chassis/files/4473682/runkit7.zip)

**Comment by rmccue** [comment]
So, symlinking extensions won't work.

When you create a symlink, you're essentially creating a file that points to another path. When VirtualBox mounts the directory into the VM, it will sync that pointer, but the place the pointer points to isn't inside the VM, so it won't work.

There's two ways to share extensions across VMs:

1. Use the [global extensions](https://docs.chassis.io/en/latest/extend/#globally-installing-extensions) facility. Chassis will take care of all of the linking itself and mount the extensions into the machine properly. Users will have to install them onto their machine though. This is generally designed for developer tools that users want across multiple VMs, not project-specific stuff.
2. Use the [synced folders](https://docs.chassis.io/en/latest/contents/#synced-folders) configuration to mount additional folders into the VM.

However in your case, it sounds like you want it tied into the project. What you actually probably want instead is a setup script which creates a `config.local.yaml` for users, and includes an `extensions` entry. Chassis will take care of cloning the repo down for you (and keeping it up to date as well; IIRC we merged that PR); it just calls `git` on the command line, so private repos would work fine here too.

Here's an example of a setup script we commonly use (adjusted for each project). Save this to `setup.sh` and run it to start your project:

```sh
#!/bin/bash
# Fail on any error (and yes, I know this not perfect)
set -e

# Render the config into a variable for output later.
IFS= read -d '' -r CONFIG <<"EOF" ||:
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - projectname.local
extensions:
    - chassis/xdebug
    - chassis/sequelpro
EOF

# Render instructions into a variable too.
IFS= read -d '' -r INSTRUCTIONS <<"EOF" ||:
Quick commands:

  vagrant up
    Boot (power up) your virtual machine

  vagrant halt
    Stop (power down) your virtual machine

  vagrant ssh
    SSH into the machine to run commands.
EOF


CMD_START=$(echo -e "\033[38;5;8m")
CMD_END=$(echo -e "\033[0m")

# Clone down Chassis if we need to
if [[ ! -d chassis ]]; then
	echo "Grabbing Chassis..."

	git clone --progress --recursive git@github.com:Chassis/Chassis.git chassis

	# Set up Chassis configuration
	echo "$CONFIG" > chassis/config.local.yaml
fi

# Start the machine
cd chassis
export VAGRANT_CWD=./
vagrant --color up | sed -e "s/^/${CMD_START}[vagrant]${CMD_END} /"

# Define a function to run xdg-open (Linux) or open (OSX), whichever is available.
# Check for xdg-open first, because "open" exists on Linux but means something else.
openurl() {
    if hash xdg-open 2>/dev/null; then
        xdg-open "$@"
    else
        open "$@"
    fi
}

# Open in browser
while true; do
	echo
	read -r -p "Open https://projectname.local/wordpress/wp-admin/ in your browser? [y/N] " SHOULD_CREATE
	SHOULD_CREATE=$(echo "$SHOULD_CREATE" | tr '[:upper:]' '[:lower:]')
	case $SHOULD_CREATE in
		y|yes)
			openurl https://projectname.local/wordpress/wp-admin/
			break
			;;
		n|no|"")
			break
			;;
		* )
			echo "Please answer yes or no."
			;;
	esac
done

echo "Installation complete!"
echo
echo "$INSTRUCTIONS"
```

You can add anything you like into the config section there, including custom extensions (which can be any GH repo name).

**Comment by banderon** [comment]
> When VirtualBox mounts the directory into the VM, it will sync that pointer, but the place the pointer points to isn't inside the VM, so it won't work.

Ah, that'd do it. Didn't realize that extensions are processed inside the VM. We might just stick to copying it in during setup then and add some sort of versioning to our setup script.

Thanks for the info! I think my next step will be to try to use the phpini extension to enable the extension installed by the runkit7 PHP extension I linked above.

**Comment by BronsonQuick** [comment]
@rmccue Thanks for adding the extra information! I totally blanked and forgot to mention the symlink option!

@banderon Thanks so much for the code for the extension you've been working on. I hadn't encountered `runkit` before. I definitely think there's enough of a use case warranted for me to create an official extension for it. I'll try and use your code as a starter and publish something for you on the weekend.

**Comment by banderon** [comment]
> I hadn't encountered runkit before. I definitely think there's enough of a use case warranted for me to create an official extension for it. I'll try and use your code as a starter and publish something for you on the weekend.

@BronsonQuick You've probably never heard of `runkit` because it's a dark and evil thing 😏. Messing with defined functions and constants is very bad practice and (generally) shouldn't be done... but our site is on **VIP Go**, and part of local dev for that environment includes loading in the [VIP Go mu-plugins](https://github.com/Automattic/vip-go-mu-plugins) repo, which pulls down and kicks off a number of functions and constants that get in the way of our local development. Rather than modify the code we pull down from their repo (which would hinder being able to easily pull down future updates), we have a file (`local-only.php`, which.. only loads on our locals) with the dirty code we use to massage their functions and constants into something less intrusive and easier to work around.

If you're going to play around with the extension, you'll initially need to run this bit of code before you provision the VM:
```bash
# From within /content
cd ../puppet/modules/chassis/templates/

# Add "extension=runkit7.so" to `php.ini.erb` in the "Dynamic Extensions" section
awk 'BEGIN{c=5}/; Dynamic Extensions ;/{c=1}(c++)==4{print "extension=runkit7.so\n"}1' php.ini.erb > php-tmp && mv php-tmp php.ini.erb
```
I wrote that before I discovered [chassis/phpini](https://github.com/Chassis/phpini) which I haven't had a chance to play around with but I imagine will remove the need for the above code. Ideally, this extension would be able to add the necessary line into `php.ini.erb` that it needs on its own, but that's beyond my abilities.

**Comment by rmccue** [comment]
@banderon As an easier way for your config: PHP will combine all the files in `/etc/php/7.x/fpm/php/conf.d` into the configuration. The phpini extension generates a file within that, and is intended as an easy way for users to add additional config, but as an extension, you can just create a file there yourself.

In shell, that'd be:
```
echo "extension=runkit7.so" > /etc/php/7.4/fpm/conf.d/10-runkit.ini
```

(It's conventional to prefix with an int for load order, and 10 is the normal one for most extensions. Runkit, being special, might need to be earlier.)

**Comment by banderon** [comment]
@rmccue My first attempt was to just adding the extension config within the VM, but every attempt to do that failed as PHP was already loaded by then. I couldn't figure out why, but restarting it/nginx didn't seem to load the new ini; it would only be utilized after I reloaded the VM. That's when I finally gave up and made the move to inject the setting into the ini template before the VM was provisioned.

Would love to know what I was doing wrong.

**Comment by banderon** [comment]
@rmccue My first attempt was to actually to add the extension config within the VM, but every attempt to do that failed as PHP was already loaded by then. I couldn't figure out why, but restarting it/nginx didn't seem to load the new ini; it would only be utilized after I reloaded the VM. That's when I finally gave up and made the move to inject the setting into the ini template before the VM was provisioned.

Would love to know what I was doing wrong.

**Comment by banderon** [comment]
@BronsonQuick Just a quick FYI: it looks like my extension has stopped building, breaking the vagrant provision. It looks like `phpize` isn't being found now, which prevents the extension from being built and installed. The only change I've found after talking with folks on our team for whom it's still working is that they're on PHP 7.3.16, and provisioning now builds out with PHP 7.3.17. So if you do play around with it and find that your vagrant is breaking, that'd be why.

```
default: Notice: /Stage[main]/Chassis::Php/Package[php7.3-fpm]/ensure: ensure changed '7.3.16-1+ubuntu18.04.1+deb.sury.org+1' to '7.3.17-1+ubuntu18.04.1+deb.sury.org+1'
default: Notice: /Stage[main]/Runkit7/Exec[Install runkit7 extension]/returns: Cloning into 'runkit7-src'...
default: Notice: /Stage[main]/Runkit7/Exec[Install runkit7 extension]/returns: /bin/sh: 8: phpize: not found
```

**Comment by BronsonQuick** [comment]
@banderon Ahh gotcha. So you'll get `phpize` if you have `php-dev` installed. 

I've only just managed to have a little bit more of a read up on runkit7 and from the looks of it I think there might be a better option for us to use instead of the shell script you've written in your extension. I think we should use `pecl` to install it. After a quick and dirty ssh into a Chassis box and running some various commands I think we can achieve what we need by creating an extension that makes sure the following packages are setup:

- `php-dev` so we can run `phpize`
- `php-xml` so we can install runkit7
- `php-pear` so we can run `pecl install runkit7-alpha`

**Comment by banderon** [comment]
@BronsonQuick That all sounds about right :)

As I'd mentioned, I've never used puppet before so I was limited by what I could get it to do. I'd tried the PECL approach, but couldn't figure out how to get puppet to do all the things I wanted it to do and didn't have the time to devote to better learning the platform.. hence the github approach I cobbled together. I could do most things via SSH directly (after the VM had already booted), but couldn't work out how to accomplish them during provisioning with puppet. Sounds like you'll likely have much more successful 👍

**Comment by BronsonQuick** [comment]
Hey @banderon, yeah that totally makes sense. Puppet is a little tricky to wrap your head around. I think you did a killer job with what you had given you're only new to Puppet and Chassis extensions. I'll start whipping up the basics of the new extension during my lunch hour and circle back here to drop a link to it then I'll close this issue and we can work on any issues of extra configuration options you might need in that repo.

**Comment by BronsonQuick** [comment]
Alrighty, here's a quick lunchtime extension to get us started: https://github.com/Chassis/runkit7
