### ISSUE TITLE
failed to create symbolic link '/vagrant/puppet/manifests/example.pp

### ISSUE THREAD

**Issue by pritimills** [Chassis/Chassis#844]
1. What operating system do you use?
Windows 10 Home
2. What version of Vagrant are you running?
Vagrant 2.2.14

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.1

4. Do you have a custom YAML file? If so, what does it contain?
  No
5. Do you have any Chassis other extensions installed? If so, what are they?

**Comment by pritimills** [comment]
I am receiving the failed to create symbolic link and Protocol Error.

` default: Running provisioner: shell...
    default: Running: C:/Users/Priti/AppData/Local/Temp/vagrant-shell20201208-108168-1pu9yej.sh
    default: ln:
    default: failed to create symbolic link '/vagrant/puppet/manifests/example.pp'
    default: : Protocol error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

**Comment by BronsonQuick** [comment]
Hey @pritimills, thanks for you issue. Unfortunately, I don't have a copy of Windows 10 Home handy to test this but my first guess would be to ask if you were running your terminal as an Administrator or not? I have a vague recollection that this issue will occur if you aren't running your terminal as an Admin.

**Comment by pritimills** [comment]
Hi,

 

I am running the terminal as administrator. 

 

Thanks,
