### ISSUE TITLE
Have chassis easily work as a drop-in for theme/plugin development.

### ISSUE THREAD

**Issue by ajf-** [Chassis/Chassis#87]
Currently, this is the structure that we have to follow:

```
project-name
|_ Chassis
    |_ ...
    |_wp
       |_wp-content 
          |_ themes  <---| Work happens here 
          |_ plugins <---|
```

I would like to be able to drop Chassis into a theme (or plugin) development workflow, and keeping only that portion of wordpress visible for development: 

```
project-name
|_ theme-name
    |_ files... <-- Chassis uses config.vm.synced_folder to map this to wp-content/themes/theme-name
|_ Chassis
    |_ ...
```

Or in the case of a plugin:

```
project-name
|_ plugin-name
    |_ files... <-- Chassis uses config.vm.synced_folder to map this to wp-content/plugins/plugin-name
|_ Chassis
    |_ ...
```

Keeping the actual wordpress installation only inside the virtual machine and not mapped to any directory in the host machine. __The purpose of this is to have a self-contained Chassis drop-in for theme/plugin development that can be bundled with the sources without needing to bundle a complete WordPress installation too.__

WordPress' files, updates, plugins, etc. in this case would be managed with wp-cli inside the vm only. 

Any pointers on how to do this would be appreciated and I'd be glad to make a pull request if you guys find this could be useful (it would certainly be useful in my case) 

My current approach is changing in ```puppet/manifests/development.pp```

```
sennza::wp { $config['hosts'][0]:
	location          => '/vagrant',
```
For

```
sennza::wp { $config['hosts'][0]:
	location          => $config[wplocation],
```

So that the ```wplocation``` parameter can be set in ```config.yml``` to something other than ```/vagrant```, and then (in the case of a theme) add:

```
config.vm.synced_folder "../theme-name", $config[wplocation] + "/wp-content/themes/theme-name", :extra => "dmode=777,fmode=777"
```

To map the appropriate folder to the Wordpress installation.

Let me know if this is something that would interest you and any pointers on getting it done.

Thanks

**Comment by BronsonQuick** [comment]
I think this should be fixed now thanks to this PR: https://github.com/Chassis/Chassis/pull/145
