### ISSUE TITLE
Restore /latest/ in docs

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#893]
Just an FYI, I fixed "latest" in Read the Docs to handle the branch rename to main; "latest" is the standard RTD alias, and a lot of existing links point to it, so figured it made most sense to bring it back.

**Comment by BronsonQuick** [comment]
Thank you Sir. Much appreciated. I did a "quick" fix here: https://github.com/Chassis/Chassis/issues/842 when I realised they hadn't been working properly for ages. Good to know you're still alive too 💖

**Comment by rmccue** [comment]
Yeah, RTD is a bit of a pain like that, don't think they really prepared for the big master -> main renamening. Likewise, hope you're well!
