### ISSUE TITLE
What to do about VMs and Docker

### ISSUE THREAD

**Issue by joemcgill** [Chassis/Chassis#911]
We're currently living in a world that puts folks using tools like Chassis facing challenging realities. As of today, VirtualBox isn't compatible with Apple's M1 chips with no upcoming solution on the horizon, and [Docker has just announced a change to their ToS](https://www.docker.com/blog/updating-product-subscriptions/) that require many folks to pay a subscription fee to continue using Docker Desktop on their Macs.

The purpose of this issue is to prompt discussion about a viable path forward for Chassis that would avoid the need to use a provider that does risk either obsolescence or unstable pricing structures.

**Comment by BronsonQuick** [comment]
@joemcgill I just noticed VVV have this: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2441/files do you have anyone that could confirm if that's working as that's in VVV's core.

Chassis used to run on VMWare but I haven't used that for a while. You mentioned Slack that VMWare Fusion should be getting support for M1s so that might be a possible path too. I did just check the pricing though and it's $280 Aussie for that so it's a rather large outlay compared to $0 💸

**Comment by joemcgill** [comment]
Yeah, it does seem like Parallels might be the best current option without porting everything to a totally different containerized solution. Laravel Valet is another interesting option to play with, but this heavily depends on running services directly on the host machine, rather than being able to quickly provision services within a VM to match the requirements of the specific project. Maybe there's a way to automate that configuration and use Valet for managing/serving the local WP application?

**Comment by tomjn** [comment]
There aren't many M1 compatible vagrant boxes but they do exist. The most difficult parts of making VVV compatible were:

 - acquiring hardware
 - building Mailhog. The project appears to be abandoned and their build process doesn't build appropriate binaries. It's easily fixed but there's nobody in power around to do it.
   - @evertiro put his own copy up that we use instead
 - the box we found was ubuntu 20, so we had to update from ubuntu 18 to use it

I also explored using a vagrant plugin for canonicals multipass that relied on the same apple hypervisor, but didn't spend much time. It didn't have many users either.

**Comment by BronsonQuick** [comment]
@tomjn Awesome. Thanks so much for sharing all your learnings. Most appreciated! 🙏🏻

**Comment by BronsonQuick** [comment]
@joemcgill FYI Tom has done some great work over here: https://github.com/Chassis/Chassis/pull/941/files KAdam has tested it too and had success. Reckon you could give it a spin sometime in the next week or so too please?

**Comment by joemcgill** [comment]
Oh nice work @tomjn! For my clarity, does this PR require Parallels on M1 chips to work, or are these separate concerns?

**Comment by BronsonQuick** [comment]
Ahh yep. I should've mentioned that. It does require a paid version of Parallels because it needs CLI access. I'd you don't want to fork out some dollarydoos for that then I totally understand!

Well have docs coming for it soon. You'll.also need to set ``

**Comment by BronsonQuick** [comment]
Sorry for accidentally closing it. I'm typing from bed at 4:47am...as you do 🤣

**Comment by BronsonQuick** [comment]
Alrighty, thanks to @tomjn we now support [M1 chips](https://docs.chassis.io/en/main/quickstart/#macos-m1-chips). This does require purchasing [Parallels Desktop for Mac Pro Edition](https://buy.parallels.com/329/purl-pd17f-pro1y) which means Chassis is no longer free for MacOS M1's but it's our best solution for now so I'll close this one out. Hopefully we can figure out a free alternative in the future!
