### ISSUE TITLE
Ensure the VM has internet access

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#927]
There's a recurring issue on Windows where the VM loses internet access. We should add the following to our `Vagrantfile` to fix this issue:
```
vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
```

**Comment by pbiron** [comment]
Thanx @BronsonQuick
