### ISSUE TITLE
Avahi has to be restarted after rebooting

### ISSUE THREAD

**Issue by rmccue** [Chassis/Chassis#95]
Bug I can reproduce on Mac: can't connect after doing a `halt` then `up`.

I've dug into this, and it looks like avahi is serving up the wrong IP: I get `10.0.2.15` from eth0 instead of the correct `172.28.128.3` from eth1. It looks like this problem fixes itself after a while, but we need to fix this.

**Comment by tanveer19** [comment]
i am using ubuntu mate 14.04 x64 and Every time at boot I get a message “Network service discovery disabled. Your current network has a .local domain, which is not recommended and incompatible with the Avahi network service discovery. The service has been disabled.”
and i have to "vagrant reload" several times before i can access vagrant.local after i restart my pc. i am not sure if it really fixes the issue.
is this problem related to avahi? adding deny-interfaces=eth0 to /etc/avahi/avahi-daemon.conf didn't work for me.

**Comment by BronsonQuick** [comment]
@tanveer19 Yeah I had that same issue with Ubuntu as well and I couldn't figure out a workaround for it unfortunately :( Let me know if you have any luck working through it.

**Comment by BronsonQuick** [comment]
I haven't seen this issue in ages so I'm gonna close it. Feel free to open it again if any of you can replicate it!
