### ISSUE TITLE
Add `WP_RUNTIME_ENVIRONMENT`

### ISSUE THREAD

**Issue by BronsonQuick-APL** [Chassis/Chassis#963]
Once https://github.com/WordPress/wordpress-develop/pull/2225 lands in WordPress core we will need to add:
`define( 'WP_RUNTIME_ENVIRONMENT', 'virtualbox' );` into Chassis core in https://github.com/Chassis/Chassis/blob/main/wp-config.php#L11

This will ensure that WordPress plugin and theme rollbacks work correctly on VirtualBox.

**Comment by BronsonQuick** [comment]
We didn't end up needing this one.
