### ISSUE TITLE
Test Chassis on Apple M1/M2 with VirtualBox 7.x

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#983]
VirtualBox 7 has beta support for Apple M1 and M2 chipsets. I'm curious to know how Chassis goes out of the box with it.

@tomjn @kadamwhite @stuartshields any chance one of you folks could please give it a whirl for me as I still haven't got myself an M1/M2 laptop yet. Thanks! 🙏🏻

**Comment by BronsonQuick** [comment]
Here's a link to the download as currently the link to it is broken on their wiki: https://download.virtualbox.org/virtualbox/7.0.2/VirtualBox-7.0.2_BETA4-154219-macOSArm64.dmg

**Comment by tomjn** [comment]
@BronsonQuick @kadamwhite @stuartshields expect any tests of VirtualBox 7 on M1/2 to be somewhat catastrophic, the very fact they released it in such a crippled state.

At most you can expect to get an old 32bit linux distro to run very very slowly with poor stability. Don't expect Virtualbox 7 to be usable on Arm for at least a year

**Comment by BronsonQuick** [comment]
@tomjn Ahh true. I didn't realise it was in that bad of a state. Thanks for the heads up!

**Comment by BronsonQuick** [comment]
It looks like the folks at VirtualBox have removed the beta link from the site and they aren't even building for Arm in the betas so I'm gonna close this off. Parallels seems to be the only option for M* chips 😭
