### ISSUE TITLE
"Deprecated" errors when using php 8.1

### ISSUE THREAD

**Issue by dirad** [Chassis/Chassis#986]
1. Host is windows 10

2. Vagrant 2.3.2

3. VirtualBox 6.1.40

4. only change is php: 8.1

5.  default install

The admin interface is littered with "Deprecated: " errors ...
For example: 

```
Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vagrant/wp/wp-includes/Requests/Cookie/Jar.php on line 102

Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /vagrant/wp/wp-includes/Requests/Transport/cURL.php on line 345

Deprecated: setcookie(): Passing null to parameter #5 ($domain) of type string is deprecated in /vagrant/wp/wp-includes/option.php on line 1113

Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in /vagrant/wp/wp-includes/formatting.php on line 2772
```

Also this warning shows up, more than once on some pages.
```
Warning: Cannot modify header information - headers already sent by (output started at /vagrant/wp/wp-includes/Requests/Transport/cURL.php:345) in /vagrant/wp/wp-admin/admin-header.php on line 9
```

**Comment by BronsonQuick** [comment]
Hey @dirad, thanks for opening this issue. I've had a quick look and I believe that these deprecations and warnings should be resolved when WordPress 6.1 drops in early November but I'll leave this issue open in case that's not the case.

A quick look into Requests should that the first issue has been fixed upstream: https://github.com/WordPress/Requests/blob/develop/src/Cookie/Jar.php#L98 and I think WP 6.1 will ship with the latest version of that.

**Comment by BronsonQuick** [comment]
We've just updated Chassis to WP 6.1 but it looks like there are still some deprecations that haven't been addressed in WordPress core:

<img width="1532" alt="Log_In__Chassis_Site__WordPress_2022-11-02_15-16-04" src="https://user-images.githubusercontent.com/1377956/199404042-6835da77-d93e-4a8f-9fb6-0acd0c964398.png">

Looks like there are quite a few issues with 8.1 that still need to be addressed: https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&keywords=~php81&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&order=priority

**Comment by BronsonQuick** [comment]
It's been a while since I've provisioned a new box on 8.1 but it looks like this was fixed in one of the WP releases and I missed it! 🎉
