### ISSUE TITLE
Chassis only uses the Arm box on Arm if the mode is set to base

### ISSUE THREAD

**Issue by tomjn** [Chassis/Chassis#988]
If you run an Apple Silicon device and use parallels it will try to use the amd64/x86 box if the mode is set to normal.

There is a check to change it to the arm64 box, but this is only running when the mode is base:

```ruby
	# The Parallels Provider uses a different naming scheme.
	config.vm.provider :parallels do |_v, override|
		unless CONF['_mode'] == "normal"
			# Vagrant currently runs under Rosetta on M1 devices. As a result,
			# this seems to be the most reliable way to detect whether or not we're
			# running under ARM64.
			if Etc.uname[:version].include? 'ARM64'
				override.vm.box = 'mpasternak/focal64-arm'
			end
		end
	end
```

instead, until an arm64 chassis box is built it should instead force the `CONF['_mode']` value to `base`

**Comment by BronsonQuick** [comment]
This is by design at the moment and it's been documented.

Do you know if there's a way to detect in in the `Vagrantfile`? If we can detect it then I'm happy to add it. I don't have a Silicon chip so I can't test it but if you do a PR for us then I'll be happy to test the backwards compatibility and merge it in. Taa!

**Comment by tomjn** [comment]
I believe it's in the code block above, here is VVV's check to auto-switch our config to use the Parallels provider by default if Arm64 is detected as the chipset:

```ruby
# if Arm default to parallels
if Etc.uname[:version].include? 'ARM64'
  defaults['provider'] = 'parallels'
end
```

**Comment by tomjn** [comment]
Perhaps the code I quoted can be simplified to:

```ruby
	# The Parallels Provider uses a different naming scheme.
	config.vm.provider :parallels do |_v, override|
		# Vagrant currently runs under Rosetta on M1 devices. As a result,
		# this seems to be the most reliable way to detect whether or not we're
		# running under ARM64.
		if Etc.uname[:version].include? 'ARM64'
			override.vm.box = 'mpasternak/focal64-arm'
		end
	end
```

Then perhaps in `def self.normalize_config(config)` in `puppet/chassis.rb` it can do a check like this:

```ruby
		if Etc.uname[:version].include? 'ARM64'
			config['_mode'] = 'base'
		end
```

What do you think?

**Comment by BronsonQuick** [comment]
@tomjn That looks great to me! Any chance you'd be able to pop up a PR for that and let me know if it works as expected for you then I'll test backwards compatibility on my Intel chip. Thanks!

**Comment by tomjn** [comment]
I've very very limited bandwidth available to do this, it may take a few weeks/**_months_** before I can get to this

Note that the code I shared is almost guaranteed to work though and is extremely similar to work done elsewhere

**Comment by BronsonQuick** [comment]
@tomjn Sorry for the epic delay on this. I'm doing some catching up now. I've added your fix. Hopefully it works for you. If you get a chance could you please do a little test for me? Thanks man!
