### ISSUE TITLE
Not working after update to Ventura

### ISSUE THREAD

**Issue by rogercoathup** [Chassis/Chassis#992]
Updated to Ventura and vagrant up is failing for all my chassis installs.

Intial error was:

```
roger@Rogers-MacBook-Pro content % vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running action triggers before up ...
==> default: Running trigger...
==> default: Checking if box 'chassis/chassis' version '5.0.0' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 95 of file VBoxManageHostonly.cpp
```

I then:

Updated vagrant to version 2.3.4
Updated virtual box from v6 to v7

And tried setting up a clean chassis install.  I'm now seeing the following error:

```
roger@Rogers-MacBook-Pro testventura % vagrant up                       
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running action triggers before up ...
==> default: Running trigger...
==> default: Checking if box 'chassis/chassis' version '5.0.1' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
A customization command failed:

["guestproperty", "set", :id, "/Chassis/synced_folders", "{\"/var/log/nginx\":\"/Users/roger/Development/testventura/logs/nginx\",\"/var/log/php\":\"/Users/roger/Development/testventura/logs/php\",\"/vagrant\":\"/Users/roger/Development/testventura\",\"/vagrant/extensions/_global\":\"/Users/roger/.chassis/extensions\"}", "--flags", "TRANSIENT,RDONLYGUEST"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["guestproperty", "set", "e127ee13-b433-4032-9aa1-b03afd32025c", "/Chassis/synced_folders", "{\"/var/log/nginx\":\"/Users/roger/Development/testventura/logs/nginx\",\"/var/log/php\":\"/Users/roger/Development/testventura/logs/php\",\"/vagrant\":\"/Users/roger/Development/testventura\",\"/vagrant/extensions/_global\":\"/Users/roger/.chassis/extensions\"}", "--flags", "TRANSIENT,RDONLYGUEST"]

Stderr: VBoxManage: error: Properties with TRANSIENT or TRANSRESET flag cannot be set or modified if VM is not running
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SetGuestProperty(Bstr(pszName).raw(), Bstr(pszValue).raw(), Bstr(pszFlags).raw())" at line 156 of file VBoxManageGuestProp.cpp
>

Please fix this customization and try again.

```

**Comment by rogercoathup** [comment]
Machine is 2019 MacBook Pro Intel Core i9

**Comment by tomjn** [comment]
@rogercoathup did you reinstall and reboot your machine after making changes to VirtualBox?

VirtualBox requires kernel level extensions to be present to work. These can be removed or isolated when you do an OS level upgrade, and they also require you to do a system restart when those extensions either change/update or are added/installed. Most people think this is something that happens on Windows as it's rare to see on Apple devices.

When Virtualbox kernel extensions aren't present it usually shows as either extremely unreliable network connections from or to the VM, or in messages such as the one you first shared:

```
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
```

Which heavily implies an incomplete VirtualBox install.

Unfortunately nothing can be done at the Chassis end of things as this isn't a Chassis problem. Likewise you'd face the same issue with any other vagrant project, or even if you manually set up VirtualBox VMs.

1. So I would start with a system reboot.
2. If that doesn't work ( and sometimes a second reboot helps ), re-running the VirtualBox installer can help
3. Do not downgrade VirtualBox, and if you have to uninstall it, restart. There is no such thing as a clean install if you do not restart as old kernel extensions will be loaded
4. There are `kext` commands that can list the active virtualbox extensions to confirm they are present, if you see no such extensions then they are not present or not loaded
```sh
❯ kextstat | grep -v com.apple
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  178    3 0xffffff7fa2326000 0xb2000    0xb2000    org.virtualbox.kext.VBoxDrv (6.1.16) DAF044F0-5043-3B8E-8758-5A462567BDAA <8 6 5 3 1>
  183    0 0xffffff7fa2403000 0x5000     0x5000     org.virtualbox.kext.VBoxUSB (6.1.16) CA33FA52-5933-3F0E-9B40-8B1ECF4D6A36 <182 178 66 8 6 5 3 1>
  184    0 0xffffff7fa23fe000 0x4000     0x4000     org.virtualbox.kext.VBoxNetFlt (6.1.16) C93EAF6A-676F-3370-BAE2-BDFD2BF16582 <178 8 6 5 3 1>
  185    0 0xffffff7fa23f8000 0x2000     0x2000     org.virtualbox.kext.VBoxNetAdp (6.1.16) 76200407-D2F0-3D84-BCCF-7EEA18F16654 <178 6 5 1>
```

Note that it's not possible to load or unload kernel extensions in normal mode, a reboot is necessary. The only way to do it via a command at runtime usually requires rebooting into safe or recovery mode. It's also not something you will see on Apple Silicon devices.

For info on VirtualBox kernel extensions, see this issue in the VVV repo:

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2637#issuecomment-1299154456

In particular https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2637#issuecomment-1299993485

**Comment by rogercoathup** [comment]
I've been through several reboots and reinstalls of VirtualBox (v7.0.4).  Nothing showing in the security section of system preferences, but still getting this error message on vagrant up (not its

**Comment by tomjn** [comment]
did you run the kernel extension commands I shared? What was the output? Most people I know who encounter this resolve it by reinstalling VirtualBox ( the same version )

**Comment by tomjn** [comment]
And can you confirm the VMs status using VirtualBox's UI? What's the output of `kextstat | grep -v com.apple`? DId you try any of the other commands in the issues I linked to?

**Comment by BronsonQuick** [comment]
Hey @rogercoathup, I did have a crack at upgrading to VirtualBox 7.0 a few weeks ago and I think I had the same issue. I was still on Monterey. I'd seen that issue in the past for old version and tried some of the things that @tomjn mentioned as they'd worked in the past but I didn't have any luck. Can you please try downgrading to VirtualBox 6.1.40 and see if that fixes it?

**Comment by rogercoathup** [comment]
@tomjn -- my understanding is that kexts aren't applicable to VirtualBox 7.x  https://forums.virtualbox.org/viewtopic.php?f=8&t=107680#p527278

**Comment by rogercoathup** [comment]
Note: I tried installing an Ubuntu vagrant (https://app.vagrantup.com/ubuntu/boxes/focal64) to check VirtualBox 7 / Vagrant was working in general on Ventura.

**Comment by BronsonQuick** [comment]
Hey @rogercoathup I've just been having a look at VirtualBox 7.x again on Monterey and I've hit this issue as well. I've got a fix for it here: https://github.com/Chassis/Chassis/pull/997

I'm just going to downgrade back to VirtualBox 6.1.40 to make sure it still works with that. If it does then I'll merge that change in and it should fix the issue you were having. I think it was to do with some changes on VirtualBox 7.x rather than Ventura. I should also note that I'm using Vagrant 2.3.4.

**Comment by BronsonQuick** [comment]
I've confirmed that this change is backwards compatible so I'll merge that fix in now. @rogercoathup sorry about the delay on this one. Let me know if it's working on Ventura as well please! Thanks! 🙏🏻

**Comment by BronsonQuick** [comment]
I just upgraded to Ventura and I can confirm that the latest changes are working as expected with VirtualBox `7.0.4r154605` and Vagrant `Vagrant 2.3.4`

**Comment by tomjn** [comment]
@BronsonQuick what was the problem/fix? I see you removed a parameter from a shared folder but I'm not sure what it did

**Comment by BronsonQuick** [comment]
@tomjn those parameters only worked in the box was already provisioned. Technically it wasn't ever working correctly but in the past it was failing silently.

That line was only ever added so we could get the details of those folders in the Chassis Desktop app that we were building in Electron. We didn't end up finishing that one so it's not a big issue for us thankfully 😅

**Comment by dirad** [comment]
I have this same issue on Windows 10.
errors out on the folder sync: 
``` Command: ["guestproperty", "set", "ab512a79-af8f-4a5e-ad28-86e2da2cf4fe", "/Chassis/synced_folders", "{\"/var/log/nginx\":\"C:/web_project/logs/nginx\",\"/var/log/php\":\"C:/web_project/logs/php\",\"/vagrant\":\"C:/web_project\"}", "--flags", "TRANSIENT,RDONLYGUEST"]      ```
Not sure when this started, but I think before installing VirtualBox 7.
Using Vagrant 2.3.4

Some boxes actually end up working by running them from the Virtual Box GUI, but some dont..
Is there something I can do? [should I open a new issue?]

**Comment by BronsonQuick** [comment]
@dirad Hey there, so that line was removed 3 weeks ago here: https://github.com/Chassis/Chassis/commit/0240128751c1f5b1e487cc7fea857459bd03fedd which means whichever project you're using Chassis on has the old code there. You should able to do a `git pull` in that Chassis project and that line should disappear and things should work as expected for you

**Comment by dirad** [comment]
@BronsonQuick  Thanks.  I did end up doing a `git pull` and it was fine.    I do wonder why this would happen though... Is it the the Vbox update?  
Also, and maybe this is worth a new issue - What is the 'right' way to do a Chassis update in such a scenario?   Meaning - What do do with the changed files [for exmaple config.yaml]   
I know there are several options, [i ended up with stashing everything and then rewriting it...] but what is the best / recommended one?  🙏🙏

**Comment by BronsonQuick** [comment]
@dirad That error that you encountered was due to the VB 7.x update. They changed the way they handled some things internally. That line of code that I removed to fix it was something that we had in there when we were working on a GUI for Chassis Desktop. We didn't end up having the time to complete it and launch it so I was happy to remove that line 😅 

In theory with a Chassis upgrade you should just be able to do a `git pull` and you'll have the latest changes as well as the latest version of WP too. There shouldn't be any config files that will be overwritten so if you have modified `config.yaml` in the root of the project then I'd recommend creating a `config.local.yaml` in the root directory that has just the overrides you need for your project. There are a few version of the config files that you can create which contain your overrides. Checkout https://docs.chassis.io/en/latest/config/#configuration as that covers those. Those files are all ignored by git so they should retain all your changes. If you follow that configuration then an update is as easy as https://docs.chassis.io/en/latest/quickstart/#updating

**Comment by dirad** [comment]
Thanks a bunch @BronsonQuick !
